### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/martinjr/Downloads/Atom.app'

### ISSUE THREAD

**Issue by mpatino117** [atom/settings-view#724] opened 2016-01-19 03:37 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.232.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/martinjr/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/martinjr/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:53:23)
    at Object.<anonymous> (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:12:41)
    at Object.<anonymous> (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:361:4)
    at Module._compile (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/main.js:18:28)
    at Object.<anonymous> (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at Module._compile (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:10:10)
    at Object.<anonymous> (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:369:4)
    at Module._compile (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/martinjr/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-01-19 03:38
Thanks for reporting!  This looks like a duplicate of #9559 though, so feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-01-19 03:38 UTC
