### ISSUE TITLE
Avatars not shown after Atom update

### ISSUE THREAD

**Issue by rugk** [atom/settings-view#706] opened 2015-11-25 18:59 UTC
After updating to Atom v1.2.4 the avatars are broken:
![avatar](https://cloud.githubusercontent.com/assets/11966684/11406689/f4fe26b2-93ae-11e5-8973-fb0df8e1432e.PNG)
(screenshot from "packages")

Related to https://github.com/atom/settings-view/issues/327 possibly.

Windows 7 x64

**Comment by rugk** [comment] 2015-11-25 19:00
Note that a few are displayed correctly, but most are broken:
![avatarsafew](https://cloud.githubusercontent.com/assets/11966684/11406744/392362d0-93af-11e5-97f4-f43169825e89.PNG)

**Comment by mnquintana** [comment] 2015-11-25 19:04
Thanks for the report! This does looks like a duplicate of https://github.com/atom/settings-view/issues/327 to me - feel free to subscribe there for updates.

**Closed by mnquintana** 2015-11-25 19:04 UTC
