### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by cassianoleal** [atom/settings-view#792] opened 2016-05-20 12:32 UTC
1. Open Settings / Updates
2. Fail to update a package (in my case I couldn't reach `github.com`)

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At /opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709

TypeError: Cannot read property 'substr' of null
    at /opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709:80
    at /opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:51
    at /opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:403:20
    at exit (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -0:58.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dracula-theme.theme-dracula-ui)
     -0:58.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dracula-theme.theme-dracula-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vertical-align",
      "term2",
      "autocomplete-ruby",
      "welcome",
      "metrics",
      "language-toml",
      "language-sass",
      "language-perl",
      "language-objective-c",
      "language-less",
      "language-java",
      "language-git",
      "language-csharp",
      "language-coffee-script",
      "language-clojure",
      "language-c",
      "keybinding-resolver",
      "language-mustache",
      "valign",
      "minimap-autohide",
      "linter-foodcritic",
      "language-chef",
      "activate-power-mode"
    ],
    "themes": [
      "dracula-ui",
      "dracula-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.22.0
aligner-puppet, v0.1.1
aligner-python, v1.0.1
aligner-ruby, v1.4.0
atom-cli-diff, v1.3.0
atom-erb, v0.2.0
atom-meld, v0.2.1
atom-pair, v2.0.10
atom-python-debugger, v0.3.4
auto-indent, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.3
docs-snippets, v0.8.0
dracula-theme, v1.2.5
dracula-ui, v0.3.0
editorconfig, v1.4.1
file-watcher, v0.4.0
git-log, v0.4.1
git-projects, vundefined
git-tab-status, v1.9.2
highlight-selected, v0.11.2
language-ansible, v0.1.6
language-apache, v1.5.0
language-bats, v0.1.0
language-docker, v1.1.6
language-puppet, v0.19.1
language-rspec, v0.5.0
language-scala, v1.1.6
language-terraform, v0.7.4
language-x86-64-assembly, v2.1.11
line-ending-converter, v1.3.2
linter, v1.11.4
linter-ansible-linting, v1.1.2
linter-erb, v1.0.2
linter-js-yaml, v1.2.5
linter-jshint, v2.1.0
linter-puppet-lint, v0.6.3
linter-puppet-parse, v0.6.0
linter-ruby, v1.2.2
linter-shellcheck, v1.2.0
markdown-scroll-sync, v2.1.2
merge-conflicts, v1.4.2
minimap, v4.23.5
minimap-bookmarks, v0.3.1
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-selection, v4.4.0
motepair, v0.21.0
project-colorize, v0.2.0
project-manager, v2.9.7
project-view, v0.5.0
python-iresolve, v0.0.3
python-tools, v0.6.7
remote-edit, v1.8.24
rest-client, v1.1.0
rspec-snippets, v0.4.0
ruby-block, v0.3.5
serverspec-snippets, v0.1.1
ssh-config, v0.10.1
sync-settings, v0.7.2
synced-sidebar, v0.4.3
tidy-markdown, v3.0.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

### Package update error log:

```
npm ERR! git clone --template=/Users/cassiano/.atom/.apm/_git-remotes/_templates --mirror git://github.com/slang800/tidy-markdown.git /Users/cassiano/.atom/.apm/_git-remotes/git-github-com-slang800-tidy-markdown-git-9837029c: Cloning into bare repository '/Users/cassiano/.atom/.apm/_git-remotes/git-github-com-slang800-tidy-markdown-git-9837029c'...
npm ERR! git clone --template=/Users/cassiano/.atom/.apm/_git-remotes/_templates --mirror git://github.com/slang800/tidy-markdown.git /Users/cassiano/.atom/.apm/_git-remotes/git-github-com-slang800-tidy-markdown-git-9837029c: fatal: unable to connect to github.com:
npm ERR! git clone --template=/Users/cassiano/.atom/.apm/_git-remotes/_templates --mirror git://github.com/slang800/tidy-markdown.git /Users/cassiano/.atom/.apm/_git-remotes/git-github-com-slang800-tidy-markdown-git-9837029c: github.com[0: 192.30.252.129]: errno=Host is down
npm ERR! Darwin 15.5.0
npm ERR! argv "/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app/apm/bin/node" "/opt/homebrew-cask/Caskroom/atom/1.7.3/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/cassiano/.atom/.apm/.apmrc" "--userconfig" "/Users/cassiano/.atom/.apmrc" "install" "/private/var/folders/yx/7h7_xvts09q287cqmyhmrfzh0000gp/T/d-116420-51999-11o22n2/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/Users/cassiano/.atom/.apm/_git-remotes/git-github-com-slang800-tidy-markdown-git-9837029c'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=Host is down
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/yx/7h7_xvts09q287cqmyhmrfzh0000gp/T/apm-install-dir-116420-51999-4ujxzo/npm-debug.log
```

**Comment by Kerveck** [comment] 2016-05-22 21:35
i have  same problem.
Ubuntu, atom 1.7.3
/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:709
Show Stack Trace
The error was thrown from the settings-view package. This issue has already been reported.
View Issue

**Comment by wolfgang42** [comment] 2016-05-23 04:25
This looks like a duplicate of #753.

**Comment by 50Wliu** [comment] 2016-05-23 16:06
Closing in favor of #766.

**Closed by 50Wliu** 2016-05-23 16:06 UTC

**Comment by varosi** [comment] 2016-06-02 12:50
C:\Users\varosi\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\settings-view\lib\package-card.js:709
Hide Stack Trace
TypeError: Cannot read property 'substr' of null
    at C:\Users\varosi\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\settings-view\lib\package-card.js:709:80
    at C:\Users\varosi\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:376:51
    at C:\Users\varosi\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:403:20
    at exit (C:\Users\varosi\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\varosi\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:215:47)
    at C:\Users\varosi\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:222:18
    at Socket.<anonymous> (C:\Users\varosi\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

**Comment by Shobhit1** [comment] 2016-06-22 17:11
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1


### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709

TypeError: Cannot read property 'substr' of null
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709:80
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:51
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:403:20
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -2:47.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.compact-tab-bar.panel-contrast.use-animations.compact-tree-view.theme-monokai.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint"
    ],
    "themes": [
      "atom-material-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.8
atom-material-ui, v1.2.13
auto-detect-indentation, v1.1.0
compare-files, v0.6.2
git-diff-details, v1.3.0
highlight-selected, v0.11.2
language-babel, v2.28.0
linter, v1.11.10
minimap-highlight-selected, v4.4.0
monokai, v0.18.0
open-recent, v5.0.0
pigments, v0.29.2
react, v0.15.0
tab-switcher, v1.5.3

# Dev
No dev packages
```

**Comment by dhruvdutt** [comment] 2016-06-24 10:51
[Enter steps to reproduce below:]

1. Open Settings / Updates
2. Fail to update a package 

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1


### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At C:\Users\dhruvdutt\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:709

TypeError: Cannot read property 'substr' of null
    at C:\Users\dhruvdutt\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:709:80
    at C:\Users\dhruvdutt\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:376:51
    at C:\Users\dhruvdutt\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:403:20
    at exit (C:\Users\dhruvdutt\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\dhruvdutt\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\dhruvdutt\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -5:09.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-atom-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "automaticallyUpdate": false,
    "disabledPackages": [
      "jscs-fixer",
      "linter-jscs",
      "linter-jshint",
      "linter-less",
      "docblockr",
      "language-babel",
      "angularjs",
      "language-go",
      "language-java",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "language-yaml",
      "language-c",
      "language-clojure",
      "language-csharp",
      "react",
      "minimap"
    ],
    "projectHome": "F:\\Projects",
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-ternjs, v0.14.2
autoclose-html, v0.23.0
css-spy, v0.5.1
file-icons, v1.7.15
highlight-selected, v0.11.2
indent-guide-improved, v1.4.9
less-than-slash, v0.13.0
linter, v1.11.14
merge-conflicts, v1.4.4
selector-to-tag, v0.4.1
tool-bar, v0.4.0
tool-bar-atom, v1.5.0

# Dev
No dev packages
```

**Comment by Kreshnik** [comment] 2016-07-03 14:56
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1


### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709

TypeError: Cannot read property 'substr' of null
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709:80
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:51
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:403:20
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -0:42.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "dev-live-reload",
      "auto-indent"
    ],
    "projectHome": "/Users/Ninxha/Sites"
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
auto-update-packages, v1.0.1
autoclose-html, v0.23.0
autocomplete-go, v1.1.0
autocomplete-paths, v1.0.2
builder-go, v1.0.0
change-case, v0.6.0
color-picker, v2.1.1
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.15
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
highlight-selected, v0.11.2
jshint, v1.8.5
linter, v1.11.14
merge-conflicts, v1.4.4
navigator-godef, v1.0.3
pigments, v0.29.3
terminal-plus, v0.14.5
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by DavidePastore** [comment] 2016-07-07 19:51
[Enter steps to reproduce below:]

1. Open Settings / Updates
2. Fail to update a package

**Atom Version**: 1.7.2
**System**: Unknown Windows Version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1


### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At C:\Users\Davide\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:709

TypeError: Cannot read property 'substr' of null
    at C:\Users\Davide\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:709:80
    at C:\Users\Davide\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:376:51
    at C:\Users\Davide\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:403:20
    at exit (C:\Users\Davide\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Davide\AppData\Local\atom\app-1.7.2\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Davide\AppData\Local\atom\app-1.7.2\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -2:28.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-html, v0.7.2
docblockr, v0.7.3
editorconfig, v1.4.1
language-html, v0.43.1
language-r, v0.4.1
markdown-preview-plus, v2.4.0
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by tonydiep** [comment] 2016-07-11 12:34
Updating on Fedora 24 fails. See error message below

Updating to “markdown-writer@2.4.0” failed.Hide output…
/bin/sh: /bin/electron: No such file or directory


gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@4.4.5 | linux | x64
gyp ERR! install error 
gyp ERR! stack Error: Invalid version number: undefined
gyp ERR! stack     at install (/usr/lib/node_modules/node-gyp/lib/install.js:50:21)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/lib/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at run (/usr/lib/node_modules/node-gyp/bin/node-gyp.js:72:30)
gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/node-gyp/bin/node-gyp.js:133:1)
gyp ERR! stack     at Module._compile (module.js:409:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:416:10)
gyp ERR! stack     at Module.load (module.js:343:32)
gyp ERR! stack     at Function.Module._load (module.js:300:12)
gyp ERR! stack     at Function.Module.runMain (module.js:441:10)
gyp ERR! stack     at startup (node.js:139:18)
gyp ERR! System Linux 4.6.3-300.fc24.x86_64
gyp ERR! command "/usr/lib/node_modules/atom-package-manager/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=undefined" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /home/tonydiep/.atom
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

**Comment by tarnagas** [comment] 2016-07-12 07:12
Same issue.

**Comment by tonydiep** [comment] 2016-07-12 10:31
On Fedora 24 I traced the problem to the fact that the electron rpm did not install itself properly.

sudo dnf reinstall electron

created the correct symlinks and allowed the markdown-writer package to then update itself correctly.  Your mileage may vary.

**Comment by 50Wliu** [comment] 2016-07-15 01:09
I'm locking this issue as it is a duplicate of #766 and the amount of activity in this issue is a bit distracting.  To anyone arriving here from the big red popup, Google, or somewhere else, please subscribe to #766 instead.  Thanks!
