### ISSUE TITLE
Disable package doesn't show settings when enabled

### ISSUE THREAD

**Issue by ungb** [atom/settings-view#1003] opened 2017-09-28 17:58 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Disable package doesn't show settings when enabled

### Steps to Reproduce

1. Disable a package that has settings (e.g whitespace package) in settings view
2. Close settings view
3. reopen settings view and reenable the package and click on settings

**Expected behavior:** [What you expect to happen]
Settings for package should show up 

**Actual behavior:** [What actually happens]
Settings doesn't populate until after closing and reopening Atom 

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

![clock](https://user-images.githubusercontent.com/5624870/30982239-a4e77d50-a43b-11e7-8b17-62045627a5ee.gif)

### Versions
```
Atom    : 1.22.0-dev-1880e1401
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

```

Can Repro on atom 1.15.0 too

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by t9md** [comment] 2018-01-26 17:14
I investigated this and I think I'm now clear for the cause.

It's panel cache(`this.panelsByName`) kept in `SettingsView` instance.
Could fix locally, by removing panel cache on by registering observer in `constructor`.

I will send PR after cleanup my local code mess.
(:thought_balloon: README.md cache part should not invalidate? need more smarter/partial invalidation??)

```javascript
atom.packages.onDidActivateInitialPackages(() => {
  console.log('start observing')
  this.disposables.add(
    atom.packages.onDidActivatePackage(pack => {
      console.log('activated', pack.name)
      this.deletePanelCache(pack.name)
    }),
    atom.packages.onDidDeactivatePackage(pack => {
      console.log('deactivated', pack.name)
      this.deletePanelCache(pack.name)
    })
  )
})
```


![setting-view](https://user-images.githubusercontent.com/155205/35451638-40ab4efe-0307-11e8-8602-41cb50e86927.gif)

**Comment by maralv** [comment] 2018-11-13 17:37
I'm interested in solving this issue and I've successfully reproduced it. However, the following statement by @ungb seems to be obsolete:
> Settings doesn't populate until after closing and reopening Atom.

The settings view does populate by just closing and reopening it, no need to close and reopen Atom itself. Is anyone working on this issue?

**Comment by rsese** [comment] 2018-11-14 20:13
Thanks @maralv :+1:

> However, the following statement by @ungb seems to be obsolete:
> 
> > Settings doesn't populate until after closing and reopening Atom.

Looks like I can't reproduce either on 1.32.2.

@t9md - since this issue doesn't seem to reproduce anymore (let me know if I'm mistaken), is https://github.com/atom/settings-view/pull/1044 still necessary in your opinion?

**Comment by t9md** [comment] 2018-11-16 01:08
I cannot remember what the original issue is.

But yes, I agree that we no longer need close/reopen Atom itself to make setting fields appear after disable/enabled pkg.

I have not to revisit my PR.
I think the current behavior is still non-intuitive, setting fields should appear immediately once use clicks `Enable` button.

**Closed** 2019-01-14 20:55 UTC
Labels: bug, triaged
