### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by alex** [atom/settings-view#476] opened 2015-04-23 02:31 UTC
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:247:11)
PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:155:26)
PackageDetailView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:145:12)
PackageDetailView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
```

**Comment by thomasjo** [comment] 2015-04-23 06:11
This is caused by one of your installed packages. Re-open this issue on the offending package's repo. Tracking down the offending repo might be a little bit tricky if you have many installed.

---
Ideally we should not be seeing these with settings-view as the offender. The package being activated should be marked as the offender.

/cc @atom/core (@kevinsawicki @nathansobo @maxbrunsfeld @thedaniel @benogle, etc)

**Closed by thomasjo** 2015-04-23 06:11 UTC

**Comment by izuzak** [comment] 2015-04-25 10:16
> Ideally we should not be seeing these with settings-view as the offender. The package being activated should be marked as the offender.

@thomasjo Yep, you're right. This should be fixed with https://github.com/atom/atom/pull/6510.
