### ISSUE TITLE
Uncaught TypeError: Cannot read property 'showPanel' of null

### ISSUE THREAD

**Issue by gabrielc63** [atom/settings-view#298] opened 2014-12-27 14:47 UTC
[Enter steps to reproduce below:]

1. open atom from terminal

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.161.0

### Stack Trace

Uncaught TypeError: Cannot read property 'showPanel' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/main.js:19

TypeError: Cannot read property 'showPanel' of null
  at openPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/main.js:19:24)
  at atom-workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/main.js:56:16)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at PackageUpdatesStatusView.jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-updates-status-view.js:39:17)
  at HTMLDivElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "atom-spotify",
      "minimap",
      "git-control"
    ],
    "themes": [
      "atom-dark-ui",
      "Lucario"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Lucario, v0.1.9
autocomplete-plus, v1.0.0
autocomplete-snippets, v0.3.1
file-icons, v1.4.3
language-swift, v0.3.0
linter, v0.9.0
linter-ruby, v0.1.4
preview-tabs, v0.1.6
run-in-browser, v0.1.1
save-session, v0.11.1
script, v2.15.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by xdumaine** [comment] 2015-01-02 18:28
+1

**Comment by kevinsawicki** [comment] 2015-01-05 18:12
I believe this is a duplicate of https://github.com/atom/settings-view/issues/285

**Closed by kevinsawicki** 2015-01-05 18:12 UTC
