### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by yichen123** [atom/settings-view#592] opened 2015-07-17 02:29 UTC
[Enter steps to reproduce below:]

1. I don't if i did something bad before, but this message shows up every time when i am trying to update my installed packages(even core packages), and the updates failed
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:56

TypeError: Cannot read property 'message' of undefined
  at ErrorView.module.exports.ErrorView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:56:21)
  at ErrorView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new ErrorView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:14:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/updates-panel.js:84:44
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:579:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:303:17
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:326:20
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "localization",
      "localization",
      "localization"
    ],
    "themes": [
      "atom-light-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-07-17 02:30
This is a duplicate of #577 – it's been fixed for the next release of Atom.

**Closed by mnquintana** 2015-07-17 02:30 UTC

**Comment by yichen123** [comment] 2015-07-17 02:32
cool, good to know that, thanks
