### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/jcastro/.atom/packages/autocomplete-plus/lib/provider.coffee'

### ISSUE THREAD

**Issue by jcastro3** [atom/settings-view#393] opened 2015-02-25 01:37 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.183.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/jcastro/.atom/packages/autocomplete-plus/lib/provider.coffee'

```
At /Users/jcastro/Downloads/Atom.app/Contents/Resources/app/src/package.js:241

Error: ENOENT, no such file or directory '/Users/jcastro/.atom/packages/autocomplete-plus/lib/provider.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Users/jcastro/Downloads/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Users/jcastro/Downloads/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.exports._compileFile (/Users/jcastro/Downloads/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:206:14)
  at getSourceMap (/Users/jcastro/Downloads/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:314:22)
  at getSourceMapping (/Users/jcastro/Downloads/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:322:19)
  at formatSourcePosition (/Users/jcastro/Downloads/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:274:16)
  at /Users/jcastro/Downloads/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:340:34
  at Function.Error.prepareStackTrace (/Users/jcastro/Downloads/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:343:7)
  at Package.module.exports.Package.activateNow (/Users/jcastro/Downloads/Atom.app/Contents/Resources/app/src/package.js:241:79)
  at /Users/jcastro/Downloads/Atom.app/Contents/Resources/app/src/package.js:221:28
  at Package.module.exports.Package.measure (/Users/jcastro/Downloads/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Users/jcastro/Downloads/Atom.app/Contents/Resources/app/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Users/jcastro/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:464:21)
  at /Users/jcastro/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Users/jcastro/Downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Users/jcastro/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Users/jcastro/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Users/jcastro/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
  3x -8:58.9 core:backspace (atom-text-editor.editor)
  2x -8:51.9 core:save (atom-text-editor.editor)
     -3:23.9 editor:newline (atom-text-editor.editor)
     -1:12.7 settings-view:open (atom-text-editor.editor)
     -0:57.8 application:open-your-keymap (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai-light.theme-atom-dark-ui)
     -0:54.9 core:close (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai-light"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.2.1
file-icons, v1.4.2
less-autocompile, v0.3.3
linter, v0.10.0
monokai-light, v0.3.6
open-last-project, v0.1.1
tabular, v0.1.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-02-25 01:40
Duplicate of #388, please subscribe there for updates.

**Closed by 50Wliu** 2015-02-25 01:40 UTC
