### ISSUE TITLE
Settings not appearing on package's settings page

### ISSUE THREAD

**Issue by travs** [atom/settings-view#383] opened 2015-02-16 15:54 UTC
Manjaro Linux 0.8.12
Atom 0.179.0

When I go to view/change the settings for my installed packages, the parameters do not appear.

This was initially prompted by [an issue](https://github.com/travs/markdown-pdf/issues/42) over at my package, where the config settings were disappearing for a user.
I took a look and I get similar behaviour (the config settings never appear in the first place), and this occurs for all packages I install.

The image simply shows that there are no config settings appearing.
![](https://cloud.githubusercontent.com/assets/7369273/6214841/367344d6-b5d6-11e4-84e6-a534d060f781.png)

**Comment by 50Wliu** [comment] 2015-02-16 17:33
Refs #356?

**Comment by sindresorhus** [comment] 2015-04-08 08:51
I'm seeing this too. The weird thing is that using `module.exports` instead of multiple `exports` in my plugin seems to fix it. https://github.com/sindresorhus/atom-esformatter/pull/11

**Comment by hedefalk** [comment] 2015-04-10 19:48
Same problem here.

**Comment by mnquintana** [comment] 2015-04-13 18:47
Duplicate of #356 and resolved in #371

**Closed by mnquintana** 2015-04-13 18:47 UTC

**Comment by efatsi** [comment] 2016-01-20 21:03
I'm still seeing this issue in my package - https://github.com/vigetlabs/platomformio/blob/master/lib/platomformio.coffee#L5-L19

Is there something that I'm doing incorrectly?

**Comment by itotallyrock** [comment] 2017-04-16 07:36
I had the same problem but luckily stumbled upon a solution, and may help others.
My problem was that I had changed package names and thus my config had the old package still.  After I removed the old instance my package's settings reappeared.
