### ISSUE TITLE
Failed to activate the minimap package

### ISSUE THREAD

**Issue by johnmaia** [atom/settings-view#416] opened 2015-03-10 10:33 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to activate the minimap package

```
At undefined is not a function

TypeError: undefined is not a function
  at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:355:117)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:243:16)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
     -4:58.7 core:move-right (atom-text-editor.editor)
     -4:53.8 core:backspace (atom-text-editor.editor)
     -4:51.7 editor:consolidate-selections (atom-text-editor.editor)
     -4:51.7 core:cancel (atom-text-editor.editor)
     -4:50.2 core:backspace (atom-text-editor.editor)
     -4:49.5 core:save (atom-text-editor.editor)
     -2:49.4 remote-edit:browse (atom-pane.pane.active)
  2x -2:26.5 core:backspace (atom-text-editor.editor.mini)
  3x -2:25.2 core:confirm (atom-text-editor.editor.mini)
  2x -1:09.5 editor:newline (atom-text-editor.editor)
     -1:08.0 core:move-down (atom-text-editor.editor)
     -0:59.9 remote-edit:browse (atom-text-editor.editor)
  2x -0:46.7 core:backspace (atom-text-editor.editor)
     -0:45.7 editor:newline (atom-text-editor.editor)
     -0:43.8 core:backspace (atom-text-editor.editor)
     -0:43.2 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-flex, v0.2.0
minimap, v4.5.0
remote-edit, v1.7.2
remote-sync, v2.4.0

# Dev
No dev packages
```

**Comment by kevinhikaruevans** [comment] 2015-03-10 15:43
Happened on Windows 8.1 too.

**Comment by ev-mark** [comment] 2015-03-11 14:26
Updated minimap package from 4.3.1 to 4.5

If I then clicked through to settings the old version was still showing, if that helps.


**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to activate the minimap package

```
At undefined is not a function

TypeError: undefined is not a function
  at Package.module.exports.Package.activateServices (C:\Users\MarkGallacher\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:355:117)
  at Package.module.exports.Package.activateNow (C:\Users\MarkGallacher\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:243:16)
  at C:\Users\MarkGallacher\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:221:30
  at Package.module.exports.Package.measure (C:\Users\MarkGallacher\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\MarkGallacher\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\MarkGallacher\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:465:21)
  at C:\Users\MarkGallacher\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:226:29
  at exit (C:\Users\MarkGallacher\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\MarkGallacher\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\MarkGallacher\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
     -8:40.5 settings-view:open (atom-text-editor.editor)
     -0:45.8 snippets:next-tab-stop (atom-text-editor.editor)
     -0:45.8 snippets:expand (atom-text-editor.editor)
     -0:45.8 editor:indent (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
minimap, v4.5.0
monokai, v0.12.0
remote-edit, v1.7.2

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-03-12 12:33
I could reproduce this:

1. `apm install minimap@4.3.1`
2. Start Atom
3. Go to Settings View and click on Update All (to update the minimap package to the latest version)
4. Exception is thrown
5. If I quit and restart Atom -- no exceptions are thrown.

There seems to be [a bunch of issues like this one](https://github.com/atom/settings-view/issues?q=is%3Aissue+is%3Aopen+%22Failed+to+activate%22), for different packages, started happening recently. Any ideas why that might be happening @jlord @maxbrunsfeld? As far as I can tell, things are blowing up here:

https://github.com/atom/atom/blob/aaa607f1438b5fe68fbf2bc9732e4a97cec5a603/src/package.coffee#L227

```
@activationDisposables.add atom.packages.serviceHub.provide(name, version, @mainModule[methodName]())
```

So, the `@mainModule[methodName]()` call is failing, but not sure why. I just checked two packages, and as far as I can tell -- the main module has a method with the name listed in `providedServices`.

It seems as if `@mainModule` is the old version of the package (before the update) which doesn't have the `methodName` in the main module. I was expecting it to be the new version which is being activated (after the update). Is it possible that `@mainModule` wasn't refreshed with the new version of the package before that call was made?

**Comment by izuzak** [comment] 2015-03-12 12:38
Ahhh, just noticed that @mathiasvr already created a pull request to fix this: https://github.com/atom/settings-view/pull/423. :smile:

**Comment by 50Wliu** [comment] 2015-03-12 12:52
After #423 gets merged should these errors go on their corresponding repo?

**Comment by izuzak** [comment] 2015-03-12 13:00
@50Wliu I think this is a problem on our side, so no need to reopen these issues in packages. But lets see how it plays out. :athletic_shoe: :soccer:

**Comment by abe33** [comment] 2015-03-12 13:17
> It seems as if @mainModule is the old version of the package (before the update) which doesn't have the methodName in the main module. I was expecting it to be the new version which is being activated (after the update). Is it possible that @mainModule wasn't refreshed with the new version of the package before that call was made? 

That was also my hypothesis regarding #388 as we had a similar issue with atom-minimap/minimap#274.

**Comment by izuzak** [comment] 2015-03-12 13:23
Ahhh, I forgot about that one -- thanks for the :link:, @abe33! Pulling in @kevinsawicki for more :eyes: then.

**Comment by jlord** [comment] 2015-03-19 23:33
This https://github.com/atom/atom/pull/6026 should cover it :balloon:

**Closed by jlord** 2015-03-19 23:33 UTC
Labels: atom, bug
