### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by wedojava** [atom/settings-view#604] opened 2015-07-24 10:16 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Linux Mint
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/error-view.js:56

TypeError: Cannot read property 'message' of undefined
  at ErrorView.module.exports.ErrorView.initialize (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/error-view.js:56:21)
  at ErrorView.View (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new ErrorView (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/error-view.js:14:46)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/install-panel.js:156:44
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:579:27)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:359:17
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:384:20
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:04.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by koresar** [comment] 2015-07-24 11:17
Smae here. I just clicked "Install". Nothing else.

**Comment by danrfraser** [comment] 2015-07-24 12:08
I have the same issue on Windows 7.

**Comment by mnquintana** [comment] 2015-07-24 12:11
This is a duplicate of #577 – it's been fixed for the next release of Atom.

**Closed by mnquintana** 2015-07-24 12:11 UTC

**Comment by TheProfessionalNoob** [comment] 2015-07-24 14:20
I found this same issue on Windows 8. Roughly when will the version with the above mentioned fix be released

**Comment by Meligy** [comment] 2015-07-25 01:24
Just got it on Mac too

**Comment by danielbayley** [comment] 2015-07-25 17:08
Me 3 when trying to install the `atom-development-server` package.

**Comment by VincyLouis** [comment] 2015-07-26 03:18
The error still present, means this issue can't fix until the next version release?

**Comment by zbx1218** [comment] 2015-07-26 11:31
OSX too... I was installing one package.

**Comment by bojanv91** [comment] 2015-07-26 14:34
Windows 8.1 too. Wanted to evaluate Atom Editor for TypeScript coding... moving next I guess

**Comment by mnquintana** [comment] 2015-07-26 14:51
> it's been fixed for the next release of Atom.

**Comment by 50Wliu** [comment] 2015-07-26 14:51
1.0.3 should be out this week, but I can't guarantee that since I'm not a Github employee.
In the meantime, please try installing packages through the `apm install <package>` command (for instance, `apm install file-icons`).

@danielbayley That was probably a problem with atom.io - trying again a few hours later should fix the issue.

**Comment by n1889** [comment] 2015-07-27 09:35
Experienced on OSX while attempting to update regex-railroad-diagram

**Comment by sorousht** [comment] 2015-07-27 10:19
Just got on Windows too

**Comment by Hanpama** [comment] 2015-07-27 21:14
Got this error while trying to install seti-monokai theme

**Comment by mr-karan** [comment] 2015-07-28 18:50
Got this on Linux Mint 17.2 too while trying to install any package

**Comment by mnquintana** [comment] 2015-07-28 18:56
I'm sorry people are still running into this, but since this has already been fixed for the next release of Atom, I'm going to lock this issue to keep this from getting too noisy.

**Comment by 50Wliu** [comment] 2015-07-28 22:20
Atom 1.0.3 is now out.  If you're still running into this even on 1.0.3, please open a new issue.
