### ISSUE TITLE
Failed to activate the atom-material-syntax package

### ISSUE THREAD

**Issue by agentodessa** [atom/settings-view#693] opened 2015-11-06 15:04 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.230.0

### Stack Trace

Failed to activate the atom-material-syntax package

```
At Cannot set property 'textContent' of undefined

TypeError: Cannot set property 'textContent' of undefined
  at atom-styles.StylesElement.styleElementUpdated (C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\styles-element.js:133:37)
  at Emitter.module.exports.Emitter.emit (C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at StyleManager.module.exports.StyleManager.addStyleSheet (C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\style-manager.js:78:22)
  at ThemePackage.module.exports.Package.activateStylesheets (C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:283:52)
  at ThemePackage.module.exports.Package.activateNow (C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:229:14)
  at C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\theme-package.js:45:28
  at ThemePackage.module.exports.Package.measure (C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:153:15)
  at C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\theme-package.js:41:24
  at ThemePackage.module.exports.ThemePackage.activate (C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\theme-package.js:37:97)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:474:21)
  at C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\theme-manager.js:323:52
  at C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:551:16
  at C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:568:20
  at Emitter.module.exports.Emitter.emit (C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:753:29)
  at Config.module.exports.Config.setRawValue (C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:545:19)
  at Config.module.exports.Config.set (C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:215:14)
  at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\themes-panel.js:490:28)
  at C:\Users\Andrew.Melnikov\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\themes-panel.js:497:24

```

### Commands

```
     -0:36.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-material-syntax, v0.2.3
atom-typescript, v6.0.0
jsformat, v0.9.0
linter, v1.4.3
minimap, v4.13.2
pigments, v0.12.0
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2015-11-06 22:28
Was this when you launched the Settings View? Or when you did something within the Settings View?

**Comment by lee-dohm** [comment] 2015-12-17 07:19
Since there hasn't been a response to the request for more information, I'm going to close this. Please let us know if the issue reproduces for you!

**Closed by lee-dohm** 2015-12-17 07:19 UTC
Labels: more-information-needed, uncaught-exception
