### ISSUE TITLE
Regarding Package Installation(Type Error body.filter is not a function)

### ISSUE THREAD

**Issue by deoudit** [atom/settings-view#1072] opened 2018-08-17 10:15 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]
TypeError: body.filter is not a function
    at Request._callback (C:\Users\UDIT DEO\AppData\Local\atom\app-1.29.0\resources\app\node_modules\settings-view\lib\atom-io-client.js:305:39)
    at Request.self.callback (C:\Users\UDIT DEO\AppData\Local\atom\app-1.29.0\resources\app.asar\node_modules\settings-view\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\UDIT DEO\AppData\Local\atom\app-1.29.0\resources\app.asar\node_modules\settings-view\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (C:\Users\UDIT DEO\AppData\Local\atom\app-1.29.0\resources\app.asar\node_modules\settings-view\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Aerijo** [comment] 2018-08-17 10:29
Closing as duplicate of #1071

**Closed by Aerijo** 2018-08-17 10:29 UTC
