### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, unlink '~/Library/Application Support/Atom/Cac...

### ISSUE THREAD

**Issue by agos** [atom/settings-view#866] opened 2016-10-12 13:29 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.242.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, unlink '/Users/ago/Library/Application Support/Atom/Cache/settings-view/janosimas-1476278959276'

```
At fs.js:990

Error: ENOENT: no such file or directory, unlink '/Users/ago/Library/Application Support/Atom/Cache/settings-view/janosimas-1476278959276'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:990:18)
    at WriteStream.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/atom-io-client.js:221:18)
    at emitOne (events.js:95:20)
    at WriteStream.emit (events.js:182:7)
    at WriteStream.<anonymous> (fs.js:1933:12)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -0:16.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:12.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.9.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -0:02.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "language-javascript-better",
      "language-scala",
      "welcome",
      "merge-conflicts",
      "git-plus",
      "tree-view-git-branch",
      "spell-check",
      "linter-jshint",
      "minimap",
      "atom-ternjs",
      "angularjs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.5 (inactive)
angularjs-styleguide-snippets-es6, v1.0.3 (active)
atom-beautify, v0.29.13 (active)
atom-ternjs, v0.15.0 (inactive)
dash, v1.7.0 (inactive)
editorconfig, v1.4.1 (active)
emmet, v2.4.3 (active)
expand-region, v0.2.5 (inactive)
file-icons, v1.7.21 (active)
git-plus, v5.18.0 (inactive)
git-time-machine, v1.5.3 (inactive)
language-gettext, v0.6.1 (active)
language-scala, v1.1.6 (inactive)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
linter-jshint, v3.0.0 (inactive)
material-syntax, v0.5.0 (inactive)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.25.0 (inactive)
minimap-autohide, v0.10.1 (active)
minimap-git-diff, v4.3.1 (active)
monokai, v0.18.0 (inactive)
pigments, v0.37.0 (active)
pretty-json, v1.6.1 (active)
project-manager, v3.2.3 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
sort-lines, v0.14.0 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
toggle-quotes, v1.0.0 (inactive)
tree-view-git-branch, v0.1.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-10-12 15:34
This is a duplicate of #850 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-12 15:34 UTC
