### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/home/mike/.atom/packages/autocomplete-plus/lib/provider.coffee'

### ISSUE THREAD

**Issue by tal2211** [atom/settings-view#398] opened 2015-02-26 14:44 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: linux 3.11.0-26-generic
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.183.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/home/mike/.atom/packages/autocomplete-plus/lib/provider.coffee'

```
At /opt/atom/resources/app/src/package.js:241

Error: ENOENT, no such file or directory '/home/mike/.atom/packages/autocomplete-plus/lib/provider.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/opt/atom/resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/opt/atom/resources/atom/common/lib/asar.js:329:27)
  at Object.exports._compileFile (/opt/atom/resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:206:14)
  at getSourceMap (/opt/atom/resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:314:22)
  at getSourceMapping (/opt/atom/resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:322:19)
  at formatSourcePosition (/opt/atom/resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:274:16)
  at /opt/atom/resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:340:34
  at Function.Error.prepareStackTrace (/opt/atom/resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:343:7)
  at Package.module.exports.Package.activateNow (/opt/atom/resources/app/src/package.js:241:79)
  at /opt/atom/resources/app/src/package.js:221:28
  at Package.module.exports.Package.measure (/opt/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/opt/atom/resources/app/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app/src/package-manager.js:464:21)
  at /opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/opt/atom/resources/app/src/buffered-process.js:63:47)
  at /opt/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/opt/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -6:24.7 core:move-right (atom-text-editor.editor)
  9x -6:13.5 core:save (atom-text-editor.editor)
     -4:33.2 core:copy (atom-text-editor.editor)
     -4:31.8 core:paste (atom-text-editor.editor)
 13x -4:31.3 core:save (atom-text-editor.editor)
     -4:27.7 snippets:next-tab-stop (atom-text-editor.editor)
     -4:27.7 snippets:expand (atom-text-editor.editor)
     -4:27.7 editor:indent (atom-text-editor.editor)
 13x -3:54.9 core:save (atom-text-editor.editor)
  3x -3:44.4 core:delete (atom-text-editor.editor)
 23x -3:41.4 core:save (atom-text-editor.editor)
  2x -2:20.7 core:backspace (atom-text-editor.editor)
 12x -2:18.9 core:save (atom-text-editor.editor)
     -1:04.7 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-dark-ui.find-visible)
     -1:00.6 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-dark-ui.find-visible)
  3x -0:57.9 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-dark-ui.find-visible)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "symbols-view"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-light-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.17.1
atom-ctags, v2.5.1
autoclose-html, v0.15.0
bemhtml, v0.10.0
file-icons, v1.4.11
html-entities, v0.3.1
html-helper, v0.2.3
html-id-class-snippets, v1.4.1
language-html-swig, v1.2.0
language-mason, v2.0.0
open-last-project, v0.3.4
project-colorize, v0.1.0
smart-tag-cycle, v0.2.0
tag, v0.2.3

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-02-26 17:39
Duplicate of #88, please subscribe there for updates.

**Closed by 50Wliu** 2015-02-26 17:39 UTC
