### ISSUE TITLE
typing space in Settings triggers page jump

### ISSUE THREAD

**Issue by philxchen** [atom/settings-view#806] opened 2016-06-29 20:20 UTC
Whenever I type space key in any textbox in Settings panel, a page jump is triggered.

**Reproduction Steps:**

1. Open a tab in Settings panel (e.g. + Install)
2. Try to search something
3. When you type space, you can see a page jump

**Screenshots and GIFs**

![atom_trigger_pagejump](https://cloud.githubusercontent.com/assets/15373115/16467290/c0ab75a2-3e14-11e6-9046-1d7de76b5563.gif)

**Atom version:** 1.9.0-beta0
**OS and version:** Windows 10 build 14361

**Additional information:**

* Problem can be reproduced in safe mode: Yes
* Problem started happening recently, didn't happen in an older version of Atom: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by Ben3eeE** [comment] 2016-06-30 07:16
This is a duplicate of https://github.com/atom/settings-view/issues/767

**Closed** 2016-06-30 09:45 UTC
