### ISSUE TITLE
Package installer not working (neither using UI nor using apm) . I already set up http-proxy , https-proxy and strict-ssl = false. It is showing packages  searching them but not able to install them.

### ISSUE THREAD

**Issue by Abhivendra** [atom/settings-view#608] opened 2015-07-28 00:25 UTC
I am using atom under my Institutes proxy network . npm and bower are working fine after setting proxy . I don't have any clue why it is not working.
![apn error1](https://cloud.githubusercontent.com/assets/8620274/8920964/bfb032ea-34ed-11e5-9a83-2c732e631fcb.PNG)

![apm error2png](https://cloud.githubusercontent.com/assets/8620274/8921004/21749a34-34ee-11e5-8518-8aedd2c7c74a.PNG)

Packages are not downloading manually too. Cursor gets disable on clicking cloud download button.

**Comment by mnquintana** [comment] 2015-07-28 00:48
This is a duplicate of #577 – it's been fixed for the next release of Atom.

**Closed by mnquintana** 2015-07-28 00:48 UTC
