### ISSUE TITLE
Unable to view local, featured, or search for any packages.

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#533] opened 2015-06-09 02:01 UTC
_From @theoctopod on June 7, 2015 10:34_

Running version `0.207.0` on Windows 8.1.

Everything was running perfectly until I decided to make junction points from `C:\Users\<username>\AppData\Local` to `D:\Users\<username>\AppData\Local`, `C:\Users\<username>\AppData\LocalLow` to `D:\Users\<username>\AppData\LocalLow`, and `C:\Users\<username>\AppData\Roaming` to `D:\Users\<username>\AppData\Roaming` in order to free space on my C drive.

Anyway, ever since doing that, I was unable to search for any packages. The featured packages also fails with a seemingly uninformative error:
![](http://puu.sh/ifC5D/a5c3a514ce.png)

Also, viewing my local packages or themes doesn't work, as all the categories are frozen on "Loading packages...":
![](http://puu.sh/ifBOJ/ce82bb55d6.png)

In the Developer Console, there is an error about failing to fetch local packages:

```
Fetching local packages failed. Error: Fetching local packages failed.
  at D:\Users\<username>\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:83:21
  at exit (D:\Users\<username>\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:53:16)
  at triggerExitCallback (D:\Users\<username>\AppData\Local\atom\app-0.207.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (D:\Users\<username>\AppData\Local\atom\app-0.207.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```

I could revert the junction points as a last resort if that's the only way to fix this problem, but I was wondering if anyone could pinpoint the exact cause of this issue. 

_Copied from original issue: atom/atom#7153_

**Comment by mnquintana** [comment] 2015-06-09 02:01
Would you mind moving this to https://github.com/atom/settings-view?

**Comment by theoctopod** [comment] 2015-06-09 08:14
Yikes. Sorry you had to move it for me, I couldn't get back fast enough. 

Anyway, it's worth noting that the problem still exists on both a clean install of Atom (those screenshots were taken on a clean install) and with Atom's safe mode.

**Comment by cipherstream** [comment] 2015-10-30 15:34
I have the same problem, only I didn't attempt to create junction points. Any update on how this issue can be resolved?

**Comment by addui** [comment] 2016-02-18 21:10
I had the same problem on my work desktop but not my personal laptop or desktop. I started removing programs I had on my work desktop that was not on the other two and tested after each removal and I found that when I removed Cygwin it worked. I think you need to remove all programs which aim to replace cmd.exe

**Comment by lee-dohm** [comment] 2016-02-18 21:12
@damieng do you want to take a look at this?

**Comment by DMRobertson** [comment] 2016-04-05 19:05
I've just installed the stable version (1.6.2) and found myself with the same error. I haven't made any junction points (though it would be nice if we could choose where Atom installed to!). I opened the dev console and noticed errors. Here's the traceback it produced:
```
Uncaught (in promise) Error: Fetching local packages failed.
    at C:\Users\David\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:103:21
    at exit (C:\Users\David\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\David\AppData\Local\atom\app-1.6.2\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\David\AppData\Local\atom\app-1.6.2\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

I've also included a [short video](https://youtu.be/Q_OyDsYmmuA) where I tried to play around and cause some of these errors to appear in the console. At the start, I'm able to right click and "open in explorer" despite an error message telling me that atom failed to do so!

**Comment by DMRobertson** [comment] 2016-04-10 10:40
I think I've got this sorted. The problem seems to be similar to #533, where cmd.exe was attempting to run something via an AutoRun key in the registry. The 'something' triggered an error each time, preventing Atom from accessing apm's output---despite the fact that calling `apm ls --json` manually worked perfectly.

According to the help (`cmd.exe /?`), the command prompt looks for the registry keys

- `HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\EnableExtensions`
- `HKEY_CURRENT_USER\Software\Microsoft\Command Processor\EnableExtensions`

but neither was present on my machine. I searched for any key called Command Processor and I eventually found

- `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Command Processor`

(note the `Wow6432Node`). Its value was `"C:\Program Files (x86)\clink\0.4.4\clink" inject --profile "~\clink"`. I suppose I hadn't uninstalled [clink](https://github.com/mridgers/clink) correctly.
After I deleted this key, I could list and see packages in atom perfectly.

**Comment by jozsi** [comment] 2016-09-20 13:14
I am able to reproduce this on Windows when opening Atom from GitHub Desktop:
![image](https://cloud.githubusercontent.com/assets/840815/18671578/5146d7c2-7f4d-11e6-80bd-e3f7a37c5d01.png)

**Comment by edrow** [comment] 2016-09-29 17:02
I ran into the same problem...Windows 10, no changes to Atom or using any 3rd party app that replaces my CMD. All I did was Run As Admin for Atom and it resolved my issue, even though it was running fine without having to do that a few days ago. Hope this resolves it for some of you.

**Comment by damieng** [comment] 2016-09-29 17:47
This issue is becoming a kind of catch-all for anything resulting in apm not being called correctly from Atom.

What we need I think is some kind of output window in the case of failure where you can see exactly what went on in the console it spawned so we can correctly identify the various issues. Issues we've seen so far are;

1. AutoRuns interfering with expected output (should be solved by bypassing it in Atom)
2. Spaces in paths (might still be some of these left)
3. Unexpected double-quoted paths in the system PATH environment

**Comment by Neosublimation** [comment] 2016-10-27 09:09
I encountered a similar version of this problem with a twist. I get the same error as OP, but **not** if I start Atom via the start menu entry (which runs `C:\Users\Foo\AppData\Local\atom\Update.exe --processStart atom.exe`) or via `atom` in a `cmd.exe`, the [Git Bash](https://git-for-windows.github.io/) or a [Cygwin](https://www.cygwin.com/) terminal.

Unfortunately, the bug occurs with my most used way of starting Atom: Using the *Open with Atom* entry in the Windows Explorer context menu. I found an entry in the registry at `HKEY_CLASSES_ROOT\*\shell\Atom\command`, but it appears to not be the one used, because changing it had no effect for me (I've looked at the command using the ProcessExplorer and changed it to `cmd.exe` to test if it works). I will see, if it has an effect after the next boot.

However, the command I found for this entry in the registry was `"C:\Users\Foo\AppData\Local\atom\app-1.9.9\atom.exe" "%1"`, which obviously differs from the way the start menu link opens it. Could this cause such an issue?

Other things I've checked so far:
- the `COMSPEC` environment variable (https://github.com/atom/atom/issues/7986#issuecomment-123411913)
- the Command Processor/EnableExtensions keys in the registry (https://github.com/atom/settings-view/issues/533#issuecomment-207958438)
- the `PATH` variable for double quotes
- `apm ls --json`, which works in `cmd.exe` and the Git Bash, but fails in Cygwin because of path mush: `Error: Cannot find module 'C:\cygdrive\c\Users\Foo\AppData\Local\atom\app-1.11.2\resources\app\apm\lib\cli.js'`

Uninstalling Cygwin is no option for me, because I'd die of serious brain and nerve damage if I was forced to use a Windows terminal for development.

I'm using Windows 7 64 Bit and the following Atom version:
```
$ atom --version

Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by Ben3eeE** [comment] 2016-10-27 09:18
> However, the command I found for this entry in the registry was "C:\Users\Foo\AppData\Local\atom\app-1.9.9\atom.exe" "%1", which obviously differs from the way the start menu link opens it. Could this cause such an issue?

Yeah there was an issue with the auto updater and the new System tab in the `settings-view` causing the registry keys to not get updated correctly. What you should try is:

1. Completely exit all instances of Atom.
1. Launch Atom the way it works, from the start menu.
1. Open the `settings-view` with <kbd>Ctrl+,</kbd>.
1. Navigate to the System tab.
1. Check and uncheck all three options, this should rewrite the registry keys to be correct.
1. Check the options as you want.
1. Exit Atom.

**Comment by Neosublimation** [comment] 2016-10-27 09:57
@Ben3eeE This solved the issue for me. Thank you very much.

**Comment by damieng** [comment] 2017-03-20 01:46
The scenario where spaces were not corrected escaped has been fixed.

The scenario where autoruns were interfering with the output has been fixed.

The scenario with double-escaped PATH has been fixed.

I'm closing this issue - if you are running into something similar please raise a new issue with your details.

**Closed by damieng** 2017-03-20 01:46 UTC
Labels: needs-reproduction, windows
