### ISSUE TITLE
ENOENT

### ISSUE THREAD

**Issue by chrislewispac** [atom/settings-view#714] opened 2015-12-19 01:24 UTC
[Enter steps to reproduce below:]

1. Download Atom on new iMac
2. Attempt to go to settting view

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.232.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/chrislewis/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/chrislewis/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/lib/parse.js:4:18)
    at Module._compile (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/lib/cheerio.js:6:13)
    at Module._compile (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/index.js:5:28)
    at Module._compile (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/roaster/node_modules/task-lists/lib/index.js:4:11)
    at Module._compile (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/roaster/lib/roaster.js:14:15)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/roaster/lib/roaster.js:73:4)
    at Module._compile (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-readme-view.js:8:13)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-readme-view.js:72:4)
    at Module._compile (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:26:23)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:441:4)
    at Module._compile (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:24:23)
    at Object.<anonymous> (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:369:4)
    at Module._compile (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at createSettingsView (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:20:22)
    at /Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:71:28
    at Workspace.module.exports.Workspace.openURIInPane (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:454:22)
    at Workspace.module.exports.Workspace.open (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:393:19)
    at atom-workspace.atom.commands.add.settings-view:open (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:85:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Users/chrislewis/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1010:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:12.7.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:00.1.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-12-19 01:53
Hi @chrislewispac, thanks for reporting!  This looks like a duplicate of atom/atom#9813, so please subscribe there for updates.

**Closed by 50Wliu** 2015-12-19 01:53 UTC
