### ISSUE TITLE
Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by dhruvdutt** [atom/settings-view#828] opened 2016-08-08 13:06 UTC
[Enter steps to reproduce below:]

1. Opened JSX file from Fuzzy Finder.

**Atom Version**: 1.9.6
**System**: Microsoft Windows 10 Pro
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.238.0

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At C:\Users\dhruvdutt\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\settings-view\lib\package-card.js:705

TypeError: Cannot read property 'substr' of null
    at C:\Users\dhruvdutt\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\settings-view\lib\package-card.js:705:80
    at C:\Users\dhruvdutt\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\settings-view\lib\package-manager.js:376:51
    at C:\Users\dhruvdutt\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\settings-view\lib\package-manager.js:403:20
    at exit (C:\Users\dhruvdutt\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\dhruvdutt\AppData\Local\atom\app-1.9.6\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\dhruvdutt\AppData\Local\atom\app-1.9.6\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

### Commands

```
     -5:04.6.0 selector-to-tag:solve-selector (atom-text-editor.editor.is-focused)
     -5:04.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -5:04.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -5:03.0 editor:indent (atom-text-editor.editor.is-focused)
     -4:48.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -4:45.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:42.5.0 tree-view:toggle (atom-text-editor.editor)
     -4:01.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-atom-dark-syntax.theme-one-dark-ui)
     -3:50.3.0 core:undo (atom-text-editor.editor.is-focused)
     -1:57.5.0 pane:show-next-recently-used-item (atom-text-editor.editor.is-focused)
     -1:57.4.0 pane:move-active-item-to-top-of-stack (div.panels-item)
     -1:52.7.0 pane:show-next-recently-used-item (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-atom-dark-syntax.theme-one-dark-ui)
     -1:52.6.0 pane:move-active-item-to-top-of-stack (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-atom-dark-syntax.theme-one-dark-ui)
     -0:37.6.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-atom-dark-syntax.theme-one-dark-ui)
     -0:36.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "automaticallyUpdate": false,
    "disabledPackages": [
      "jscs-fixer",
      "linter-jscs",
      "linter-jshint",
      "linter-less",
      "docblockr",
      "angularjs",
      "language-go",
      "language-java",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "language-yaml",
      "language-c",
      "language-clojure",
      "language-csharp",
      "minimap",
      "autocomplete-java",
      "react"
    ],
    "packagesWithKeymapsDisabled": [],
    "projectHome": "F:\\Projects",
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.5 (inactive)
atom-jade, v0.3.0 (active)
atom-ternjs, v0.14.2 (active)
autoclose-html, v0.23.0 (active)
clipboard-history, v0.6.6 (inactive)
css-spy, v0.5.1 (active)
docblockr, v0.7.4 (inactive)
es6-javascript, v1.0.0 (inactive)
file-icons, v1.7.18 (active)
git-control, v0.8.2 (inactive)
git-plus, v5.16.2 (inactive)
highlight-selected, v0.11.2 (active)
indent-guide-improved, v1.4.9 (active)
jscs-fixer, v1.1.1 (inactive)
language-babel, v2.32.2 (active)
less-than-slash, v0.16.0 (active)
linter, v1.11.15 (active)
linter-eslint, v7.2.4 (active)
linter-jscs, vundefined (inactive)
linter-jshint, v2.1.0 (inactive)
linter-less, v2.6.0 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.24.7 (inactive)
predawn-syntax, v1.0.2 (inactive)
predawn-ui, v1.0.2 (inactive)
react, v0.15.0 (inactive)
selector-to-tag, v0.4.1 (active)
tool-bar, v1.0.0 (inactive)
tool-bar-atom, v1.6.3 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.3 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-08-08 13:28
This is a duplicate of #766 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-08 13:28 UTC
