### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'

### ISSUE THREAD

**Issue by tjmehta** [atom/settings-view#444] opened 2015-03-27 06:40 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.174.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'

```
At fs.js:503

Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/task-lists/lib/index.js:4:11)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:140:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/lib/roaster.js:14:15)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/lib/roaster.js:70:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:140:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-readme-view.js:8:13)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-readme-view.js:71:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:140:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:28:23)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:398:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:140:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:26:23)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:369:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:140:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at createSettingsView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/main.js:12:22)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/main.js:39:18
  at wrappedOpener (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:568:16)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:485:22)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:418:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:45:32)
  at EventEmitter.emit (events.js:119:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "tabs",
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
circle-ci, v0.6.2
highlight-line, v0.10.1
highlight-selected, v0.9.1
jshint, v1.3.0
minimap, v4.3.1
monokai, v0.13.0
sublime-tabs, v0.5.2
travis-ci-status, v0.13.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-27 11:22
Duplicate of atom/release-notes#29.

**Closed by 50Wliu** 2015-03-27 11:22 UTC
