### ISSUE TITLE
Atom's smart tab feature is broken by design

### ISSUE THREAD

**Issue by dchambers** [atom/settings-view#364] opened 2015-01-31 21:46 UTC
There is a setting called 'Soft tabs', but this is only respected when there aren't yet ant tabs in a file.
As soon as there are tabs, Atom guesses whether to use soft tabs or hard tabs, and this guess is as often wrong as it is right.

Instead of guessing, my preference would be for Atom to:

  1. Use soft-tabs by default for files that exclusively use soft-tabs.
  1. Use hard tabs by default for files that exclusively use hard tabs.
  1. Ask me what tab-style I want to use for files that use both styles, and whether I'd like to convert the file to exclusively use that tab style.
  1. Remember my previous answers to the questions so that I would normally just press the 'accept' button to do the same I usually do in that situation.
  1. Display an indicator showing the current tab-style, and allow that indicator to be clicked to switch tab-styles, where the conversion question would be asked here too.

**Comment by lee-dohm** [comment] 2015-02-01 00:25
Duplicate of atom/atom#3719. You should subscribe to that issue for updates and give your feedback there. Thanks for submitting your ideas!

**Closed by lee-dohm** 2015-02-01 00:25 UTC

**Comment by dchambers** [comment] 2015-02-04 10:56
Thanks @lee-dohm, good to see that work is already underway.
