### ISSUE TITLE
`Library/Application\ Support/Atom/Cache` owned by root

### ISSUE THREAD

**Issue by peterbe** [atom/settings-view#845] opened 2016-09-16 16:48 UTC
I never start Atom with sudo. But for some reason `Library/Application\ Support/Atom/Cache` is now owned by root. 

```
▶ sudo ls -l Library/Application\ Support/Atom
total 104
drwx------@ 7 root     staff    238 Sep 16  2014 Cache
-rw-r--r--@ 1 root     staff   6144 Sep 16  2014 Cookies
-rw-r--r--@ 1 root     staff   1544 Sep 16  2014 Cookies-journal
drwx------@ 7 root     staff    238 Sep 16  2014 GPUCache
drwx------  3 peterbe  staff    102 Jan 20  2015 IndexedDB
drwx------@ 6 root     staff    204 Sep 16  2014 Local Storage
-rw-------  1 peterbe  staff  18368 May 17 09:07 Preferences
-rw-r--r--  1 peterbe  staff  15360 Sep 16 11:42 QuotaManager
-rw-r--r--  1 peterbe  staff   2576 Sep 16 11:42 QuotaManager-journal
drwx------  4 peterbe  staff    136 Apr 21 15:59 databases

```
I don't know if this is settings-view's problem. This is what I see:
![screen shot 2016-09-16 at 12 46 53 pm](https://cloud.githubusercontent.com/assets/26739/18593950/b6c50028-7c0b-11e6-956c-c5d41d3f3f8c.png)

With stack trace:
<img width="530" alt="screen shot 2016-09-16 at 12 47 28 pm" src="https://cloud.githubusercontent.com/assets/26739/18593966/c396a5f4-7c0b-11e6-912a-7b489583b936.png">

**Comment by peterbe** [comment] 2016-09-16 16:48
When I copy the whole thing, this is the output:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.242.2


### Stack Trace

Uncaught Error: EACCES: permission denied, unlink '/Users/peterbe/Library/Application Support/Atom/Cache/settings-view/Glavin001-1474044409955'

```
At fs.js:990

Error: EACCES: permission denied, unlink '/Users/peterbe/Library/Application Support/Atom/Cache/settings-view/Glavin001-1474044409955'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:990:18)
    at WriteStream.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/atom-io-client.js:221:18)
    at emitOne (events.js:95:20)
    at WriteStream.emit (events.js:182:7)
    at WriteStream.<anonymous> (fs.js:1933:12)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -0:03.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "pep8",
      "atom-flake8",
      "atom-jshint",
      "atom-color-highlight",
      "linter-js-standard",
      "react"
    ],
    "followSymlinks": true,
    "ignoredNames": [
      ".pyc"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.8.1 (active)
advanced-open-file, v0.16.4 (inactive)
atom-beautify, v0.29.11 (inactive)
atom-color-highlight, v3.0.9 (inactive)
atom-jshint, v2.0.0 (inactive)
atom-material-syntax, v0.4.6 (inactive)
autoclose-html, v0.23.0 (active)
autocomplete-html-entities, v0.1.0 (active)
color-picker, v2.2.2 (active)
double-tag, v0.4.0 (active)
editorconfig, v1.4.1 (active)
fizzy, v0.16.0 (inactive)
gist-it, v0.9.1 (inactive)
highlight-line, v0.11.1 (active)
language-babel, v2.39.0 (active)
language-brightscript, v0.6.1 (active)
language-ini, v1.16.0 (active)
language-nginx, v0.6.1 (active)
language-scala, v1.1.6 (active)
last-cursor-position, v0.9.0 (active)
linter, v1.11.16 (active)
linter-js-standard, v3.4.1 (inactive)
merge-conflicts, v1.4.4 (active)
monokai, v0.18.0 (inactive)
pigments, v0.34.0 (active)
react, v0.16.0 (inactive)
remember-file-positions, v0.2.2 (active)
rst-preview, v1.3.1 (active)
seti-ui, v1.3.2 (inactive)
simple-center-screen, v1.3.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (active)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-10-05 19:47
Closing as a duplicate of #850 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-05 19:47 UTC
Labels: uncaught-exception
