### ISSUE TITLE
Error while uninstalling package/theme

### ISSUE THREAD

**Issue by Gensoki** [atom/settings-view#769] opened 2016-04-20 01:00 UTC
Tried a whole bunch of packages/themes error keeps popping up in both Atom and Atom Beta
Failed to delete [package/theme name here]: Does not exist

Running Mac OS X Yosemite

**Comment by 50Wliu** [comment] 2016-04-20 01:06
This is a duplicate of atom/atom#11464 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-20 01:06 UTC
