### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/lancejordan/.atom/packages/autocomplete-plus/lib/provider.coffee'

### ISSUE THREAD

**Issue by lacostenycoder** [atom/settings-view#406] opened 2015-03-03 22:13 UTC
[Enter steps to reproduce below:]

1. Update package from Settings.

**Atom Version**: 0.182.0
**System**: Mac OS X 10.9.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.183.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/lancejordan/.atom/packages/autocomplete-plus/lib/provider.coffee'

```
At /Applications/Atom.app/Contents/Resources/app/src/package.js:241

Error: ENOENT, no such file or directory '/Users/lancejordan/.atom/packages/autocomplete-plus/lib/provider.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.exports._compileFile (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:206:14)
  at getSourceMap (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:314:22)
  at getSourceMapping (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:322:19)
  at formatSourcePosition (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:274:16)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:340:34
  at Function.Error.prepareStackTrace (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:343:7)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:241:79)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
  2x -2:45.8 core:move-down (atom-text-editor.editor.mini)
     -2:45.3 core:confirm (atom-text-editor.editor.mini)
     -2:37.3 core:backspace (atom-text-editor.editor)
     -2:28.3 command-palette:toggle (atom-text-editor.editor)
  7x -2:25.8 core:backspace (atom-text-editor.editor)
     -2:23.3 snippets:next-tab-stop (atom-text-editor.editor)
     -2:23.3 snippets:expand (atom-text-editor.editor)
     -2:23.3 editor:indent (atom-text-editor.editor)
  5x -2:20.5 core:backspace (atom-text-editor.editor)
     -2:13.5 command-palette:toggle (atom-text-editor.editor)
     -2:12.1 editor:consolidate-selections (atom-text-editor.editor.mini)
     -2:12.1 core:cancel (atom-text-editor.editor.mini)
     -1:40.0 snippets:show (atom-text-editor.editor)
     -1:26.0 editor:consolidate-selections (atom-text-editor.editor)
     -1:26.0 core:cancel (atom-text-editor.editor)
     -0:58.2 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check"
    ],
    "themes": [
      "atom-dark-ui",
      "SideWalkChalk"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
SideWalkChalk, v0.0.0
atom-erb, v0.1.0
autocomplete-snippets, v0.3.1
color-picker, v1.2.6
highlight-line, v0.9.2
html2haml, v0.3.0
language-haml, v0.14.0
slim-language, v2.0.0
web-browser, v1.3.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-03 22:43
Duplicate of #388, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-03 22:43 UTC
