### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by richerve** [atom/settings-view#782] opened 2016-05-08 19:46 UTC
[Enter steps to reproduce below:]

1. Trying to update packages in a regular homebrew installation of atom
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At /opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709

TypeError: Cannot read property 'substr' of null
    at /opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709:80
    at /opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:51
    at /opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:403:20
    at exit (/opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -0:27.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.seti-ui-no-icons.theme-solarized-dark-syntax.theme-one-dark-ui.scrollbars-visible-always)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
file-icons, v1.7.8
language-salt, v0.4.0
minimap, v4.23.2
pigments, v0.26.0
project-manager, v2.9.7
tree-view-git-branch, v0.1.2
tree-view-git-status, v0.2.3
vim-mode, v0.65.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-05-08 20:20
This is a duplicate of #766 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-08 20:20 UTC
