### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by cschultz702** [atom/settings-view#949] opened 2017-05-14 13:11 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.248.0

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At C:\Users\chris\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:240

TypeError: Cannot read property 'version' of undefined
    at /app.asar/node_modules/settings-view/lib/package-card.js:240:34
    at /app.asar/node_modules/settings-view/lib/package-manager.js:282:18
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -1:35.2.0 editor:toggle-line-comments (button.btn.option-selection.selected)
     -1:29.1.0 encoding-selector:show (button.btn.option-selection.selected)
     -0:41.3.0 settings-view:install-packages-and-themes (button.btn)
```

### Non-Core Packages

```

```

**Comment by JABirchall** [comment] 2017-05-15 08:22
Getting the same issue. 

[Enter steps to reproduce:]
1. Open atom
2. Open settings

**Atom:** Latest version (auto updated this morning)
**Electron:** unknown
**OS:** Mac OS X Yosemite 10.10.5
**Thrown From:** settings-view package 0.248.0

**Comment by rsese** [comment] 2017-05-15 22:48
Looks like a dupe of https://github.com/atom/settings-view/issues/943 - @JABirchall can you share your info in that issue and let us know if you can reproduce in safe mode (`atom --safe`)?  @cschultz702 - if you have steps to reproduce, that would be great to hear too :v:

**Closed by rsese** 2017-05-15 22:48 UTC
