### ISSUE TITLE
Text fields only visible when focused

### ISSUE THREAD

**Issue by jovilog** [atom/settings-view#1050] opened 2018-03-13 22:25 UTC
### Prerequisites

* [x] Reproduced the problem in Safe Mode
* [x] Reset to Factory Defaults
* [x] Check for Linked Packages
* [x] Check for Incompatible Packages
* [x] Clearing Saved State

### Description

Whenever I open settings view, every text field is invisible and only becomes visible when focused.
Select fields, checkboxes, etc. are ok.
Disabling `opacity: .75` in Dev Tools makes the text fields appear (see screenshots). 

### Steps to Reproduce

1. `Cmd+,`

**Expected behavior:** See all the text fields.

![visible](https://user-images.githubusercontent.com/1716272/37373089-60f32092-2715-11e8-9bc2-b68740156388.png)

**Actual behavior:** The text fields occupy space but are invisible

![invisible](https://user-images.githubusercontent.com/1716272/37373094-65ced0fc-2715-11e8-809d-0f557003f684.png)

**Reproduces how often:** 100%

### Versions

* Atom 1.25.0 (but the problem existed in previous versions as well)
* Electron 1.7.11
* Chrome 58.0.3029.110
* Node 7.9.0
* Mac OS X 10.11.6

### Additional Information

My windows setup doesn't have this error.

**Comment by rsese** [comment] 2018-03-15 06:32
Thanks for the report!

> Atom 1.24.1 (but the problem existed in previous versions as well)

Interesting...I can't reproduce on macOS 10.12.6 with 1.24.1 but I don't remember seeing this in previous versions either (I installed 1.23.0 to double check at least one old version but the text fields looked ok there).

Just to clarify, do the text fields look exactly the same when you started Atom in safe mode as when you're not in safe mode?  

Also, if you temporarily reset to factory defaults, does that make any difference?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

**Comment by jovilog** [comment] 2018-03-16 00:25
To be clear, the problem wasn't always there. I remember seeing those fields when I started out with Atom. Eventually, the fields disappeared, but I hoped it was a glitch with some theme or some other bug that'll get fixed soon. So, I didn't pay much attention when it first happened, and that's why I can't be more specific about the version update or other circumstances that caused the issue. Later, I searched a few times for possible causes or even solutions, and I couldn't believe no one else seems to be having the problem.

>  Just to clarify, do the text fields look exactly the same when you started Atom in safe mode as when you're not in safe mode?

Well, the default theme colors are a bit different, but the fields are just as much invisible in safe mode.

I updated my original post's prerequisites. The problem persists with factory defaults. After switching back to my setup, it showed one incompatible package (Flex Tool Bar) that could be rebuilt successfully. Everythin works fine, but the problem persists. Also, I have zero linked packages.

Here's another screenshot of when I hover over a field:
![hover](https://user-images.githubusercontent.com/1716272/37497476-c275bfec-28b8-11e8-9039-d26fa4212978.png)

**Comment by jovilog** [comment] 2018-03-16 01:12
The problem just got worse for a moment: after temporarily resetting to factory defaults (and back), all the fields, when focused, appeared empty. Dev tools showed the respective values were still there, but were not visible.

I ran `$ atom --clear-window-state` and at least the values are visible again, when a field is focused. The original problem persists. I once again updated the prerequisites section.

**Comment by jovilog** [comment] 2018-03-20 23:08
Anyone? What else could I try?
The problem described in my last comment is back again.

1. All text fields in settings are invisible, except when focused. 
2. Then, they all seem empty (no text visible), but they are not.

The latter even applies to the fields of the search and replace panel.

**Comment by paysonwallach** [comment] 2018-03-21 02:04
I'm experiencing the same issue. Clearing the window state resolved the issue until I clicked out of the text field, and every text field went blank, even when focused.

**Comment by rsese** [comment] 2018-03-21 03:12
Hmmm, not sure what else the issue could be since we can't repro and there haven't been other reports of this that I could find:

* is this on an external monitor?
* do you have the same issue in other Electron applications (e.g. VS Code)?
* are the text fields visible in a light theme like `One Light`?
* are there any errors in [devtools console](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools)?
* do you have any macOS settings or external applications enabled that could possibly be related?

**Comment by rsese** [comment] 2018-03-21 17:39
Oh the issue didn't live update for me, missed your comment @paysonwallach - do you remember when you saw this issue appear for you (assuming you're on 1.25 or 1.26 beta now)?  Also what operating system are you running?

**Comment by jovilog** [comment] 2018-03-21 23:29
I've tried almost everything that's listed on the debugging page.

Also...

* no external monitor,
* no problems with VS Code and other Electron apps,
* I've tried many themes, light and dark, core and installed, to no avail,
* no errors in the console.

I believe you're last question points in the right direction, but I have no idea what settings or apps could possibly be related, I'm afraid.

The two problems seem different, but related, since the values in the search/replace fields of the editor are invisible, too, while these fields themselves are not invisible like the ones in the Settings.

Maybe it's got something to do with the rendering of Chrome, since I am able to at least make everything visible through Dev Tools when:

* setting `opacity: 1;` for `.settings-view .section atom-text-editor[mini]`
&rarr; *solves the invisible fields*
* and setting `contain: size layout style !important;`, i.e. **omitting `paint`**, for the child `.settings-view .section atom-text-editor[mini] > div`
&rarr; *solves the invisible values*.

This is also how I could possibly get around this for now: put these styles in the `styles.less` file in the `.atom` folder.
But, man, I'd really like to understand what causes these issues.

**Comment by jovilog** [comment] 2018-03-24 11:15
Ok, so I figured out this comes with the 1.19.0 version of Atom, 1.18.0 was ok.

Also, I found something interesting, I have issues with the minimap in VS Code and found [this issue](https://github.com/Microsoft/vscode/issues/44287#issuecomment-370054663).

Now the point is, I too have an Early 2009 model iMac with a similar video card and think the problems might be related.

Maybe somebody could verify? Or any new ideas with this new info?

**Comment by paysonwallach** [comment] 2018-03-24 22:16
Sorry @rsese, I'm running 1.25 on macOS 10.13.3.

**Comment by rsese** [comment] 2018-03-27 00:17
I see the referenced issue mentions NVIDIA GeForce GT 120, which video card in particular do you both have?

If you start Atom like this:

```
atom --disable-gpu
```

Does that make any difference?

**Comment by jovilog** [comment] 2018-03-27 17:21
I have a NVIDIA GeForce GT 130 512 MB.

```
atom --disable-gpu
```
This. All problems gone.

Now, what does that mean?
Could this possibly be fixed?
Or will I have to live with it, with my dated hardware?
Is there a way to start Atom like this from the dock?
What are the disadvantages of starting Atom like this?

**Comment by Arcanemagus** [comment] 2018-03-27 17:34
> Now, what does that mean? What are the disadvantages of starting Atom like this?

Chromium (and thus Atom) normally uses the GPU to accelerate drawing parts of the interface. That option tells it to not even _attempt_ to do this, and just use the CPU for rendering everything. This means that the parts that would normally be accelerated using the GPU will instead take slightly longer and render on the CPU. This likely won't make a noticeable difference, but does slightly increase the battery usage as the CPU has to work harder to do the things the GPU is optimized for.

> Could this possibly be fixed? Or will I have to live with it, with my dated hardware?

Some issues like this can be fixed by the GPU driver being updated to fix the bug that is causing this, but with older hardware manufacturers often drop support entirely so it's rather unlikely unfortunately. Chromium maintains a blacklist of features that cards simply don't support (while claiming they do), or don't work properly. Normally this hides bugs like this, but it sounds like the list within the version used by Atom simply doesn't know about this issue. It's possible when Atom updates Electron at some future point you may be able to stop using that flag, but if the `chrome://gpu` page shown in that linked comment is any indication it doesn't seem that there are _any_ GPU accelerations that work on your hardware. You can visit that page in Chrome yourself to see Chrome's current status on your machine.

> Is there a way to start Atom like this from the dock?

https://superuser.com/questions/271678/how-do-i-pass-command-line-arguments-to-dock-items

**Comment by jovilog** [comment] 2018-03-28 16:15
Thanks for the explanations. I should have worded that better. I know what hardware acceleration does, I was more after things like the battery thing (which is no problem, for me at least (iMac)).

> Chromium maintains a blacklist of features that cards simply don't support (while claiming they do), or don't work properly. Normally this hides bugs like this, but it sounds like the list within the version used by Atom simply doesn't know about this issue. It's possible when Atom updates Electron at some future point you may be able to stop using that flag, but if the chrome://gpu page shown in that linked comment is any indication it doesn't seem that there are any GPU accelerations that work on your hardware.

Very interesting. But that linked comment doesn't show my hardware. Hardware acceleration works with most features on my machine, but mine shows the same detected problems with NVidia GPUs.

> Is there a way to start Atom like this from the dock?

Doh. I really could have found that out by myself, couldn't I?

So, thanks everyone. Maybe someone should label this a bit more appropriately? And the close it.

**Comment by Arcanemagus** [comment] 2018-03-28 17:17
Thanks for reporting back 😉.

Since there isn't anything that Atom can do to fix this, and there is a viable workaround posted [here](https://github.com/atom/settings-view/issues/1050#issuecomment-376353836), I'll go ahead and close this issue.

**Closed as completed by Arcanemagus** 2018-03-28 17:17 UTC
Labels: mac

**Comment by illmatic6514** [comment] 2018-11-27 11:30
> I see the referenced issue mentions NVIDIA GeForce GT 120, which video card in particular do you both have?
> 
> If you start Atom like this:
> 
> ```
> atom --disable-gpu
> ```
> Does that make any difference?

I've seen this in other discussions too and I tried it and it fixed most of my problems.. 
I can see the searched text but not the text I want to replace with.
And when I search in directory all texts input fields disappear.
