### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by tonyeung** [atom/settings-view#775] opened 2016-04-22 14:59 UTC
[Enter steps to reproduce below:]

1. press the update button (going from 8.8.0 to 8.8.1)
2. see error

**Atom Version**: 1.7.2
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At C:\Users\rduong\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:709

TypeError: Cannot read property 'substr' of null
    at C:\Users\rduong\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:709:80
    at C:\Users\rduong\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:376:51
    at C:\Users\rduong\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:403:20
    at exit (C:\Users\rduong\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\rduong\AppData\Local\atom\app-1.7.2\resources\app.asar\src\buffered-process.js:215:47)
    at C:\Users\rduong\AppData\Local\atom\app-1.7.2\resources\app.asar\src\buffered-process.js:229:18
    at Socket.<anonymous> (C:\Users\rduong\AppData\Local\atom\app-1.7.2\resources\app.asar\src\buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -8:54.8.0 core:paste (atom-text-editor.editor.is-focused)
     -8:54.1.0 core:save (atom-text-editor.editor.is-focused)
     -3:38.4.0 core:paste (atom-text-editor.editor.is-focused)
  2x -3:37.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:28.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "drag-drop-text"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-typescript, vundefined
autocomplete-angular-material, v0.4.0
linter, v1.11.4
linter-eslint, vundefined
simple-drag-drop-text, v0.3.0

# Dev
No dev packages
```

**Comment by ArthurZ** [comment] 2016-04-24 03:33
I have it too, in Ubuntu 14

**Comment by sbmueller** [comment] 2016-04-24 12:48
Same with OS X 10.11

**Comment by migueltarga** [comment] 2016-04-25 13:42
Same with OS X 10.10.5

**Comment by tonyeung** [comment] 2016-04-25 14:33
If it bothers anyone else as much as it did with me, I just deleted the package from my .atom folder. This is after a few attempts at unistalling it after window refreshes, app restarts and pc restarts. Then installing the new version works. I hope this problem gets fixed so that the next time there's a plugin update I don't have to manually delete and reinstall. This might be a squirrel issue, but I don't have the bandwidth to investigate.

**Comment by hacdias** [comment] 2016-04-25 18:30
Same with Windows 10 Pro Insider Preview Build 14328.

**Comment by 50Wliu** [comment] 2016-04-25 20:25
This is a duplicate of #766 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-25 20:25 UTC

**Comment by RefactorMan** [comment] 2016-05-07 12:01
same on windows 10 64bit
