### ISSUE TITLE
Only a few of packages show up under Community Packages

### ISSUE THREAD

**Issue by danielbayley** [atom/settings-view#598] opened 2015-07-21 14:22 UTC
I have 53 community packages installed, but only about 10 of them show up in settings view, and searching for ones that don't doesn't find them either.

OS X Yosemite 10.10.4
Atom 1.0.2

**Comment by mnquintana** [comment] 2015-07-21 14:37
I think this is a duplicate of https://github.com/atom/settings-view/issues/591 – let's keep the discussion there.

**Closed by mnquintana** 2015-07-21 14:37 UTC
