### ISSUE TITLE
Uncaught TypeError: Cannot read property 'context-menu' of undefined

### ISSUE THREAD

**Issue by windgo** [atom/settings-view#375] opened 2015-02-07 05:47 UTC
Uncaught TypeError: Cannot read property 'context-menu' of undefined

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.161.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/src/package.js:297

TypeError: Cannot read property 'context-menu' of undefined
  at Package.module.exports.Package.activateResources (/Applications/Atom.app/Contents/Resources/app/src/package.js:297:16)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:209:19
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:159:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:207:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:404:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:234:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:37:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:59:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:66:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:146:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:461:12)

```

/cc @atom/core

**Comment by windgo** [comment] 2015-02-07 05:48
when "Markdown Writer" package intalling.

**Comment by 50Wliu** [comment] 2015-02-07 20:13
To clarify: Is this when you were *installing* the package, or was it already installed?
Also, could you please upgrade to the latest Atom version (currently 0.177.0)?  Thanks.

**Comment by kevinsawicki** [comment] 2015-02-09 18:24
This is a duplicate of https://github.com/atom/settings-view/issues/310

If you upgrade to the latest Atom, 0.177, this issue should go away, you are about 20 releases behind currently.

**Closed by kevinsawicki** 2015-02-09 18:24 UTC
