### ISSUE TITLE
Uncaught Error: spawn EPERM

### ISSUE THREAD

**Issue by imnileshsalvi** [atom/settings-view#948] opened 2017-05-11 13:55 UTC
[Enter steps to reproduce:]

1. ...Open Atom
2. ...Click Welcome Guide tab
3. ...Click Customize the Styling (in Get to know Atom!)
4. ...Select Settings from File menu
5. ...In Setting menu, click System

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.248.0

### Stack Trace

Uncaught Error: spawn EPERM

```
At internal/child_process.js:313

Error: spawn EPERM
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at Registry.get (/app.asar/node_modules/winreg/lib/registry.js:616:14)
    at ShellOption.isRegistered (/app.asar/src/main-process/win-shell.js:40:91)
    at /app.asar/node_modules/settings-view/lib/system-windows-panel.js:49:32)
    at /app.asar/node_modules/settings-view/lib/settings-view.js:208:20
    at SettingsView.getOrCreatePanel (/app.asar/node_modules/settings-view/lib/settings-view.js:349:19)
    at SettingsView.showPanel (/app.asar/node_modules/settings-view/lib/settings-view.js:407:24)
    at HTMLDivElement.clickHandler (/app.asar/node_modules/settings-view/lib/settings-view.js:174:18)
```

### Commands

```
```

### Non-Core Packages

```
platformio-ide-terminal 2.5.0 
```

**Comment by rsese** [comment] 2017-05-11 23:22
Thanks for the report @imnileshsalvi!  Can you confirm if the error is reproducible?

I don't have access to my Windows machine right now so can't try to reproduce with my Mac since there's no `Settings > System` menu on Mac.

**Comment by imnileshsalvi** [comment] 2017-05-12 20:11
Hi Robert,

Yes. It can be reproduced on the work computer. I am going to try it on my
personal development machine today and will post it on the thread.

I am getting to love Atom. Keep up the good work with this awesome tool.

Thanks and have a nice weekend!

Nilesh

**Comment by 50Wliu** [comment] 2017-05-12 21:42
It sounds like you don't have permission to edit the registry.  What happens when you attempt to run the `regedit` command?

**Comment by 50Wliu** [comment] 2017-08-05 00:53
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/settings-view/issues/948#issuecomment-301192797. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by 50Wliu** 2017-08-05 00:53 UTC
Labels: needs-reproduction, uncaught-exception

**Comment by sobolevnrm** [comment] 2017-10-01 15:44
I have this problem and cannot run the regedit command as a normal user (need admin privileges).

**Comment by 50Wliu** [comment] 2017-10-02 08:11
Unfortunately, the System tab currently needs access to the registry in order to be able to change file associations.  We can definitely add an informative notification for this case rather than throwing an error though.
