### ISSUE TITLE
Uncaught CssSyntaxError: <css input>:3:37: Unclosed quote

### ISSUE THREAD

**Issue by BLiu1** [atom/settings-view#905] opened 2017-01-23 10:34 UTC
Steps to Trigger the Bug

1. Open settings/preferences.
2. Click on Editor tab.
3. Type a double-quote character in the "Font Family" input.
4. Behold the early parse error.

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.244.0

### Stack Trace

Uncaught CssSyntaxError: <css input>:3:37: Unclosed quote

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/parse.js:35

CssSyntaxError: <css input>:3:37: Unclosed quote

  1 | atom-text-editor {
  2 |   font-size: 12px;
> 3 |   font-family: ", "Apple Color Emoji";
    |                                     ^
  4 |   line-height: 1.5;
  5 | }

    at Input.error (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/input.js:113:22)
    at unclosed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/tokenize.js:57:21)
    at tokenize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/tokenize.js:167:29)
    at Parser.tokenize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/parser.js:49:46)
    at Function.parse (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/postcss/lib/parse.js:25:16)
    at transformDeprecatedShadowDOMSelectors (/Applications/Atom.app/Contents/Resources/app.asar/src/style-manager.js:253:37)
    at StyleManager.addStyleSheet (/Applications/Atom.app/Contents/Resources/app.asar/src/style-manager.js:148:23)
    at atom-workspace.module.exports.WorkspaceElement.updateGlobalTextEditorStyleSheet (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:73:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:200:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:262:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1417:25
```

### Commands

```
  2x -9:00.2.0 core:backspace (input.hidden-input)
     -7:20.4.0 core:cut (input.hidden-input)
     -7:19.5.0 core:undo (input.hidden-input)
     -7:17.1.0 core:cut (input.hidden-input)
     -7:14.8.0 core:paste (input.hidden-input)
     -3:48.7.0 core:backspace (input.hidden-input)
     -3:38.2.0 core:select-all (input.hidden-input)
 13x -2:43 core:backspace (input.hidden-input)
     -1:02.4.0 pane:show-previous-item (input.hidden-input)
     -1:01.4.0 pane:show-next-item (input.hidden-input)
     -0:51.3.0 pane:show-previous-item (input.hidden-input)
     -0:50 pane:show-next-item (input.hidden-input)
     -0:48.2.0 pane:show-previous-item (div.panels-item)
     -0:47.4.0 pane:show-next-item (input.hidden-input)
 17x -0:45.8.0 core:move-left (input.hidden-input)
  2x -0:26.3.0 core:backspace (input.hidden-input)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.2.4 (active)
emmet, v2.4.3 (active)
gpp-compiler, v3.0.7 (active)
linter, v1.11.21 (active)
minimap, v4.26.7 (active)
open-recent, v5.0.0 (active)
prime-file-icons, v0.3.0 (active)
rectangle-selection, v0.2.0 (active)
synced-sidebar, v0.4.3 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (active)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment] 2017-01-23 10:39
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13663. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-01-23 10:39 UTC
