### ISSUE TITLE
'find' doesn't find anything in the settings

### ISSUE THREAD

**Issue by toejough** [atom/settings-view#253] opened 2014-09-29 14:02 UTC
Atom version: 0.132.0
OS: OSX (10.9.5)

![screen shot 2014-09-29 at 7 51 43 am](https://cloud.githubusercontent.com/assets/5317312/4442652/2e3a2be4-47e1-11e4-9faa-42b5a8af3f0a.png)

Apologies if this is the wrong place to submit the bug - I just got started with Atom, and I'm not sure if the correct sub-project is vim-mode, settings, or find-and-replace.

One of the first things I did when opening Atom was check if there's a vim-mode.  Found it, installed it, browsed the keybindings, tried to search the keybindings.

When viewing the vim-mode keybindings, the 'find' functionality that pops up when you hit command-f on a mac (10.9.5) does not search the keybindings you're looking at.

I'm submitting here because I tried this on several other 'settings' pages, with the same effect.  'find' doesn't find anything in the settings.

**Comment by mcandre** [comment] 2015-03-08 16:47
+1

**Comment by mnquintana** [comment] 2015-04-25 03:56
Closing as duplicate of #394 - please subscribe there for updates.

**Closed by mnquintana** 2015-04-25 03:56 UTC
Labels: enhancement
