### ISSUE TITLE
packages list breaks (showing not packages) when searching while updating packages

### ISSUE THREAD

**Issue by despairblue** [atom/settings-view#565] opened 2015-07-02 13:51 UTC
I updated all packages and then went on to search for a specific package to change some options, then this happened:
![screenshot from 2015-07-02 15-50-37](https://cloud.githubusercontent.com/assets/927609/8478493/2777915a-20d2-11e5-84ce-352a37041105.png)

**Comment by eboracus** [comment] 2015-07-05 01:44
I've also experienced this issue, don't know at all right now what's causing it though, as it seems for me to be more general. But always after trying to filter the list through the search box - then when deleting the search term.... this.

I've been hit by this effect multiple times, twice after updating packages (almost identical process you describe there), but it doesn't seem limited to this setting either as I've also seen it a number of times when having carried out no updates at all. In those cases I couldn't figure out a likely cause/pattern and haven't been able to reproduce via repeating any suspected causes. :/

Of note is that I am now looking at exactly this screen, having come back to the package list page and tried searching after carrying out the reproduction of this separate issue: atom/settings-view#507. Though this involved installing/unistalling so maybe a connection there(?)

**Comment by eboracus** [comment] 2015-07-05 02:28
Ok now investigated further and this definitely seems caused by any updating _and_ installing of packages in general. Here is an illustration of using the search field as normal and then installing a new package and trying to filter the installed package list again:

![filter_list_breaks_install_take2](https://cloud.githubusercontent.com/assets/11758299/8510051/aeba7526-22c4-11e5-94f9-cc7bc19e66e1.gif)

Now it makes more sense why no pattern seemed clear before, when not updating. As I also tried installing a package and then going off to edit another open file, saving, opening menus, then coming back and the same behaviour occurs. So could've filled that intervening time with many random things :p

**Comment by mnquintana** [comment] 2015-07-07 01:26
Hmmm, I can't seem to reproduce this with the latest changes on master. Can anyone in @atom/feedback reproduce this?

**Comment by benogle** [comment] 2015-07-07 01:30
This should be fixed via https://github.com/atom/settings-view/commit/06b810e7d5ab5a7f66adbad4f4e3e962d103dfcb. There was an issue when the `ListView` was updated; it would disconnect the model -> view map and the filtering would no longer work.

**Closed by benogle** 2015-07-07 01:30 UTC
Labels: needs-reproduction
