### ISSUE TITLE
atom error

### ISSUE THREAD

**Issue by pssgo** [atom/settings-view#1001] opened 2017-09-23 13:38 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.250.0

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:248

TypeError: Cannot read property 'version' of undefined
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:248:40
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:333:24
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -1:40.6.0 core:confirm (input.hidden-input)
  5x -1:37.4.0 core:close (input.hidden-input)
     -1:25.5.0 application:add-project-folder (div.tool-panel.tree-view)
     -1:01.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:57 tree-view:add-file (div.header.list-item.project-root-header)
     -0:54 core:backspace (input.hidden-input)
     -0:53.4.0 core:confirm (input.hidden-input)
     -0:39.8.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  4x -0:38.6.0 core:backspace (input.hidden-input)
  7x -0:35.8.0 core:move-up (input.hidden-input)
     -0:33.3.0 core:confirm (input.hidden-input)
     -0:31 core:cut (input.hidden-input)
  5x -0:27.1.0 core:backspace (input.hidden-input)
     -0:20.2.0 core:move-right (input.hidden-input)
     -0:19.4.0 editor:newline (input.hidden-input)
  4x -0:16.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.13 
atom-ide-ui 0.3.3 
autocomplete-paths 2.10.1 
busy-signal 1.4.3 
file-icons 2.1.11 
git-control 0.9.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
intentions 1.1.5 
language-babel 2.73.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.8 
open-in-browsers 0.0.30 
simplified-chinese-menu 5.3.4 
```

macOs

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.1
atom 1.19.2

**Comment by rsese** [comment] 2017-09-25 19:38
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/settings-view/issues/943. You may want to subscribe there for updates and if you have any steps to reproduce you can share, please comment in the issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-09-25 19:38 UTC
