### ISSUE TITLE
ThemePackage.activateConfig is deprecated.

### ISSUE THREAD

**Issue by dieselrich89** [atom/settings-view#477] opened 2015-04-23 05:30 UTC
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
ThemePackage.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:247:11)
PackageDetailView.activate (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:155:26)
PackageDetailView.updateInstalledState (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:193:12)
<unknown> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:222:24)
```

**Comment by thomasjo** [comment] 2015-04-23 05:57
This is caused by one of your installed packages, and judging from the stack trace, said package is a theme. Re-open this issue on the offending package's repo.

**Comment by thomasjo** [comment] 2015-04-23 06:04
Sorry, I misread that stack trace completely. This is indeed an issue that should be fixed here.

**Comment by thomasjo** [comment] 2015-04-23 06:09
The deprecation message is being triggered at https://github.com/atom/atom/blob/edbcf4023ee4420e0e9fd5407b97dab0b4902860/src/package.coffee#L163-L167, so this is indeed a package issue.

---
*Note to self: don't triage issues this early in the morning*

**Closed by thomasjo** 2015-04-23 06:09 UTC
