### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by wingprc** [atom/settings-view#1055] opened 2018-03-30 11:20 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.254.1

### Stack Trace

Uncaught TypeError: Cannot read property 'filter' of undefined

```
At C:\Users\hp\AppData\Local\atom\app-1.25.0\resources\app\node_modules\settings-view\lib\atom-io-client.js:305

TypeError: Cannot read property 'filter' of undefined
    at Request._callback (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/settings-view/lib/atom-io-client.js:305:38)
    at Request.self.callback (/app.asar/node_modules/settings-view/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
     -2:05.8.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -2:00.9.0 core:confirm (input.hidden-input)
     -1:58.2.0 core:backspace (input.hidden-input)
  3x -1:57.6.0 core:move-left (input.hidden-input)
  6x -1:54.9.0 core:backspace (input.hidden-input)
  2x -1:47.9.0 core:move-right (input.hidden-input)
  2x -1:45.8.0 core:backspace (input.hidden-input)
     -1:45.4.0 core:move-right (input.hidden-input)
     -1:44.8.0 editor:newline (input.hidden-input)
     -1:43.1.0 core:backspace (input.hidden-input)
     -1:39.7.0 autocomplete-plus:confirm (input.hidden-input)
     -1:39.7.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:36.7.0 core:backspace (input.hidden-input)
     -1:06.7.0 application:open-your-stylesheet (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:54.4.0 core:backspace (input.hidden-input)
     -0:49 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
activate-power-mode-delete 0.6.1 
atom-material-syntax 1.0.8 
simplified-chinese-menu 5.3.5 
```

**Comment by rsese** [comment] 2018-03-30 21:23
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by ano95** [comment] 2018-04-24 13:33
Same as #1058.

**Comment by rsese** [comment] 2018-04-24 23:37
Thanks @ano95 :+1:  #1058 also looks like a duplicate of #1052.

Feel free to subscribe to #1052 for updates if you'd like @wingprc.

**Closed by rsese** 2018-04-24 23:37 UTC
Labels: more-information-needed, uncaught-exception
