### ISSUE TITLE
Very slow and laggy load on the beta 

### ISSUE THREAD

**Issue by GeorgeWL** [atom/settings-view#942] opened 2017-04-21 17:39 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
Very Slow  to load Package List, hung once. Using a unusually high amount of memory
### Steps to Reproduce

1. Open Package List
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
Faster load
**Actual behavior:** [What actually happens]
slow load
**Reproduces how often:** [What percentage of the time does it reproduce?]
every time
### Versions
Version 1.7.0-Beta3
Windows 10 Latest Version
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2017-04-25 23:38
@GeorgeWL - is the behavior in safe mode exactly the same?  Also, how many packages do you have installed?  You can check with `apm list --installed`.

Lastly, can you share the output of these commands?

* `atom -v`
* `apm -v`

**Comment by rsese** [comment] 2017-04-25 23:39
Oh also, did you notice this behavior just after updating to  1.7.0-Beta3?

**Comment by GeorgeWL** [comment] 2017-04-26 08:27
@rsese I noticed it just after Beta update,  but it was an issue to a lesser extent before. 

I have 78 packages installed.

**Comment by rsese** [comment] 2017-04-26 22:57
Nice thanks @GeorgeWL, I'll try to reproduce with that package list.  Seems like something that would have an existing issue but didn't come across one.

A few more questions though:

* What operating are you using?  You don't mention in the Versions section of the issue template.
* You mentioned that you sync packages between 2 different computers - do you see the same lag on both machines?
* About how long is the lag?

**Comment by rsese** [comment] 2017-05-02 05:37
Finally had a chance to install sync-settings and try this out - I copied your package.json file and synced but didn't see much lag beyond ~1 second on `Settings > Packages`.  But I did notice a discrepancy when you mentioned:

> I have 78 community packages installed on top of the core.

After syncing, listing only installed packaged with `apm list --packages --installed` only shows 27 packages for me.  What do you see when running that command?

**Comment by GeorgeWL** [comment] 2017-05-02 10:21
I misworded there,  I meant as in total,  including the core.

**Comment by rsese** [comment] 2017-05-05 23:50
Thanks for clarifying - since I can't reproduce with the same set of packages I'll tag as needs reproduction for now.

Oh I also realized you didn't answer this question from before, can you confirm?

> You mentioned that you sync packages between 2 different computers - do you see the same lag on both machines?

**Comment by GeorgeWL** [comment] 2017-05-06 00:19
Ooh,  nope.  And since reinstall after a drive failure,  not this one either

**Comment by rsese** [comment] 2017-05-10 00:54
Ahhh great, thanks for letting us know - since you're not seeing the lag anymore I'll go ahead and close this but if I misunderstood please let me know.

**Closed by rsese** 2017-05-10 00:54 UTC
Labels: more-information-needed
