### ISSUE TITLE
Failed to load the autocomplete-plus package

### ISSUE THREAD

**Issue by TangibleLight** [atom/settings-view#457] opened 2015-04-04 00:55 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to load the autocomplete-plus package

```
At variable @syntax-color-variable is undefined

Error
  at new Parser (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\node_modules\less-cache\node_modules\less\lib\less\parser.js:333:27)
  at LessCache.module.exports.LessCache.parseLess (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\node_modules\less-cache\lib\less-cache.js:244:16)
  at LessCache.module.exports.LessCache.cssForFile (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\node_modules\less-cache\lib\less-cache.js:275:20)
  at LessCompileCache.module.exports.LessCompileCache.cssForFile (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\src\less-compile-cache.js:40:25)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\src\theme-manager.js:368:33)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\src\theme-manager.js:346:21)
  at C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:436:45
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:435:59)
  at C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:186:19
  at Package.module.exports.Package.measure (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.load (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:464:30)
  at C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:268:29
  at exit (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\David\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
     -1:22.1 settings-view:open (atom-text-editor.editor)
     -0:57.2 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "autocomplete"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.8.0

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-04-04 13:54
Duplicate of https://github.com/atom-community/autocomplete-plus/issues/352, I believe.

**Closed by izuzak** 2015-04-04 13:54 UTC
