### ISSUE TITLE
Packages are reloaded(?) when switching themes in Atom 0.135, Mac OS X

### ISSUE THREAD

**Issue by thomaslindstrom** [atom/settings-view#260] opened 2014-10-07 11:18 UTC
Similar to the issue seen a couple of days ago with 0.133 (https://github.com/atom/settings-view/issues/257), switching themes also cause packages to flicker or reload.

Video: http://cl.ly/3a2b1c0V473N

I am not sure if this is a fault in `color-picker` or `settings-view`, but I'm fairly certain this hasn't been present previously.

https://github.com/thomaslindstrom/color-picker/issues/40

**Comment by jlord** [comment] 2015-04-30 23:45
@thomaslindstrom Have you seen this happening more recently? I've got `color-picker` installed, too, but can't reproduce it.

**Comment by izuzak** [comment] 2015-09-09 12:48
I don't remember seeing other reports of this and I'm unable to reproduce this as well. Since this was way back in version 0.133 -- I'm going to close this. @thomaslindstrom -- let us know if you can still reproduce the problem. :v:

**Closed by izuzak** 2015-09-09 12:48 UTC
Labels: more-information-needed
