### ISSUE TITLE
Possibility to "guess tab length" from opened file

### ISSUE THREAD

**Issue by Ciantic** [atom/settings-view#446] opened 2015-03-28 15:15 UTC
This needs to be a new setting, perhaps checkbox "Guess tab length" it would try to guess the tab length of the opened file and use that in this file.

Right now I use tab length 4, but sometimes I have to edit files with tab length 2, I don't want to go back and forth tuning the settings.

**Comment by thomasjo** [comment] 2015-03-28 16:04
Duplicate of https://github.com/atom/atom/issues/3043.

**Closed by thomasjo** 2015-03-28 16:04 UTC
