### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/brianspector/Library/Application...

### ISSUE THREAD

**Issue by spector-in-london** [atom/settings-view#692] opened 2015-11-05 21:06 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.230.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/brianspector/Library/Application Support/com.github.atom.ShipIt/update.qerIyxj'

```
At ATOM_SHELL_ASAR.js:118

Error: ENOENT: no such file or directory, lstat '/Users/brianspector/Library/Application Support/com.github.atom.ShipIt/update.qerIyxj'
  at Error (native)
  at fs.lstatSync (fs.js:844:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
  at realpathSync (fs.js:1449:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
  at toRealPath (module.js:108:13)
  at tryFile (module.js:104:22)
  at tryExtensions (module.js:114:20)
  at tryPackage (module.js:92:31)
  at Function.Module._findPath (module.js:155:20)
  at Module._resolveFilename (module.js:332:25)
  at Function.Module._resolveFilename (/Users/brianspector/Library/Application Support/com.github.atom.ShipIt/update.qerIyxj/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/brianspector/Library/Application Support/com.github.atom.ShipIt/update.qerIyxj/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:14:11)
  at Object.<anonymous> (/Users/brianspector/Library/Application Support/com.github.atom.ShipIt/update.qerIyxj/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:369:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Users/brianspector/Library/Application Support/com.github.atom.ShipIt/update.qerIyxj/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (/Users/brianspector/.atom/packages/email/node_modules/mailtool/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at createSettingsView (/Users/brianspector/Library/Application Support/com.github.atom.ShipIt/update.qerIyxj/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:14:22)
  at /Users/brianspector/Library/Application Support/com.github.atom.ShipIt/update.qerIyxj/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:62:28
  at Workspace.module.exports.Workspace.openURIInPane (/Users/brianspector/Library/Application Support/com.github.atom.ShipIt/update.qerIyxj/Atom.app/Contents/Resources/app.asar/src/workspace.js:431:22)
  at Workspace.module.exports.Workspace.open (/Users/brianspector/Library/Application Support/com.github.atom.ShipIt/update.qerIyxj/Atom.app/Contents/Resources/app.asar/src/workspace.js:374:19)
  at EventEmitter.module.exports.WindowEventHandler.handleIPCMessage (/Users/brianspector/Library/Application Support/com.github.atom.ShipIt/update.qerIyxj/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:193:23)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)

```

### Commands

```
  3x -9:38.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2015-11-06 22:28
Was this when you launched the Settings View? Or when you attempted to do something specific within the Settings View?

**Comment by 50Wliu** [comment] 2015-11-13 21:28
Closing as a duplicate of atom/atom#7399, please subscribe there for updates.
However, please still answer @lee-dohm's question.

**Closed by 50Wliu** 2015-11-13 21:28 UTC
Labels: more-information-needed, uncaught-exception
