### ISSUE TITLE
Failed to load the todo-list package

### ISSUE THREAD

**Issue by iharsuvorau** [atom/settings-view#439] opened 2015-03-21 06:53 UTC
[Enter steps to reproduce below:]

1. Just started downloading
2. And bug message appreared

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to load the todo-list package

```
At variable @scrollbar-color is undefined

Error
  at new Parser (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
  at LessCache.module.exports.LessCache.parseLess (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:244:16)
  at LessCache.module.exports.LessCache.cssForFile (/Applications/Atom.app/Contents/Resources/app/node_modules/less-cache/lib/less-cache.js:275:20)
  at LessCompileCache.module.exports.LessCompileCache.cssForFile (/Applications/Atom.app/Contents/Resources/app/src/less-compile-cache.js:40:25)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:368:33)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:346:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:436:45
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (/Applications/Atom.app/Contents/Resources/app/src/package.js:435:59)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:186:19
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:30)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -1:32.1 core:paste (atom-text-editor#todo-show.findTheseRegexes.editor.mini)
     -1:26.0 core:save (atom-text-editor#todo-show.findTheseRegexes.editor.mini)
  2x -1:25.3 core:confirm (atom-text-editor#todo-show.findTheseRegexes.editor.mini)
     -1:21.3 atom-terminal:open (atom-text-editor.editor)
     -1:07.8 command-palette:toggle (atom-text-editor.editor)
  2x -1:04.3 core:backspace (atom-text-editor.editor.mini)
     -1:01.2 core:confirm (atom-text-editor.editor.mini)
     -1:01.2 todo-show:find-in-project (atom-text-editor.editor)
     -0:45.1 core:cut (atom-text-editor#todo-show.findTheseRegexes.editor.mini)
     -0:43.1 core:confirm (atom-text-editor#todo-show.findTheseRegexes.editor.mini)
     -0:38.0 command-palette:toggle (atom-text-editor.editor)
     -0:36.2 core:confirm (atom-text-editor.editor.mini)
     -0:36.2 todo-show:find-in-project (atom-text-editor.editor)
  4x -0:28.2 core:confirm (atom-text-editor.editor.mini)
     -0:18.3 core:backspace (atom-text-editor.editor.mini)
  2x -0:18.1 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-terminal, v0.7.0
color-picker, v1.4.4
emmet, v2.3.4
terminal-panel, v1.10.0
todo-show, v0.8.0

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-03-21 08:01
I believe this is a duplicate of https://github.com/atom/atom/issues/5996. See my comment there. I'm guessing you were using a theme which doesn't have that variable defined, but todo-list is depending on it.

**Closed by izuzak** 2015-03-21 08:01 UTC
