### ISSUE TITLE
There's no easy way to open Atom.io from package cards

### ISSUE THREAD

**Issue by izuzak** [atom/settings-view#328] opened 2015-01-09 12:17 UTC
_From @gfarrell on January 9, 2015 12:14_

When trying to find out more about a package, in the *Install* view of the *Settings* page in Atom `0.169.0`, clicking the title does nothing, but clicking the author opens the author page in a browser.

_Copied from original issue: atom/atom#4947_

**Comment by zephraph** [comment] 2015-01-21 16:07
+1

This is slightly annoying.

**Comment by thedaniel** [comment] 2015-01-27 20:02
This is not a bug as described. See my comments on #351. Updating the title of this issue to clarify.

**Comment by mnquintana** [comment] 2015-03-18 14:45
I think this was resolved in #373

**Closed** 2015-03-18 14:49 UTC
Labels: enhancement, next
