### ISSUE TITLE
[Suggestion] Directional key support

### ISSUE THREAD

**Issue by RomanRiesen** [atom/settings-view#944] opened 2017-04-25 08:37 UTC
Hello everyone, 

The title basically says it all.
I would really love to be abale to navigate the settings view with the arrow keys, since it is kind of annoying to reach over to the mouse if I want to quickly change something.

I would certainly do it myself, but I feel like I do not have enough experience with writing such GUI code and that I would produce an un-mergable mess.

The best solution I came up with would be to add arrow-key listeners and to select the elements based on position, which seems just not quite right to me. If someone were to point me in the right direction I would certainly take the time to create a package for this. 

But a proper integration by someone who knows his coffescript and GUI manipulation would be **alot** better.

Thanks for reading and please share you're thoughts!

P.S: I know there have been at least two other issues with the same topic, but the newest one I could find was 2 years old, so I thought it might be worth it to bring it up again.

**Comment by rsese** [comment] 2017-04-25 18:49
> P.S: I know there have been at least two other issues with the same topic, but the newest one I could find was 2 years old, so I thought it might be worth it to bring it up again.

I see where you're coming from but because of how the team treats issues, we specifically close duplicates so I'm going to go ahead and close this as a dupe of https://github.com/atom/settings-view/issues/131.   

> The best solution I came up with would be to add arrow-key listeners and to select the elements based on position, which seems just not quite right to me. If someone were to point me in the right direction I would certainly take the time to create a package for this.

A great place to ask for pointers is our message board or in the Atom Slack:

* https://discuss.atom.io/
* http://atom-slack.herokuapp.com/

The community is usually super helpful and the maintainers chime in when they can as well.

---

Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/settings-view/issues/131. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-04-25 18:49 UTC
