### ISSUE TITLE
quick search for options

### ISSUE THREAD

**Issue by ruv** [atom/settings-view#807] opened 2016-06-30 12:25 UTC
Why does text searching (find text, `Ctrl+F`) doesn't work on Settings page? "Find in Current Buffer" panel can be opened but nothing can be found.

Without a filter, the simple search would be a good alternative.

**Comment by Ben3eeE** [comment] 2016-06-30 12:40
https://github.com/atom/settings-view/issues/781?

**Comment by ruv** [comment] 2016-06-30 13:20
Yes, all other sections (Keybindings, Packages, Themes)  already have the filter tool, and it is worth to have such filter in Editor Settings section too.

Nevertheless, I suggest here an easier solution (at least it seems so) — just to support the search within plain text as in ordinary text editing pages.

**Comment by 50Wliu** [comment] 2016-07-23 23:35
This is a duplicate of #394 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-23 23:35 UTC
