### ISSUE TITLE
Failed to activate the project-palette-finder package

### ISSUE THREAD

**Issue by itadakimas** [atom/settings-view#415] opened 2015-03-10 09:14 UTC
[Enter steps to reproduce below:]

1. Click on the update all button in the updates panel

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to activate the project-palette-finder package

```
At undefined is not a function

TypeError: undefined is not a function
  at Package.module.exports.Package.activateServices (/Users/said/Applications/Atom.app/Contents/Resources/app/src/package.js:355:117)
  at Package.module.exports.Package.activateNow (/Users/said/Applications/Atom.app/Contents/Resources/app/src/package.js:243:16)
  at /Users/said/Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Users/said/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Users/said/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Users/said/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Users/said/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Users/said/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Users/said/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Users/said/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
     -0:54.1 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:54.1 docblockr:parse-enter (atom-text-editor.editor)
     -0:54.1 editor:newline (atom-text-editor.editor)
     -0:53.9 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:53.9 docblockr:parse-enter (atom-text-editor.editor)
     -0:53.9 editor:newline (atom-text-editor.editor)
     -0:53.8 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:53.8 docblockr:parse-enter (atom-text-editor.editor)
     -0:53.8 editor:newline (atom-text-editor.editor)
     -0:53.6 core:move-up (atom-text-editor.editor)
     -0:51.9 snippets:next-tab-stop (atom-text-editor.editor)
     -0:51.9 snippets:expand (atom-text-editor.editor)
     -0:51.9 docblockr:parse-tab (atom-text-editor.editor)
     -0:51.8 editor:indent (atom-text-editor.editor)
  2x -0:51.3 core:backspace (atom-text-editor.editor)
     -0:49.3 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "update-package-dependencies",
      "sublime-tabs",
      "language-mustache"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.1
color-picker, v1.4.4
docblockr, v0.6.3
editorconfig, v0.3.0
emmet, v2.3.4
html-entities, v0.3.1
project-manager, v1.15.5
project-palette-finder, v2.4.16
seti-syntax, v0.3.3
seti-ui, v0.6.3
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

**Comment by abe33** [comment] 2015-03-13 09:14
Likely a duplicate of #416, please subscribe there for updates.

**Closed by abe33** 2015-03-13 09:14 UTC
Labels: bug
