### ISSUE TITLE
Packages list doesn't filter by search when finished loading

### ISSUE THREAD

**Issue by tmunro** [atom/settings-view#667] opened 2015-09-26 17:37 UTC
1. Open Packages list
2. Type something into search field
3. Wait for packages to load
4. Observe that the packages aren't filtered
5. Type an additional character into the search field
6. Observe that packages are now filtered

Expectation:
Packages should filter by the search field contents automatically once they've finished loading.

**Comment by 50Wliu** [comment] 2015-09-26 18:03
Duplicate of #586, please subscribe there for updates.

**Closed by 50Wliu** 2015-09-26 18:03 UTC

**Comment by tmunro** [comment] 2015-09-26 18:28
Woops, my bad! My cursory search was clearly not thorough enough.
