### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by joelburget** [atom/settings-view#587] opened 2015-07-15 00:30 UTC
[Enter steps to reproduce below:]

Not exactly sure... The error was triggered as soon as I installed.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:56

TypeError: Cannot read property 'message' of undefined
  at ErrorView.module.exports.ErrorView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:56:21)
  at ErrorView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new ErrorView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:14:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/updates-panel.js:84:44
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:579:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:303:17
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:326:20
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -2:24.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.5
color-picker, v2.0.10
haskell-ghc-mod, v0.8.3
ide-haskell, v0.6.2
language-haskell, v1.1.6
minimap, v4.11.2
vim-mode, v0.55.0
vim-surround, v0.7.2

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-07-15 00:33
This is a duplicate of #577 – it's been fixed for the next release of Atom.

**Closed by mnquintana** 2015-07-15 00:33 UTC

**Comment by thecodejunkie** [comment] 2015-07-15 10:50
I can't seem to install packaged (on Windows). Is there any workaround for this? I'm on 1.0.2 at the moment

**Comment by 50Wliu** [comment] 2015-07-15 22:07
> I can't seem to install packaged (on Windows). Is there any workaround for this? I'm on 1.0.2 at the moment

You can use the `apm install <package>` command from the console (eg `apm install awesome-package`).

**Comment by thecodejunkie** [comment] 2015-07-15 22:08
@50Wliu that did not work (tried it earlier). However, I just uninstalled ATOM, manually removed the .atom folder and then reinstalled it again. This time it appears to work. So I might have had something really old on my disk that was conflicting =)

**Comment by ahmetabdi** [comment] 2015-07-16 12:40
When is the next release of atom? getting the same error.

**Comment by yvoloshin** [comment] 2015-07-16 18:03
I can't install any packages on Windows 8.1 either. After reading @thecodejunkie 's comment, I uninstalled Atom, deleted the .atom folder, and reinstalled Atom. That didn't help. I did it one more time with the same result. Can anyone suggest anything else I can try? I prefer Atom over Sublime, but not being able to use the Beautify package is a deal breaker :(

**Comment by mnquintana** [comment] 2015-07-16 18:07
@yvoloshin @thecodejunkie - @50Wliu's suggestion of using `apm install <package name>` should work. Is that not working for you? What output are you getting? You may have to reload Atom to see the package loaded when you install from the command line.

**Comment by yvoloshin** [comment] 2015-07-16 18:46
@mnquintana I tried typing `apm install <package name>` into the command palette, but when I pressed enter nothing would happen. When I use the package installer, the progress bar on the package still keeps rolling after an hour. If I close Atom and reload, the package I tried to install is not in the list of installed packages. Same result after I try to install from command line, as well as with different packages. Thanks a lot for any suggestions!

**Comment by 50Wliu** [comment] 2015-07-16 22:17
@yvoloshin Type the command into your OS's terminal, not the command palette.  For example, you would need to open `cmd.exe` on Windows and Terminal on Mac/Linux (usually <kbd>Ctrl+Alt+T</kbd> on Ubuntu-like systems).

**Comment by yvoloshin** [comment] 2015-07-17 00:32
Thanks a lot @50Wliu! That helped. It was a bit tricky to find where the atm command is. I had to go to \Users\USER\AppData\Local\atom\app-1.0.2\resources\app\apm and then run the apm install <package name> command.

**Comment by lidermanrony** [comment] 2015-07-18 05:18
Workaround for this bug:
when running apm install directly from command line you can see the real error message for the package not being able to install.
In my case the issue was that I tried to install a package that required Git to be installed (which it was not).

On windows run:
%LOCALAPPDATA%\atom\app-1.0.2\resources\app\apm\bin\apm.cmd install <package name>
