### ISSUE TITLE
Unable to re-install disabled packages

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#507] opened 2015-05-17 19:33 UTC
_From @HitomiTenshi on May 17, 2015 1:39_

How to reproduce:
- Go to settings -> Install
- Find a package you have installed at the moment
- Press disable and after that click on uninstall
- Restart atom
- Search for your disabled/uninstalled package

You will now see that it is uninstalled AND disabled, but it can't be enabled anymore.
To circumvent this bug you have to use apm through the console in order to re-install that package.

Atom version: ~~0.119.0~~ 0.199.0
OS: Windows 8.1 Pro 64 bit

_Copied from original issue: atom/atom#6826_

**Comment by mnquintana** [comment] 2015-05-17 19:33
_From @50Wliu on May 17, 2015 1:47_

Hi @HitomiTenshi, you're on an extremely old version of Atom.  If the problem still occurs under 0.199.0 (which you can install using the new Squirrel installer), please comment here and I'll reopen the issue.

**Comment by mnquintana** [comment] 2015-05-17 19:33
_From @HitomiTenshi on May 17, 2015 2:18_

oh sorry! it was a typo, I'm on 0.199.0
I'm really sorry!

**Comment by mnquintana** [comment] 2015-05-17 19:33
_From @HitomiTenshi on May 17, 2015 14:51_

I made a video that demonstrates this bug.
You can view it here: http://a.pomf.se/jbedor.webm

I found this issue by accident. I accidently clicked on disable instead of uninstall and after that didn't think anything bad would happen if I click on uninstall afterwards.

**Comment by HitomiTenshi** [comment] 2015-05-18 20:48
I don't see why more information is needed on this issue, I think I have described the problem as best as I could. I even added a video to make sure that nothing is misunderstood here.

**Comment by saschagehlich** [comment] 2015-05-19 14:08
@HitomiTenshi I think you're in the wrong issue / repo ;)

**Comment by mnquintana** [comment] 2015-05-19 14:10
@saschagehlich Nope this is the right place – I moved @HitomiTenshi's issue here. I actually can't seem to reproduce this on Atom 0.200.0-8556f39 and OS X 10.10.3 – can anyone else reproduce this?

**Comment by saschagehlich** [comment] 2015-05-19 14:13
Ah alright

**Comment by benogle** [comment] 2015-07-02 00:32
I cant reproduce this. Is this still an issue? The video 404s for me

**Comment by HitomiTenshi** [comment] 2015-07-02 05:01
pomf.se is going down.

http://a.uguu.se/grzvxc_2015-05-17_16-28-24.webm temporary link, I will change it later

the issue still exists, I just tested with atom 1.0
Just go to your package view, press disable and uninstall, then restart atom

you won't be able to install the uninstalled package from inside atom anymore.

**Comment by eboracus** [comment] 2015-07-05 01:08
Yes I've just tested and managed to reproduce this issue on both Windows and OS X. 

After disabling packages:
![disableuninstall1](https://cloud.githubusercontent.com/assets/11758299/8509869/6da5b5a2-22b8-11e5-93d5-4c5ed0581fa2.png)

After uninstalling Color-Picker - disappears from community packages list (as expected):
![disableunistall1](https://cloud.githubusercontent.com/assets/11758299/8509855/25a639bc-22b7-11e5-917c-17cfa436e0df.png)

The package is also no longer present in .atom/packages/ folder so the uninstall worked. Go to Install page and the Package is still in a disabled state (much as it would look after disabling, but before uninstalling). In this situation clicking on 'Enable' and on 'Uninstall' both have no effect and it seems like a dead end.
![disableuninstall3](https://cloud.githubusercontent.com/assets/11758299/8509871/76f8be9c-22b8-11e5-89a3-69c35de35b5c.png)

It seems that the uninstall procedure isn't removing the package name from the 'disabledPackages' list in the config.cson file. I presume having this process remove the package from the list explicitly should resolve this issue. In the meantime I think manually removing the package from the list would be a more straightforward workaround than using apm on the console, worked perfectly for me and the package was installable again.

**Comment by HitomiTenshi** [comment] 2015-07-05 01:22
Or you could use apm to re-install the bugged package and then re-enable it once it's installed. This is how I currently fix the issue (temporarily).

**Comment by benogle** [comment] 2015-07-07 00:59
This was fixed by https://github.com/atom/settings-view/pull/571. It should be out in the next version of atom tomorrow.

**Closed by benogle** 2015-07-07 00:59 UTC
Labels: bug
