### ISSUE TITLE
Failed to activate the latex package

### ISSUE THREAD

**Issue by samuela** [atom/settings-view#435] opened 2015-03-18 05:19 UTC
[Enter steps to reproduce below:]

1. Update to version 0.20.0.

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to activate the latex package

```
At Cannot read property 'bind' of undefined

TypeError: Cannot read property 'bind' of undefined
  at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:363:117)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:243:16)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -0:46.7 core:copy (atom-text-editor.editor)
     -0:46.5 core:move-down (atom-text-editor.editor)
     -0:46.1 core:move-left (atom-text-editor.editor)
  4x -0:45.8 editor:select-to-beginning-of-word (atom-text-editor.editor)
  6x -0:45.0 core:select-left (atom-text-editor.editor)
     -0:43.4 core:paste (atom-text-editor.editor)
     -0:43.0 core:save (atom-text-editor.editor)
     -0:26.1 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:24.5 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini)
     -0:23.1 core:confirm (atom-text-editor.editor.mini)
     -0:19.4 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:17.8 core:backspace (atom-text-editor.editor.mini)
     -0:17.4 core:confirm (atom-text-editor.editor.mini)
     -0:14.4 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
     -0:01.9 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:00.6 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "helium",
      "ide-haskell",
      "linter-flake8",
      "language-objective-c"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.5.0
autocomplete-snippets, v1.2.0
color-picker, v1.4.4
language-haskell, v1.0.0
language-julia, v2.0.0
language-latex, v0.4.1
language-matlab, v0.1.0
language-scala, v1.1.0
latex, v0.20.0
linter, v0.12.0
monokai, v0.12.0
script, v2.18.0
terminal-status, v1.3.5
web-view, v0.3.0

# Dev
No dev packages
```

**Comment by davidfokkema** [comment] 2015-03-18 10:02
You probably don't want too many me-too's, but just to let you know it is not confined to a single setup.

**Comment by thomasjo** [comment] 2015-03-18 13:19
I got this myself (I'm the author of the package by the way). I believe it might be caused by not handling de-activation properly. Going to try to reproduce it, then fix it.

Closing this issue and re-opening it on the latex repo.

**Closed by thomasjo** 2015-03-18 13:19 UTC
