### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/gligorijan/.atom/packages/autocomplete-plus/lib/provider.coffee'

### ISSUE THREAD

**Issue by gligorijan** [atom/settings-view#392] opened 2015-02-25 01:01 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.174.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/gligorijan/.atom/packages/autocomplete-plus/lib/provider.coffee'

```
At /Applications/Atom.app/Contents/Resources/app/src/package.js:241

Error: ENOENT, no such file or directory '/Users/gligorijan/.atom/packages/autocomplete-plus/lib/provider.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.exports._compileFile (/Applications/Atom.app/Contents/Resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:194:14)
  at getSourceMap (/Applications/Atom.app/Contents/Resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:302:22)
  at getSourceMapping (/Applications/Atom.app/Contents/Resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:310:19)
  at formatSourcePosition (/Applications/Atom.app/Contents/Resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:262:16)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:328:34
  at Function.Error.prepareStackTrace (/Applications/Atom.app/Contents/Resources/app/node_modules/grim/node_modules/coffeestack/node_modules/coffee-script/lib/coffee-script/coffee-script.js:331:7)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:241:79)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-compile-less",
      "snippets"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editor-stats, v0.17.0
emmet, v2.3.3
highlight-line, v0.9.3
javascript-snippets, v1.0.0
less-autocompile, v0.3.3
linter, v0.11.1
linter-csslint, v0.0.11
linter-php, v0.0.11
minimap, v4.3.1
project-manager, v1.15.5
wakatime, v4.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment] 2015-02-25 01:27
Duplicate of #388, please subscribe there for updates.

**Closed by 50Wliu** 2015-02-25 01:27 UTC
