### ISSUE TITLE
Uncaught TypeError: Cannot read property 'append' of undefined

### ISSUE THREAD

**Issue by therealklanni** [atom/settings-view#333] opened 2015-01-11 01:57 UTC
[Enter steps to reproduce below:]

1. Attempt to install the following theme: https://atom.io/packages/solarized-dark-apparent-ui

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.166.0

### Stack Trace

Uncaught TypeError: Cannot read property 'append' of undefined

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/themes-panel.js:204

TypeError: Cannot read property 'append' of undefined
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/themes-panel.js:204:36
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:368:19)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:284:19
  at exit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:469:12)

```

### Commands

```
     -4:15.4 core:confirm (atom-text-editor.editor.mini)
     -0:08.8 symbols-view:toggle-file-symbols (div.settings-view.pane-item)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/user/Projects"
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.2.0
command-logger, v0.20.0
editor-stats, v0.16.0
emmet, v2.3.0
travis-ci-status, v0.11.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by LPGhatguy** [comment] 2015-01-11 05:19
I got the same issue with no plugins while installing a converted Textmate theme.

**Comment by kevinsawicki** [comment] 2015-01-13 02:12
This is a duplicate of #322 and wasfixed in the 0.170 Atom release

**Closed by kevinsawicki** 2015-01-13 02:12 UTC
