### ISSUE TITLE
Add sort function to packages

### ISSUE THREAD

**Issue by juliusdanek** [atom/settings-view#729] opened 2016-02-09 18:27 UTC
A sort function for packages would be great, like popularity, # of downloads, relevance, etc.

**Comment by tabascoeye** [comment] 2016-02-12 13:02
since "number of downloads" is the only metric shown at the moment, I would also love to have a "sorting filter" for that.

**Comment by lee-dohm** [comment] 2016-02-15 22:18
This is a duplicate of https://github.com/atom/settings-view/issues/384. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-02-15 22:18 UTC

**Comment by juliusdanek** [comment] 2016-02-15 22:59
Thanks for pointing out. However, the other issue has remained unclosed for over a year now.
