### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Nxt3** [atom/settings-view#359] opened 2015-01-29 03:03 UTC
No idea what I did to reproduce this. I restarted Atom, then opened settings.

I'm on Linux Mint 17. Latest version of Atom (v0.176.0)

**Atom Version**: 0.176.0
**System**: linux 3.13.0-40-generic
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.174.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:115

TypeError: undefined is not a function
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:115:31
  at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app/src/config.js:613:7)
  at Config.module.exports.Config.observe (/usr/share/atom/resources/app/src/config.js:133:21)
  at SettingsPanel.module.exports.SettingsPanel.observe (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:152:47)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:110:17
  at Array.forEach (native)
  at SettingsPanel.module.exports.SettingsPanel.bindInputFields (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:104:47)
  at SettingsPanel.module.exports.SettingsPanel.initialize (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:43:12)
  at SettingsPanel.View (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new SettingsPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:16:50)
  at InstalledPackageView.module.exports.InstalledPackageView.populate (/usr/share/atom/resources/app/node_modules/settings-view/lib/installed-package-view.js:179:28)
  at InstalledPackageView.module.exports.InstalledPackageView.initialize (/usr/share/atom/resources/app/node_modules/settings-view/lib/installed-package-view.js:143:12)
  at InstalledPackageView.View (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new InstalledPackageView (/usr/share/atom/resources/app/node_modules/settings-view/lib/installed-package-view.js:36:57)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:268:18
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:288:19)
  at SettingsView.module.exports.SettingsView.showPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:324:24)
  at SettingsView.module.exports.SettingsView.addPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:279:21)
  at SettingsView.module.exports.SettingsView.addPackagePanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:266:19)
  at SettingsView.module.exports.SettingsView.initializePanels (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:178:14)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:92:24
  at process._tickCallback (node.js:386:11)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.class",
      "*.git"
    ],
    "disabledPackages": [
      "language-ruby",
      "language-sass",
      "language-php",
      "language-perl",
      "welcome",
      "feedback",
      "git-diff",
      "open-on-github",
      "background-tips",
      "styleguide",
      "timecop",
      "deprecation-cop",
      "language-emblem",
      "language-ruby-on-rails",
      "language-toml",
      "language-yaml",
      "metrics",
      "language-property-list",
      "autocomplete-plus",
      "spell-check",
      "go-to-line",
      "autoflow",
      "bookmarks",
      "themed-settings",
      "package-generator",
      "markdown-preview",
      "atom-color-highlight",
      "sort-lines"
    ],
    "themes": [
      "isotope-ui",
      "material-design-syntax"
    ],
    "projectHome": "/home/nxt3/code",
    "audioBeep": false,
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.3.0
custom-title, v0.7.0
docblockr, v0.5.8
file-icons, v1.4.8
fuzzy-finder, v0.65.0
isotope-ui, v1.2.8
linter, v0.10.1
linter-javac, v0.1.3
material-design-syntax, v1.4.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment] 2015-01-29 20:17
Could you please try to reproduce this in safe mode (`atom --safe`)?

**Comment by iNate71** [comment] 2015-01-31 19:43
I can try, but no promises. It's happened a few more times since reporting this, but I have no idea what I did to create the error.

**Comment by mnquintana** [comment] 2015-04-14 13:15
@Nxt3 Have you experienced this with the latest version of Atom (0.190.0)?

**Comment by despairblue** [comment] 2015-04-14 18:52
I experienced it while trying to enable the disabled *linter-jshint* package, though not in safe mode:
```
At /home/despairblue/.atom/packages/settings-view/lib/package-detail-view.coffee:65

TypeError: undefined is not a function
  at PackageDetailView.module.exports.PackageDetailView.activate (/home/despairblue/.atom/packages/settings-view/lib/package-detail-view.coffee:65:11)
  at PackageDetailView.module.exports.PackageDetailView.initialize (/home/despairblue/.atom/packages/settings-view/lib/package-detail-view.coffee:56:6)
  at PackageDetailView.View (/usr/share/atom/resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageDetailView (/home/despairblue/.atom/packages/settings-view/lib/package-detail-view.coffee:20:3)
  at /home/despairblue/.atom/packages/settings-view/lib/settings-view.coffee:120:11
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/home/despairblue/.atom/packages/settings-view/lib/settings-view.coffee:142:17)
  at SettingsView.module.exports.SettingsView.showPanel (/home/despairblue/.atom/packages/settings-view/lib/settings-view.coffee:167:17)
  at space-pen-div.<anonymous> (/home/despairblue/.atom/packages/settings-view/lib/package-card.coffee:79:92)
  at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)
```

**Comment by mnquintana** [comment] 2015-04-14 18:56
@despairblue I can't seem to reproduce that (with linter-jshint) – do you have more detailed reproduction steps by any chance?

**Comment by despairblue** [comment] 2015-04-14 21:23
I can't reproduce it either. :disappointed:

**Comment by vindicatorr** [comment] 2015-04-15 09:44
I CAN reproduce this in --safe mode:
<hr>
1. Disable a "Community Package"
2. $ atom --safe
3. Click "Packages" ->"Settings View"->"Manage Packages"
4. Click disabled "Community Package".

**Atom Version**: 0.191.0-8aba0f7
**System**: linux 3.16.0-4-amd64
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.191.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/local/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:155

TypeError: undefined is not a function
  at PackageDetailView.module.exports.PackageDetailView.activate (/usr/local/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:155:26)
  at PackageDetailView.module.exports.PackageDetailView.initialize (/usr/local/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:145:12)
  at PackageDetailView.View (/usr/local/share/atom/resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageDetailView (/usr/local/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:38:54)
  at /usr/local/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:282:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/usr/local/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:287:19)
  at SettingsView.module.exports.SettingsView.showPanel (/usr/local/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:323:24)
  at space-pen-div.<anonymous> (/usr/local/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:175:26)
  at space-pen-div.jQuery.event.dispatch (/usr/local/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/usr/local/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -5:55.1 settings-view:uninstall-packages (atom-pane.pane.active)
     -0:48.5 settings-view:open (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "omnisharp-atom"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```
<hr>
I found this while working through the Deprecated Cop issues with "ContextMenuManager:Add" being the last one. The other 4+ were related to omnisharp which I rectified (jsquery,project.json). I think the CMM deprecation also deals with omnisharp because I disabled the package, restarted and the cop didn't show up.
I thought I might get more information about the packages by clicking on the package itself (not the buttons within) and that is when the error occurred.

At first I thought it might be due to my futzing with omni, but the same behavior occurs when I disable autocomplete-plus.
I can replicate this issue at will, so if video helps I can do that.

BTW, I **LOVE** github ajax behaviors including markdown and the friendly and informative debugging in atom that is automatically made pretty with markdown.

One thing I don't care for and don't know if it's a bug, but if I click on an external link in atom, it opens the browser and atom becomes unresponsive until I close the browser.

**Comment by izuzak** [comment] 2015-04-15 09:51
> I CAN reproduce this in --safe mode:

@vindicatorr That error should be fixed in the latest released version (0.191.0) or on the latest master version of Atom (0.192.0-ca99ff4). You're running an old version (a version before 0.191.0 was released). Can you try that and let us know if you can still reproduce?

**Comment by vindicatorr** [comment] 2015-04-15 10:35
Uhhhh,"0.191.0-8aba0f7" is "a version before 0.191.0"? I swear it could only have been 1 day since I first built this version of atom (unless I lost another day or so somewhere).

I did a pull "8aba0f7..ca99ff4" and will build that now...

Yup, 0.192.0-ca99ff4 succeeded.

**Comment by izuzak** [comment] 2015-04-15 10:40
> @izuzak Uhhhh,"0.191.0-8aba0f7" is "a version before 0.191.0"?

Yep -- you can read it as "0.191.0-alpha" if that's easier. It's a pre-release of 0.191.0, it happens before 0.191.0 is actually released. 

> Yup, 0.192.0-ca99ff4 succeeded.

Great, thanks for confirming. :+1:

**Comment by vindicatorr** [comment] 2015-04-15 10:47
@izuzak I actually did NOT know that. Thanks for the info.
I would have thought it was just a commit later/above the revision version. And anything before 0.191.0 would be 0.190.#-\*, so 0.190.9-\* would be earlier/before, but 0.191.0-* would be later/above.

**Comment by izuzak** [comment] 2015-04-15 10:55
Yeah, it's not really obvious. I did check http://semver.org/ before typing that comment :smile:

Some snippets:

> Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

> When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version. Example: 1.0.0-alpha < 1.0.0. 

> A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

This doesn't say that a pre-release is created before the release, but I think that makes sense -- it doesn't make a lot of sense to create a pre-release _after_ a release (with the same version).

**Comment by vindicatorr** [comment] 2015-04-15 11:23
@izuzak OK, I think I can buy into that (not that it's for sale, but just "is").
I actually think I've seen that site before when kernel folks were talking about whether or not to jump to 4.0 some months back.
Just the correlation between alpha and a commit didn't strike with me until you pointed it out.

I'm sure I could draw this conversation out on versioning, such as me thinking any function addition/subtraction would fall under a minor version (or major if huge (class/namespace)) and any fixes for existing code flaws would fall under the patch/revision version.
To me, a commit looks like any code addition/subtraction which could be any of the minor/major/revision positions. It would just be a question whether the maintainers all agree that a series of commits would be ready for a tag/branch to be set which would define that series as a major/minor/revision increment.

But I don't want to draw it out since it doesn't deal with OP and I should just accept it as-is.
I do thank you for the enlightenment though, as well as pointing out the fix being ready.

The original atom error linked me to this ticket/issue which currently shows as being opened.
Since it seems to be fixed, I'd say it's ready to be closed. Thanks again Ivan.

**Comment by despairblue** [comment] 2015-04-15 12:10
@vindicatorrr your other mentioned bug might be this one:
https://github.com/atom/atom-shell/issues/1348#issuecomment-91230583

**Comment by vindicatorr** [comment] 2015-04-15 12:40
@despairblue Not quite.
```
$ ps -A
...
atom
atom
atom
atom
xdg-open
x-www-browser
ps -A
```
Browser is functional, but atom is not. At least the drawing appears to be fixed because with the last release, I had a ghosting effect in atom when I'd move the browser window over it.
When I close the browser, atom regains functionality but may have a message box showing:
```
Editor is not responding
The editor is not responding. Would you like to force close it or just keep waiting.
```
I can click on "Keep Waiting" and atom's functionality continues.

**Comment by despairblue** [comment] 2015-04-15 12:55
That's exactly it, there are actually two problems and only one of them is
atoms fault, so to speak. the one you are experiencing is that xdg-open
does not fork the browser into the background.

The other one is that chrome cannot be started sandoxed by a non sandboxed
app, like atom, if I understood this correctly. and that is one you don't
experience. what browser are you using? Firefox does not have this issue
for example.

**Comment by vindicatorr** [comment] 2015-04-15 13:07
@despairblue I still say it isn't it based on the issue's OP:
"shell.openExternal no longer works" I am assuming directly relates to "xdg-open".
It DOES work. It opened the browser.
While I agree that atom opens the browser as a foreground process, I see it as a different issue because it "does work".

When I scroll down to your post containing "\<browser\> complains about something and doesn't quit", my browser doesn't complain and it will quit if I close it.
The browser opened is IceWeasel

**Comment by despairblue** [comment] 2015-04-15 13:40
@vindicatorr yeah, but that's why I linked directly to my comment. You don't experience the complete bug as described there since you don't use chrome as your default browser, but iceweasel, which is firefox and as mentioned firefox does start, though still in a blocking manner (because of xdg-open not forking it into the background).

I don't think atom behaves wrong if it start xdg-open in a blocking manner, it's rather that xdg-open should fork applications into the background, and then return with 0 signaling that it found a program to open that link or file, in my opinion.

But you are correct that the linked [issue](https://github.com/atom/atom-shell/issues/1348) is mainly about chrome refusing to work if opened from atom (though still running w/o opening a window and thus blocking atom) because atom dropped some privileges that chrome needs for sandboxing (I guess).
So to address your specific case you could open another issue at the atom-shell repository asking if atom-shell could run xdg-open in a non blocking manner (forking it in the background). I'd rather see xdg-open patched (see https://bugs.freedesktop.org/show_bug.cgi?id=89902), but that would change current behavior and might not happen and if it does it will definitely not happen before 1.2.

**Comment by vindicatorr** [comment] 2015-04-15 14:03
I do find the blocking to be problematic.
I'd like to open the link and continue to refer back to atom if possible:
eg. 1) A bug is found and a link is provided in atom. I click it, paste the error and would like to go back into atom to walk through what I did to cause the error.
2) A link in atom to takes me to atom's docs for their api. I'd like to refer to the docs while continuing to code in atom.
That currently can't happen.

I don't understand why xdf-open wouldn't have an async option. They can just have multiple definitions for the open function where one accepts an bool async parameter and the default can be for synchronous call.
I don't know if this would be forking to the background, but in the shell I know I can append "&" to a command to have it run in the background ($ leafpad some.file &), so that should be easy enough.
I just don't know of the pros/cons of forking vs building it into xdg-open.
If it WILL get into xdg-open, then it can wait.

**Closed** 2015-04-28 22:52 UTC
Labels: more-information-needed, needs-reproduction
