### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/jatinganhotra/.atom/packages/autocomplete-plus/lib/provider.coffee'

### ISSUE THREAD

**Issue by jatinganhotra** [atom/settings-view#403] opened 2015-03-02 19:01 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.183.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/jatinganhotra/.atom/packages/autocomplete-plus/lib/provider.coffee'

```
At /Applications/Atom.app/Contents/Resources/app/src/package.js:243

Error: ENOENT, no such file or directory '/Users/jatinganhotra/.atom/packages/autocomplete-plus/lib/provider.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.exports._compileFile (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:206:14)
  at getSourceMap (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:314:22)
  at getSourceMapping (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:322:19)
  at formatSourcePosition (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:274:16)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:340:34
  at Function.Error.prepareStackTrace (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:343:7)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:243:79)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:334:19
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:640:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:804:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:617:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:231:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:409:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:162:14)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/available-package-view.js:331:36
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:273:15
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -0:57.6 snippets:expand (input.hidden-input)
     -0:57.6 editor:indent (input.hidden-input)
  4x -0:56.9 core:backspace (atom-text-editor.editor.vim-mode.insert-mode)
     -0:53.5 core:move-down (input.hidden-input)
     -0:52.7 core:move-up (atom-text-editor.editor.vim-mode.insert-mode)
  2x -0:51.4 core:backspace (atom-text-editor.editor.vim-mode.insert-mode)
     -0:49.7 settings-view:open (atom-text-editor.editor.vim-mode.insert-mode)
     -0:35.7 core:save (atom-text-editor.editor.vim-mode.insert-mode)
     -0:35.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode)
     -0:33.3 editor:newline (input.hidden-input)
  3x -0:32.8 core:backspace (atom-text-editor.editor.vim-mode.insert-mode)
     -0:30.7 snippets:next-tab-stop (input.hidden-input)
     -0:30.7 snippets:expand (input.hidden-input)
     -0:30.7 editor:indent (input.hidden-input)
     -0:30.1 core:backspace (atom-text-editor.editor.vim-mode.insert-mode)
  3x -0:27.6 core:save (atom-text-editor.editor.vim-mode.insert-mode)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
linter, v0.12.0
vim-mode, v0.34.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-02 20:14
Duplicate of #388, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-02 20:14 UTC
