### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by pahakalle** [atom/settings-view#594] opened 2015-07-19 13:49 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At C:\Users\Kalle\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56

TypeError: Cannot read property 'message' of undefined
  at ErrorView.module.exports.ErrorView.initialize (C:\Users\Kalle\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56:21)
  at ErrorView.View (C:\Users\Kalle\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new ErrorView (C:\Users\Kalle\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:14:46)
  at C:\Users\Kalle\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\installed-packages-panel.js:179:44
  at Emitter.module.exports.Emitter.emit (C:\Users\Kalle\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\Kalle\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:579:27)
  at C:\Users\Kalle\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:359:17
  at C:\Users\Kalle\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:384:20
  at exit (C:\Users\Kalle\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
  at triggerExitCallback (C:\Users\Kalle\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Kalle\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -3:49 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -3:24.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:12.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:08.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:48.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -1:47.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.10
compass, v0.9.1
csslint, v1.1.3
editorconfig, v1.0.1
emmet, v2.3.12
highlight-line, v0.11.0
javascript-snippets, v1.0.0
pigments, v0.8.4
project-manager, v1.15.11
terminal-status, v1.6.8
trailing-spaces, v0.3.2
vim-mode, v0.55.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-07-19 14:03
This is a duplicate of #577 – it's been fixed for the next release of Atom.

**Closed by mnquintana** 2015-07-19 14:03 UTC

**Comment by pahakalle** [comment] 2015-07-19 14:41
when is the next update released?
