### ISSUE TITLE
Updates never thinks Atom-Beautify finishes updating

### ISSUE THREAD

**Issue by frankhale** [atom/settings-view#745] opened 2016-03-04 19:25 UTC
Reference ticket on the Atom-Beautify side: https://github.com/Glavin001/atom-beautify/issues/841

Platform: Windows 10
Atom Version: 1.5.4

When there is an Atom-Beautify update and I go to update it the UI spinner that provides feedback about packages installing never goes away. It's like Atom can't tell the package has actually finished updating. If I wait a while so I can be reasonably sure Atom-Beautify has finished and I click "Check For Updates" then the UI refreshes and it knows that the update has finished installing. I've only seen this happen with Atom-Beautify. This has been happening for me on multiple machines for a number of months now. 

I'm not sure if the issue is on the settings-view side or the Atom-Beautify side. Any insight would be greatly appreciated.

CC @Glavin001

**Comment by 50Wliu** [comment] 2016-03-04 20:24
This is a duplicate of #532 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-04 20:24 UTC
