### ISSUE TITLE
Failed to activate the go-playground package

### ISSUE THREAD

**Issue by weidewang** [atom/settings-view#700] opened 2015-11-17 02:37 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.231.0

### Stack Trace

Failed to activate the go-playground package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:10:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
  2x -5:57.8.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -4:48.6.0 settings-view:open (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -2:55.1.0 grammar-selector:show (atom-text-editor.editor)
  3x -2:51.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:50.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:50.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  4x -2:41.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -2:26.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:28.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:21 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:17.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 13x -0:58.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:56.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:50.2.0 core:copy (div.text.native-key-bindings)
     -0:22.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:22 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "vim-mode",
      "secure-copy",
      "atom-dlang"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
go-playground, v0.0.2
go-plus, v3.5.2
language-clojure, v0.18.0
language-lua, v0.9.4
language-nginx, v0.6.1
linter-clojure, v1.0.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-17 02:42
The go-playground package no longer appears to be maintained.  I would suggest uninstalling it and finding an alternative.

(Also, a duplicate of tachiba/atom-go-playground#10)

**Closed by 50Wliu** 2015-11-17 02:42 UTC
