### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by skatedude007** [atom/settings-view#600] opened 2015-07-23 16:36 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8 Pro
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At C:\Users\Jash\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56

TypeError: Cannot read property 'message' of undefined
  at ErrorView.module.exports.ErrorView.initialize (C:\Users\Jash\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56:21)
  at ErrorView.View (C:\Users\Jash\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new ErrorView (C:\Users\Jash\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:14:46)
  at C:\Users\Jash\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\installed-packages-panel.js:179:44
  at Emitter.module.exports.Emitter.emit (C:\Users\Jash\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\Jash\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:579:27)
  at C:\Users\Jash\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:359:17
  at C:\Users\Jash\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:384:20
  at exit (C:\Users\Jash\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
  at triggerExitCallback (C:\Users\Jash\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Jash\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -5:56.6.0 core:select-right (atom-text-editor.editor.is-focused)
     -5:54.8.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -5:54.4.0 core:select-left (atom-text-editor.editor.is-focused)
     -5:50.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -5:09.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:08.7.0 core:paste (atom-text-editor.editor.is-focused)
  5x -5:08.2.0 core:select-left (atom-text-editor.editor.is-focused)
  7x -5:03.3.0 core:select-up (atom-text-editor.editor.is-focused)
     -5:00.2.0 core:select-right (atom-text-editor.editor.is-focused)
     -4:59.1.0 core:select-up (atom-text-editor.editor.is-focused)
     -4:57.4.0 core:copy (atom-text-editor.editor.is-focused)
     -4:18.1.0 core:save (atom-text-editor.editor.is-focused)
  4x -1:24.5.0 emmet:balance-outward (atom-text-editor.editor.is-focused)
     -1:12.9.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:09.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:01.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
achievements, v0.7.2
atom-alignment, v0.12.1
atom-beautify, v0.28.8
color-picker, v2.0.11
editor-stats, v0.17.0
emmet, v2.3.12
file-icons, v1.5.8
javascript-snippets, v1.0.0
javascript-standard-snippets, v0.2.0
linter, v1.2.4
linter-bootlint, v0.0.6
linter-clang, v2.26.2
linter-coffeelint, v1.0.0
linter-cpplint, v0.1.4
linter-csslint, v0.0.14
linter-erb, v0.1.1
linter-eslint, v3.0.1
linter-flake8, v1.5.0
linter-flow, v0.1.6
linter-gjslint, v0.0.5
linter-haml, v0.4.0
linter-htmlhint, v0.0.17
linter-javac, v0.1.4
linter-js-standard, v2.0.3
linter-jscs, v1.13.0
linter-jshint, v1.1.4
linter-jsxhint, v0.1.2
linter-less, v2.0.3
linter-pep257, v0.2.1
linter-pep8, v1.0.1
linter-php, v1.0.2
linter-phpcs, v1.0.6
linter-phpmd, v0.0.11
linter-pyflakes, v0.0.5
linter-pylama, v0.1.4
linter-pylint, v0.2.2
linter-reek, v2.0.0
linter-rubocop, v0.2.7
linter-ruby, v0.1.6
linter-scss-lint, v1.0.5
linter-shellcheck, v0.0.8
linter-slim, v0.5.1
linter-stylint, v2.0.0
linter-swiftc, v2.0.0
linter-tidy, v1.0.1
linter-xmllint, v0.0.7
minimap, v4.12.0
minimap-linter, v1.0.0
pigments, v0.9.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-07-23 16:56
This is a duplicate of #577 – it's been fixed for the next release of Atom.

**Closed by mnquintana** 2015-07-23 16:56 UTC
