### ISSUE TITLE
Uncaught TypeError: body.filter is not a function

### ISSUE THREAD

**Issue by koichi1999** [atom/settings-view#1068] opened 2018-08-03 07:36 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.12.6
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.255.0

### Stack Trace

Uncaught TypeError: body.filter is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:305

TypeError: body.filter is not a function
    at Request._callback (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:305:39)
    at Request.self.callback (/app.asar/node_modules/settings-view/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -2:30.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
emmet 2.4.3 
processing 0.13.0 
processing-autocomplete 0.2.0 
processing-language 0.2.0 
```

**Comment by cawleymillward** [comment] 2018-08-03 10:44
Also getting this error:
[Enter steps to reproduce:]

1. Go to Settings > Install
2. Type anything into the search field.

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: "Fedora release 28 64bit 
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.255.0

### Stack Trace

Uncaught TypeError: body.filter is not a function

```
At /usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:305

TypeError: body.filter is not a function
    at Request._callback (/usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:305:39)
    at Request.self.callback (/app.asar/node_modules/settings-view/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -3:10.6.0 core:confirm (input.hidden-input)
     -2:30.2.0 core:select-all (input.hidden-input)
     -2:25 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
busy-signal 1.4.3 
code-peek 1.4.21 
codeigniter 0.3.2 
emmet 2.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
open-recent 5.0.0 
pigments 0.40.2 
todo-show 2.3.0 
```

**Comment by rsese** [comment] 2018-08-03 18:14
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/settings-view/issues/1052 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-08-03 18:14 UTC
