### ISSUE TITLE
Can't revert back to Featured Packages list in Install Packages

### ISSUE THREAD

**Issue by jonobacon** [atom/settings-view#705] opened 2015-11-25 18:37 UTC
*As requested, moving this issue here from https://github.com/atom/atom/issues/9705*

Hi Folks,

I just wanted to report a small issue (possibly not an issue, depending on your view).

I am currently running 1.2.1 and in the *Install Packages* screen I see the Features Packages. This is really helpful for new Atom users.

I can then search for a specific package (e.g. `emmett`), but then when I remove the search term from the text box it doesn't go back to the Featured Packages view. As such, the only way to see the Featured Packages is to restart Atom (switching from a different settings view back to Install Packages doesn't reset the view).

# Potential Solutions

A few options for resolving this:

**Reset View Based on Typing**

When the user deletes the search box so there are no characters, it could then re-instate the view.

**Provide a Link**

Another option is that a link to *Featured Packages* (and potentially other searches such as *Popular Packages) under the search box.

**Comment by izuzak** [comment] 2015-11-27 15:11
@jonobacon Can you share a GIF which demonstrates that behavior? I'm having trouble reproducing that exact behavior. Here's what I see:

![fea](https://cloud.githubusercontent.com/assets/38924/11443871/045b38fc-9521-11e5-88d6-cab0d2851f2a.gif)

Notice that after searching -- the list of featured packages is still around, but at the bottom. So, I think this isn't true:

> As such, the only way to see the Featured Packages is to restart Atom (switching from a different settings view back to Install Packages doesn't reset the view).

Do you see the same behavior? If so, can you modify the title and body of the issue? (I do think it would be helpful if the list of featured packages is moved to the top if the search is reset). Thanks!

**Comment by bastilian** [comment] 2016-04-06 07:10
This is a duplicate of #590

**Closed** 2016-09-30 02:42 UTC
Labels: more-information-needed
