### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by AdrianKoshka** [atom/settings-view#665] opened 2015-09-24 23:43 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 15.04
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/error-view.js:56

TypeError: Cannot read property 'message' of undefined
    at ErrorView.module.exports.ErrorView.initialize (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/error-view.js:56:21)
    at ErrorView.View (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new ErrorView (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/error-view.js:14:46)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/updates-panel.js:84:44
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:579:27)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:303:17
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:326:20
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
```

### Commands

```
     -1:11.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/adrian/git"
  }
}
```

### Installed Packages

```coffee
# User
language-docker, v1.1.3
language-latex, v0.6.1
markdown-preview-plus, v2.1.1

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-09-25 00:10
You're running an old version of Atom - this is fixed in the latest version (1.0.18)

Duplicate of https://github.com/atom/settings-view/issues/577

**Closed by mnquintana** 2015-09-25 00:10 UTC

**Comment by rafaelnery** [comment] 2015-10-31 21:52
I'm in Fedora 22
Atom 1.0.18 ... 1.2
And this error persist.

But via APM works!

**Comment by zky001** [comment] 2015-12-02 04:07
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Unknown Windows Version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0


### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At C:\Users\whywin7\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56

TypeError: Cannot read property 'message' of undefined
  at ErrorView.module.exports.ErrorView.initialize (C:\Users\whywin7\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56:21)
  at ErrorView.View (C:\Users\whywin7\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new ErrorView (C:\Users\whywin7\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:14:46)
  at C:\Users\whywin7\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\install-panel.js:156:44
  at Emitter.module.exports.Emitter.emit (C:\Users\whywin7\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\whywin7\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:579:27)
  at C:\Users\whywin7\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:359:17
  at C:\Users\whywin7\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:384:20
  at exit (C:\Users\whywin7\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
  at triggerExitCallback (C:\Users\whywin7\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\whywin7\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
  2x -9:40 core:copy (atom-text-editor.editor.is-focused)
     -4:38.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -4:32.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -4:25.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:20.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:20.7.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -4:06.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:05.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:57.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:56.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```
