### ISSUE TITLE
Can not set Font Family named 'M+ 1m'

### ISSUE THREAD

**Issue by arielyang** [atom/settings-view#374] opened 2015-02-07 05:28 UTC
Can not set and recognize Font Family named 'M+ 1m'.

**Comment by lee-dohm** [comment] 2015-02-07 19:03
See atom/atom#2912 for background. Closing this as a duplicate of atom/settings-view#57. Please subscribe there for updates.

**Closed by lee-dohm** 2015-02-07 19:03 UTC
