### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/ryan/.atom/packages/autocomplete-plus/lib/provider.coffee'

### ISSUE THREAD

**Issue by porkloin** [atom/settings-view#396] opened 2015-02-25 22:35 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Mac OS X 10.9.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.183.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/ryan/.atom/packages/autocomplete-plus/lib/provider.coffee'

```
At /Applications/Atom.app/Contents/Resources/app/src/package.js:241

Error: ENOENT, no such file or directory '/Users/ryan/.atom/packages/autocomplete-plus/lib/provider.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.exports._compileFile (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:206:14)
  at getSourceMap (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:314:22)
  at getSourceMapping (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:322:19)
  at formatSourcePosition (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:274:16)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:340:34
  at Function.Error.prepareStackTrace (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:343:7)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:241:79)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -2:57.6 core:close (atom-text-editor.editor)
     -2:35.1 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -2:25.0 window:decrease-font-size (ul.list-inline.tab-bar.inset-panel)
  4x -2:24.4 window:increase-font-size (ul.list-inline.tab-bar.inset-panel)
     -2:22.4 window:reset-font-size (ul.list-inline.tab-bar.inset-panel)
  2x -2:21.3 window:decrease-font-size (ul.list-inline.tab-bar.inset-panel)
     -1:42.9 settings-view:open (ul.list-inline.tab-bar.inset-panel)
  2x -0:59.7 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:56.4 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:54.7 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:54.7 core:cancel (atom-text-editor.editor.mini)
     -0:52.8 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
     -0:52.1 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:52.1 core:cancel (atom-text-editor.editor.mini)
     -0:50.9 settings-view:open (ul.list-inline.tab-bar.inset-panel)
  4x -0:41.9 core:backspace (atom-text-editor#editor.fontFamily.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
minimap, v4.3.1
remote-edit, v1.6.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-02-25 22:59
Duplicate of #388, please subscribe there for updates.

**Closed by 50Wliu** 2015-02-25 22:59 UTC
