### ISSUE TITLE
Uncaught TypeError: body.filter is not a function

### ISSUE THREAD

**Issue by fabjab86** [atom/settings-view#1071] opened 2018-08-17 10:03 UTC
opened settings, 
typed in atom-live-server,
clicked package
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.255.0

### Stack Trace

Uncaught TypeError: body.filter is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:305

TypeError: body.filter is not a function
    at Request._callback (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:305:39)
    at Request.self.callback (/app.asar/node_modules/settings-view/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -5:23.3.0 core:backspace (input.hidden-input)
     -5:22.9.0 core:move-left (input.hidden-input)
     -5:21.7.0 core:move-down (input.hidden-input)
     -5:19.9.0 snippets:next-tab-stop (input.hidden-input)
     -5:19.9.0 snippets:expand (input.hidden-input)
     -5:19.9.0 editor:indent (input.hidden-input)
     -5:18.2.0 snippets:next-tab-stop (input.hidden-input)
     -5:18.2.0 snippets:expand (input.hidden-input)
     -5:18.2.0 editor:indent (input.hidden-input)
  2x -5:16.5.0 core:save (input.hidden-input)
     -4:21.5.0 package-generator:generate-package (input.hidden-input)
     -4:19.2.0 editor:consolidate-selections (input.hidden-input)
     -4:19.2.0 core:cancel (input.hidden-input)
     -1:25.7.0 settings-view:open (input.hidden-input)
  4x -1:01.5.0 core:confirm (input.hidden-input)
 17x -0:56.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by Colobri** [comment] 2018-08-17 10:05
Settings->Install and type anything gives me this error.

**Comment by Luca-Terrazzan** [comment] 2018-08-17 10:07
Having this issue too since last update

**Comment by Luca-Terrazzan** [comment] 2018-08-17 10:09
Seems like atom package manager is having issues in general:
https://atom.io/packages/search?q=angular

**Comment by VladLegkowski** [comment] 2018-08-17 10:16
Installed Atom yesterday and now having same issue, same steps as @Colobri...

**Comment by souka1** [comment] 2018-08-17 10:26
having the same error

**Comment by ayotomiwaa** [comment] 2018-08-17 10:28
This is my first time of using Atom and I am having this error too.

**Comment by Aerijo** [comment] 2018-08-17 10:30
@souka1 @ayotomiwaa Does [this link](https://atom.io/packages/search?q=angular) work for you? The issue seemed to be a problem with the Atom website, not the editor itself.

**Comment by ayotomiwaa** [comment] 2018-08-17 10:34
try and update Atom and try and search for packages afterwards. See if it would work.

**Comment by Aerijo** [comment] 2018-08-17 10:35
@ayotomiwaa Does the link work though? It should be opened in your browser, not in Atom.

**Comment by ayotomiwaa** [comment] 2018-08-17 10:38
The link works

**Comment by Aerijo** [comment] 2018-08-17 10:39
@ayotomiwaa OK. And now, is the settings package still not working?

**Comment by ayotomiwaa** [comment] 2018-08-17 10:41
It is working now

**Comment by rsese** [comment] 2018-08-17 18:18
Looks like some folks found it already but going to go ahead and close as a duplicate of https://github.com/atom/settings-view/issues/1052.  There was some atom.io downtime as @Aerijo [mentioned](https://github.com/atom/settings-view/issues/1052#issuecomment-413828893) which can cause this error.

**Closed by rsese** 2018-08-17 18:18 UTC
