### ISSUE TITLE
ThemePackage.activateConfig is deprecated.

### ISSUE THREAD

**Issue by alexgibson** [atom/settings-view#478] opened 2015-04-24 15:24 UTC
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
ThemePackage.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:247:11)
PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:155:26)
PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:193:12)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:222:24)
```

**Comment by izuzak** [comment] 2015-04-24 15:32
Thanks for the report, @alexgibson -- this looks like a duplicate of https://github.com/atom/settings-view/issues/477. There's a problem with how these deprecated calls are attributed to packages -- this should be fixed when https://github.com/atom/atom/pull/6510 is merged and a new Atom version is released. Currently, those calls are incorrectly attributed to Atom core or to the settings view package.

**Closed by izuzak** 2015-04-24 15:32 UTC
