### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by followtheart** [atom/settings-view#599] opened 2015-07-22 11:17 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Unknown Windows Version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At C:\Users\win8\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56

TypeError: Cannot read property 'message' of undefined
  at ErrorView.module.exports.ErrorView.initialize (C:\Users\win8\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56:21)
  at ErrorView.View (C:\Users\win8\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new ErrorView (C:\Users\win8\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:14:46)
  at C:\Users\win8\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\install-panel.js:156:44
  at Emitter.module.exports.Emitter.emit (C:\Users\win8\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\win8\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:579:27)
  at C:\Users\win8\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:359:17
  at C:\Users\win8\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:384:20
  at exit (C:\Users\win8\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
  at triggerExitCallback (C:\Users\win8\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:213:47)
  at C:\Users\win8\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:220:18
  at Socket.<anonymous> (C:\Users\win8\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:56.7.0 editor:scroll-to-cursor (atom-text-editor.editor.is-focused)
     -0:47.5.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  3x -0:43.1.0 editor:scroll-to-cursor (atom-text-editor.editor.is-focused)
  3x -0:29.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:29.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
 43x -0:28.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:23.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-07-22 11:35
This is a duplicate of #577 – it's been fixed for the next release of Atom.

**Closed by izuzak** 2015-07-22 11:35 UTC
