### ISSUE TITLE
Better error message when attempting to install a package when network is unavailable

### ISSUE THREAD

**Issue by Tails128** [atom/settings-view#1096] opened 2018-12-20 15:52 UTC
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

While the connection's off, an error message is sent. Atom should display a connection message as: "connection not available" in order to be more readable.

### Steps to Reproduce

1. Disconnect
2. settings > install package

**Expected behavior:** I expect to see a "connection not available message displayed instead of the packages"

**Actual behavior:** red error popup (t is not iterable)

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Versions

Atom: 1.32.2
Apm: 2.1.2
OS: debian scratch

### Additional Information

The bug should be os independent

**Comment by rsese** [comment] 2018-12-21 02:19
Thanks for contributing!

Not sure if you had the whole stack trace available but based on the error message you mentioned and the description of the problem, I think this is basically a duplicate of https://github.com/atom/settings-view/issues/962.  You can subscribe there for updates if you'd like and also see the open pull request meant to fix that issue /cc https://github.com/atom/settings-view/pull/1034 - the `Alternate Designs` section mentions your expected behavior as a future possibility to consider.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-12-21 02:19 UTC
