### ISSUE TITLE
Uncaught Error: EMFILE: too many open files, open 'C:\Users\Samuel Tissot\.atom\compile-cache\les...

### ISSUE THREAD

**Issue by SamuelTissot** [atom/settings-view#663] opened 2015-09-22 17:18 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Microsoft Windows 10 Pro
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.216.0

### Stack Trace

Uncaught Error: EMFILE: too many open files, open 'C:\Users\Samuel Tissot\.atom\compile-cache\less\9edab8d65227492bb99018939b842026047d6811\imports.json'

```
At fs.js:97

Error: EMFILE: too many open files, open 'C:\Users\Samuel Tissot\.atom\compile-cache\less\9edab8d65227492bb99018939b842026047d6811\imports.json'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.writeFileSync (fs.js:1165:15)
  at Object.fsPlus.writeFileSync (C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
  at LessCache.module.exports.LessCache.writeJson (C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\less-cache\lib\less-cache.js:155:17)
  at LessCache.module.exports.LessCache.setImportPaths (C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\less-cache\lib\less-cache.js:113:12)
  at LessCompileCache.module.exports.LessCompileCache.setImportPaths (C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\src\less-compile-cache.js:32:25)
  at ThemeManager.module.exports.ThemeManager.refreshLessCache (C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\src\theme-manager.js:421:75)
  at C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\src\theme-manager.js:355:17
  at C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:570:16
  at C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:587:20
  at Emitter.module.exports.Emitter.emit (C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:772:29)
  at Config.module.exports.Config.setRawValue (C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:564:19)
  at Config.module.exports.Config.set (C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:233:14)
  at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\themes-panel.js:487:28)
  at C:\Users\Samuel Tissot\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\themes-panel.js:494:24

```

### Commands

```
     -1:49.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:49.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:47.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:47.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:47.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:44.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:44.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -1:40.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:38.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:35.1.0 core:copy (atom-text-editor.editor.is-focused)
     -1:33.3.0 core:paste (atom-text-editor.editor.is-focused)
     -1:28 core:backspace (atom-text-editor.editor.is-focused)
     -1:27.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:24.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:24.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:18.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "close-tags",
      "project-manager",
      "autocomplete-html-entities",
      "autoclose-html"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.12
htmlhint, v1.1.3
node-debugger, v1.1.8
open_in_cmd, v0.6.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-09-22 17:41
Closing as a duplicate of #653, please subscribe there for updates.

**Closed by 50Wliu** 2015-09-22 17:41 UTC
