### ISSUE TITLE
Find doesn't work

### ISSUE THREAD

**Issue by shawninder** [atom/settings-view#642] opened 2015-08-24 09:29 UTC
When I open the settings in a new tab, I expect to be able to find the particular setting I'm looking for by using `ctrl-f` and typing my keyword, but it doesn't work.

Repro:
1. `cmd-,` opens the settings
2. `ctrl-f` opens the find tool
3. `audio + Enter`
4. EXPECTED the word "audio" of the "Audio beep" setting should be highlighted
5. OBSERVED the find tool doesn't find anything

**Comment by mnquintana** [comment] 2015-08-24 11:06
This looks like a duplicate of https://github.com/atom/settings-view/issues/394 – please subscribe there for updates.

**Closed by mnquintana** 2015-08-24 11:06 UTC
