### ISSUE TITLE
Loading bar with Progress Percentage ██████░░

### ISSUE THREAD

**Issue by neOnSHiFT** [atom/settings-view#681] opened 2015-10-13 02:33 UTC
This is a serius problem for me
Really, most of the time I download a small package and I always cancel it.
Because I felt it take a years to download that package.
The problem is We don't know the progress until the instalation process is done, it just we have to wait and wait without knowing what's happening in the background.
I download a  package that under 100KB (vim-mode in my case), but I noticed why I'm downloading more than 10MB?
Is it downloading another package ,updating atom or something?
Or Maybe you can show/hide console while downloading to see what's happening in the background

**Comment by mnquintana** [comment] 2015-10-13 02:41
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/settings-view/issues/270 - feel free to leave a comment there.

**Closed by mnquintana** 2015-10-13 02:41 UTC
