### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by EzimetYusup** [atom/settings-view#826] opened 2016-08-04 03:04 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.2
**System**: Mac OS X 10.11.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.238.0

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:705

TypeError: Cannot read property 'substr' of null
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:705:80
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:51
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:403:20
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "midnight-picnic"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.9 (active)
atom-beautify, v0.29.10 (inactive)
atom-typescript, v10.1.4 (inactive)
autoclose-html, v0.23.0 (active)
autocomplete-php, v0.3.7 (active)
css-clean, v2.9.0 (inactive)
emmet, v2.4.3 (active)
html-head-snippets, v0.2.0 (active)
html-id-class-snippets, v1.4.1 (active)
intentions, v1.0.5 (active)
javascript-snippets, v1.2.1 (active)
jQuery, v1.2.4 (active)
jshint, v1.8.5 (active)
linter, v1.11.14 (active)
linter-cpplint, v1.0.1 (active)
linter-csslint, v1.3.2 (active)
linter-htmlhint, v1.2.1 (active)
linter-spell, v0.8.0 (active)
linter-spell-html, v0.4.0 (active)
midnight-picnic, v1.1.0 (active)
minimap, v4.24.7 (active)
multi-cursor, v2.1.3 (inactive)
php-cs-fixer, v2.5.6 (active)
remote-edit, v1.8.24 (active)
solarized-dark-ui, v0.3.1 (inactive)
sort-lines, v0.14.0 (inactive)
terminal-plus, v0.14.5 (active)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by auscompgeek** [comment] 2016-08-04 04:13
Just got this whilst updating a bunch of packages (and an error occurred whilst downloading).

**Comment by 50Wliu** [comment] 2016-08-04 13:40
This is a duplicate of #766 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-04 13:40 UTC
