### ISSUE TITLE
Keep getting Type errors

### ISSUE THREAD

**Issue by Toltar** [atom/settings-view#583] opened 2015-07-12 18:28 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At C:\Users\Matthew\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56

TypeError: Cannot read property 'message' of undefined
    at ErrorView.module.exports.ErrorView.initialize (C:\Users\Matthew\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56:21)
    at ErrorView.View (C:\Users\Matthew\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at new ErrorView (C:\Users\Matthew\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:14:46)
    at C:\Users\Matthew\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\updates-panel.js:84:44
    at Emitter.module.exports.Emitter.emit (C:\Users\Matthew\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\Matthew\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:579:27)
    at C:\Users\Matthew\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:303:17
    at C:\Users\Matthew\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:326:20
    at exit (C:\Users\Matthew\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
    at triggerExitCallback (C:\Users\Matthew\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Matthew\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```

### Commands

```
     -0:24.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.1
color-picker, v2.0.10
jshint, v1.3.9
minimap, v4.11.2
node-debugger, vundefined
pigments, v0.8.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-07-12 19:31
@Toltar what were you doing when this happened?  Does it still happen in safe mode (`atom --safe`)?

**Comment by mnquintana** [comment] 2015-07-12 19:39
This is a duplicate of https://github.com/atom/settings-view/issues/577 – it's been fixed for the next release of Atom.

**Closed by mnquintana** 2015-07-12 19:39 UTC
Labels: more-information-needed, uncaught-exception
