### ISSUE TITLE
Uncaught TypeError at installation package (node-on-fire).

### ISSUE THREAD

**Issue by tomvlk** [atom/settings-view#578] opened 2015-07-09 17:25 UTC
Got an Uncaught TypeError at installation of the package node-on-fire:

[Enter steps to reproduce below:]

1. install package
2. crash, boem, bats, exception! Or at least for me, sorry, but I think it would be hard to reproduce the exception...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0

### Stack Trace
```
Uncaught TypeError: Cannot read property 'message' of undefined

At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:56

TypeError: Cannot read property 'message' of undefined
  at ErrorView.module.exports.ErrorView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:56:21)
  at ErrorView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new ErrorView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/error-view.js:14:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:156:44
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:579:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:359:17
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:384:20
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```

### Commands
```
  2x -0:52.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:51.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:51.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:50.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:50.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:50.5.0 editor:newline (atom-text-editor.editor.is-focused)
  9x -0:49.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:43.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:40.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:39.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
 12x -0:39.3.0 core:delete (atom-text-editor.editor.is-focused)
     -0:37.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:35.4.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -0:34.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:34.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "node-resolver"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-modules, v1.0.0
color-picker, v2.0.9
linter, v1.2.3
minimap, v4.11.0
node-debugger, v1.1.4
pigments, v0.8.3
travis-ci-status, v0.15.1

# Dev
No dev packages
```

**Comment by kaiwinter** [comment] 2015-07-10 07:01
Same here on a fresh Atom.

[Enter steps to reproduce below:]

1. Install any package

**Atom Version**: 1.0.2
**System**: xx
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.211.0


### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At D:\dev\tools\Atom\resources\app.asar\node_modules\settings-view\lib\error-view.js:56

TypeError: Cannot read property 'message' of undefined
    at ErrorView.module.exports.ErrorView.initialize (D:\dev\tools\Atom\resources\app.asar\node_modules\settings-view\lib\error-view.js:56:21)
    at ErrorView.View (D:\dev\tools\Atom\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at new ErrorView (D:\dev\tools\Atom\resources\app.asar\node_modules\settings-view\lib\error-view.js:14:46)
    at D:\dev\tools\Atom\resources\app.asar\node_modules\settings-view\lib\install-panel.js:156:44
    at Emitter.module.exports.Emitter.emit (D:\dev\tools\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (D:\dev\tools\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:579:27)
    at D:\dev\tools\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:359:17
    at D:\dev\tools\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:384:20
    at exit (D:\dev\tools\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
    at triggerExitCallback (D:\dev\tools\Atom\resources\app.asar\src\buffered-process.js:213:47)
```

### Commands

```
     -1:40.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:27.1.0 core:copy (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-07-10 12:31
Thanks for the reports. This looks like a duplicate of https://github.com/atom/settings-view/issues/577 -- it will be fixed in the next release.

**Closed by izuzak** 2015-07-10 12:31 UTC
