### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by NatanCieplinski** [atom/settings-view#940] opened 2017-04-20 19:24 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.248.0

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /Applications/Development/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:240

TypeError: Cannot read property 'version' of undefined
    at /app.asar/node_modules/settings-view/lib/package-card.js:240:34
    at /app.asar/node_modules/settings-view/lib/package-manager.js:282:18
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:343:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -1:10.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-LightTable-syntax.theme-slim-dark-ui)
  2x -1:04.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-LightTable-syntax.theme-slim-dark-ui)
     -0:52.8.0 core:confirm (input.hidden-input)
  2x -0:30.3.0 core:move-right (input.hidden-input)
  3x -0:29.8.0 core:backspace (input.hidden-input)
  2x -0:28.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.22 
atom-clock 0.1.7 
atom-material-syntax 1.0.2 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
blessed-light-syntax 0.3.0 
code-dark-ui 0.7.0 
color-picker 2.2.5 
contrast-ui 0.53.0 
duotone-light-syntax 2.1.0 
edm-light-syntax 0.1.2 
file-icons 2.1.3 
git-plus 7.6.0 
gl-light-syntax 2.2.0 
glacier-dark-ui 0.5.0 
highlight-selected 0.13.1 
kuali-dark-ui 1.0.0 
language-swift 0.5.0 
lazy-light-syntax 0.1.1 
LightTable-syntax 0.2.0 
minimap 4.27.1 
minimap-highlight-selected 4.6.1 
naturezen-light-syntax 0.1.0 
ocean-light-syntax 0.2.1 
one-dark-mini-ui 2.0.5 
script 3.14.1 
slim-dark-ui 0.12.0 
```

**Comment by rsese** [comment] 2017-04-20 20:11
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment] 2017-05-15 22:46
Stack track looks the same as https://github.com/atom/settings-view/issues/943 and since there's more commentary there, I'll go ahead and close this one.  If you have steps to reproduce @NatanCieplinski, feel free to drop them in there :v:

**Closed by rsese** 2017-05-15 22:46 UTC
Labels: more-information-needed, uncaught-exception
