### ISSUE TITLE
Failed to activate the vim-mode package

### ISSUE THREAD

**Issue by theprivileges** [atom/settings-view#421] opened 2015-03-11 13:58 UTC
[Enter steps to reproduce below:]

1. Open Atom
2. Open Settings
3. Click on Updates
4. Click on Update All

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to activate the vim-mode package

```
At undefined is not a function

TypeError: undefined is not a function
  at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:355:117)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:243:16)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -0:24.4 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
docblockr, v0.6.3
editorconfig, v0.3.0
file-icons, v1.5.1
highlight-selected, v0.9.1
linter-jshint, v0.1.0
monokai, v0.12.0
vim-mode, v0.37.0

# Dev
No dev packages
```

**Comment by abe33** [comment] 2015-03-13 09:11
Likely a duplicate of #416, please subscribe there for update.

**Closed by abe33** 2015-03-13 09:11 UTC
Labels: bug
