### ISSUE TITLE
Old API deprecation notice might need a change

### ISSUE THREAD

**Issue by AAlakkad** [atom/settings-view#567] opened 2015-07-03 23:52 UTC
Hi,
I'm using v1.0.

In `Settings View`, When click the `Updates` button. Will show the message:
> Deprecated APIs will be removed when Atom 1.0 is released in June. Please update your packages.

We're already on v1 and in July :smile:.

Maybe you want to change the text message or remove it totally.

Thanks!

**Comment by mnquintana** [comment] 2015-07-04 00:59
Thanks for the report! This was fixed in 3f28827. (Also, looks like this is a duplicate of https://github.com/atom/settings-view/issues/561.)

**Closed by mnquintana** 2015-07-04 00:59 UTC

**Comment by AAlakkad** [comment] 2015-07-04 01:00
Aha! Sorry I didn't search in the closed issues, and I'm using the latest stable version not the git version.
