### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/6to5-core/node_modules/regenerator-6to5/node_modules/commoner/node_modules/glob/node_modules/inflight/inflight.js'

### ISSUE THREAD

**Issue by matiasow** [atom/settings-view#395] opened 2015-02-25 19:16 UTC
After installing v0.182.0 I got an error trying to add a new package from UI.

Steps to reproduce: 
1. Go to Atom > Preferences...
2. Select + Install

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.183.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/6to5-core/node_modules/regenerator-6to5/node_modules/commoner/node_modules/glob/node_modules/inflight/inflight.js'

```
At fs.js:503

Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/6to5-core/node_modules/regenerator-6to5/node_modules/commoner/node_modules/glob/node_modules/inflight/inflight.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:136:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:56:16)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at AtomIoClient.module.exports.AtomIoClient.cachedAvatar (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:164:16)
  at AtomIoClient.module.exports.AtomIoClient.avatar (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:25:19)
  at AvailablePackageView.module.exports.AvailablePackageView.loadCachedMetadata (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/available-package-view.js:218:19)
  at AvailablePackageView.module.exports.AvailablePackageView.initialize (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/available-package-view.js:155:12)
  at AvailablePackageView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new AvailablePackageView (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/available-package-view.js:18:57)
  at InstallPanel.module.exports.InstallPanel.addPackageViews (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/install-panel.js:231:41)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/install-panel.js:292:28
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:58:20
  at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:146:16)
  at AtomIoClient.module.exports.AtomIoClient.featuredPackages (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:55:19)
  at InstallPanel.module.exports.InstallPanel.loadFeaturedPackages (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/install-panel.js:285:28)
  at InstallPanel.module.exports.InstallPanel.initialize (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/install-panel.js:138:19)
  at InstallPanel.View (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new InstallPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/install-panel.js:28:49)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:182:18
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:298:19)
  at SettingsView.module.exports.SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:334:24)
  at HTMLAnchorElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:151:24)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop"
    ],
    "themes": [
      "atom-light-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-haml, v0.15.0
ruby-slim, v0.2.0
slickedit-select, v1.3.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-02-25 19:25
Closing as a duplicate of #388, please subscribe there for updates.

**Closed by 50Wliu** 2015-02-25 19:25 UTC
