### ISSUE TITLE
Uncaught Error: Could not resolve 'minimap' to a package path

### ISSUE THREAD

**Issue by dennyabuti** [atom/settings-view#402] opened 2015-03-02 17:40 UTC
Uncaught Error: Could not resolve 'minimap' to a package path

**Atom Version**: 0.162.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.161.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /usr/share/atom/resources/app/src/package-manager.js:347

Error: Could not resolve 'minimap' to a package path
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:347:15)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:409:21)
  at /usr/share/atom/resources/app/src/package-manager.js:295:19
  at /usr/share/atom/resources/app/src/config.js:582:13
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app/src/config.js:690:29)
  at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app/src/config.js:564:19)
  at Config.module.exports.Config.set (/usr/share/atom/resources/app/src/config.js:190:14)
  at SettingsPanel.module.exports.SettingsPanel.set (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:156:28)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:201:26
  at TextBuffer.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at /usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1143:17

```

/cc @atom/core

**Comment by kevinsawicki** [comment] 2015-03-03 01:44
This is a duplicate of https://github.com/atom/settings-view/issues/299

It is fixed in the latest Atom release, 0.184

**Closed by kevinsawicki** 2015-03-03 01:44 UTC
