### ISSUE TITLE
Uncaught Error: EMFILE: too many open files, open 'C:\Users\Artur\.atom\compile-cache\less\40e225...

### ISSUE THREAD

**Issue by radarsu** [atom/settings-view#662] opened 2015-09-22 11:47 UTC
[Enter steps to reproduce below:]

1. Changed Theme
2. ...

**Atom Version**: 1.0.15
**System**: Unknown Windows Version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.216.0

### Stack Trace

Uncaught Error: EMFILE: too many open files, open 'C:\Users\Artur\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'

```
At fs.js:97

Error: EMFILE: too many open files, open 'C:\Users\Artur\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.writeFileSync (fs.js:1165:15)
  at Object.fsPlus.writeFileSync (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279:17)
  at LessCache.module.exports.LessCache.writeJson (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\less-cache\lib\less-cache.js:155:17)
  at LessCache.module.exports.LessCache.setImportPaths (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\less-cache\lib\less-cache.js:113:12)
  at LessCompileCache.module.exports.LessCompileCache.setImportPaths (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\less-compile-cache.js:32:25)
  at ThemeManager.module.exports.ThemeManager.refreshLessCache (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\theme-manager.js:421:75)
  at C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\theme-manager.js:355:17
  at C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:570:16
  at C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:587:20
  at Emitter.module.exports.Emitter.emit (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:772:29)
  at Config.module.exports.Config.setRawValue (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:564:19)
  at Config.module.exports.Config.set (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\src\config.js:233:14)
  at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\themes-panel.js:487:28)
  at C:\Users\Artur\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\themes-panel.js:494:24

```

### Commands

```
  3x -2:54.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:54.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -2:54.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:52.5.0 core:paste (atom-text-editor.editor.is-focused)
     -2:50.4.0 core:undo (atom-text-editor.editor.is-focused)
     -2:47.2.0 core:cut (atom-text-editor.editor.is-focused)
     -2:46.4.0 core:paste (atom-text-editor.editor.is-focused)
     -2:45.1.0 clipboard-history:copy (atom-text-editor.editor.is-focused)
     -2:43.2.0 core:paste (atom-text-editor.editor.is-focused)
  3x -2:32.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:18.6.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
     -2:15.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:57.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:57.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:42.7.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
     -1:38.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "file-icons",
      "slack-chat"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
angularjs-snippets, v0.10.18
angularjs-styleguide-snippets, v0.7.2
atom-beautify, v0.28.12
atom-html-preview, v0.1.11
auto-id-class, v0.2.6
autocomplete-modules, v1.1.0
block-comment-lines, v0.2.4
cdnjs, v1.5.0
clipboard-history, v0.6.6
color-picker, v2.0.12
color-tabs, v0.1.8
color-tabs-regex, v0.2.2
docblockr, v0.7.3
docs-snippets, v0.8.0
font-viewer, v0.3.0
fonts, v0.6.0
foundation5-snippets, v0.2.2
htmlhint, v1.1.3
js-patterns-atom-snippets, v0.2.1
jshint, v1.8.0
keyboard-localization, v1.4.8
keycodes, v0.1.4
local-server-express, v0.3.1
minimap, v4.13.3
pigments, v0.15.0
Remote-FTP, v0.7.2
seti-icons, v0.4.5
smart-tags, v0.1.0
trailing-spaces, v0.3.2
travis-ci-status, v0.18.0
w3c-validation, v0.2.0

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-09-22 11:52
Thanks for the report. This is a duplicate of https://github.com/atom/settings-view/issues/653 and being investigated in https://github.com/atom/atom/issues/8834.

**Closed by izuzak** 2015-09-22 11:52 UTC
