### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by VicVicos** [atom/settings-view#815] opened 2016-07-18 15:47 UTC
[Enter steps to reproduce below:]

1. The reason for the not clear just when writing code crashes after each simovla the entered on another PC with the same set of plug-ins do not have problems .

**Atom Version**: 1.8.0
**System**: Windows 10
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:709

TypeError: Cannot read property 'substr' of null
    at AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:709:80
    at AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:376:51
    at AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:403:20
    at exit AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:215:47)
    at AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:222:18
    at Socket.<anonymous> (AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -4:36.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:36.9.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -4:33.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:22.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -3:21.9.0 core:paste (atom-text-editor.editor.is-focused)
 17x -3:21.3.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -3:05.0 core:select-right (atom-text-editor.editor.is-focused)
     -3:04.2.0 core:delete (atom-text-editor.editor.is-focused)
  6x -3:04.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -3:01.6.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -3:00.8.0 core:select-right (atom-text-editor.editor.is-focused)
     -2:53.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:41 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -2:40.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:40 core:select-left (atom-text-editor.editor.is-focused)
     -2:38.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "color-picker",
      "autocomplete-paths",
      "linter-gjslint",
      "atom-ternjs",
      "auto-detect-indentation",
      "linter-jshint",
      "linter-htmlhint",
      "php-debug",
      "script",
      "project-manager",
      "terminal-plus"
    ],
    "packagesWithKeymapsDisabled": [
      "linter"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yii2, v0.4.0
autocomplete-php, v0.3.7
css-specificity, v0.2.2
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.17
highlight-selected, v0.11.2
jquery-snippets, v11.0.0
linter, v1.11.14
linter-csslint, v1.3.2
linter-php, v1.2.0
minimap-highlight-selected, v4.4.0
pigments, v0.29.2
Stylus, v3.0.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-07-18 17:49
This is a duplicate of #766 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-18 17:49 UTC
