### ISSUE TITLE
Possible to install incompatible packages

### ISSUE THREAD

**Issue by Ben3eeE** [atom/settings-view#871] opened 2016-10-20 19:20 UTC
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

It is possible to install incompatible versions of Atom packages from the settings-view.

#### Prerequsites
Since these tests are using community packages they are done outside of safe mode. I uninstalled all community packages and cleared `init.coffee` and `styles.less` before performing these steps.

#### Method 1
1. Launch Atom using `atom` from `cmd`.
1. Open the `settings-view`.
1. Navigate to the install panel and search for `minimap`.
1. Atom finds the latest version `4.26.0` as of this writing.
1. Click the install button before Atom updates with the latest compatible version, for me this takes up to a few seconds and is something I did by mistake.
1. Check the packages tab version `4.26.0` is installed.
1. Check the `package.json` of the installed `minimap` package. It is `"_id": "minimap@4.26.0",`
1. Try to use the installed `minimap` package it doesn't work.

**Expected:** Atom to install `minimap@4.25.4` which is the latest compatible version as of this writing. Maybe an error if the wrong version has been installed.

**Actual:** Atom installs `minimap@4.26.0` which is not compatible and doesn't work. No error shown.

**Gif of Reproduction:**
![install minimap 4 26 0](https://cloud.githubusercontent.com/assets/1058982/19572907/6495b158-9704-11e6-8a72-056ea908a6d5.gif)

#### Method 2
1. Launch Atom using `atom` from `cmd`.
1. Open the `settings-view`.
1. Navigate to the install panel and search for `minimap`.
1. Atom finds the latest version `4.26.0` as of this writing.
1. Wait for Atom to update with the correct version before clicking install.
1. Expected and Actual: The correct version `4.25.4` is installed.
1. Navigate to the install panel and search for `wegweg`.
1. Search for `minimap`.
1. Expected: version `4.25.4` to be listed with an incompatibility warning. Actual: version `4.26.0` is listed.
1. Uninstall `minimap`
1. Expected: version `4.25.4` to be listed with an incompatibility warning. Actual: version `4.26.0` is listed, Atom never updates with an incompatibility warning.
1. install `minimap`. Version `4.26.0` is installed.

**Expected:** Atom to install `minimap@4.25.4` which is the latest compatible version as of this writing. Maybe an error if the wrong version has been installed.

**Actual:** Atom installs `minimap@4.26.0` which is not compatible and doesn't work. No error shown.

**Gif of Reproduction:**
![install minimap 4 26 0 method 2](https://cloud.githubusercontent.com/assets/1058982/19572921/6f5fa742-9704-11e6-8359-8545b31066c1.gif)

### Versions

Windows 10 x64 anniversary.

###### atom --version
```
Atom    : 1.12.0-beta3
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

###### apm --version
```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.11
git 2.10.1.windows.1
visual studio 2015
```

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by 50Wliu** [comment] 2016-10-20 19:30
This is a duplicate of #732.

**Closed by 50Wliu** 2016-10-20 19:30 UTC
