### ISSUE TITLE
Uncaught TypeError: body.filter is not a function

### ISSUE THREAD

**Issue by Y3ll0WLife** [atom/settings-view#1058] opened 2018-04-24 13:31 UTC
### Description

Have found this bug when trying to search for packages in Atom.

### Steps to Reproduce

1. Go to settings, Install, Packages
2. I searched for "autocomplete python"
3. And I got this error message 

C:\Users\phili\AppData\Local\atom\app-1.26.0\resources\app\node_modules\settings-view\lib\atom-io-client.js:3

TypeError: body.filter is not a function
    at Request._callback (C:\Users\phili\AppData\Local\atom\app-1.26.0\resources\app\node_modules\settings-view\lib\atom-io-client.js:305:39)
    at Request.self.callback (C:\Users\phili\AppData\Local\atom\app-1.26.0\resources\app.asar\node_modules\settings-view\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\phili\AppData\Local\atom\app-1.26.0\resources\app.asar\node_modules\settings-view\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Gunzip.<anonymous> (C:\Users\phili\AppData\Local\atom\app-1.26.0\resources\app.asar\node_modules\settings-view\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

### Version

OS - Windows 10.X
Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
python 3.6.5
git
visual studio

###  More info
This has happend every time I restart my computer and the program.

**Comment by ano95** [comment] 2018-04-24 13:32
Can confirm this happening on my setup too, Ubuntu 16.04. Happens even in `atom --safe`

**Comment by gexter92** [comment] 2018-04-24 13:34
Got the same Error while installing "language-z80asm" under "Install Packages"... 

TypeError: body.filter is not a function
    at Request._callback (/usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:305:39)
    at Request.self.callback (/usr/share/atom/resources/app.asar/node_modules/settings-view/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Gunzip.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

System: Linux Mint 18.2 Cinnamon 64-bit

**Comment by juliancruzsanchez** [comment] 2018-04-24 13:39
When I search anything:

TypeError: body.filter is not a function
    at Request._callback (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:305:39)
    at Request.self.callback (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Gunzip.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by igotinfected** [comment] 2018-04-24 13:43
Update: 
Just before this started happening I enabled autosave in the autosave package settings, disabling this fixed it for me. Even after restart.

**Comment by rsese** [comment] 2018-04-24 23:41
Going to go ahead and close this as a duplicate of https://github.com/atom/settings-view/issues/1052 - for those that haven't already subscribed to #1052 already, feel free to subscribe there for updates.

Thanks for reporting @Y3ll0WLife :v:

**Closed by rsese** 2018-04-24 23:41 UTC

**Comment by akashbaj** [comment] 2020-07-24 18:20
I am still having this error. How do I fix this

**Comment by juliancruzsanchez** [comment] 2020-07-25 21:33
?
