### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/zhangchuzhao/Downloads/Atom.app'...

### ISSUE THREAD

**Issue by zhuifengshen** [atom/settings-view#787] opened 2016-05-15 14:47 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/zhangchuzhao/Downloads/Atom.app'
Error: ENOENT: no such file or directory, lstat '/Users/zhangchuzhao/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:314:24)
    at toRealPath (module.js:113:13)
    at tryFile (module.js:109:22)
    at tryExtensions (module.js:119:20)
    at Function.Module._findPath (module.js:160:20)
    at Function.Module._resolveFilename (module.js:336:25)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at EventEmitter.<anonymous> (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:216:77)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:133:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:113

Error: ENOENT: no such file or directory, lstat '/Users/zhangchuzhao/Downloads/Atom.app'
Error: ENOENT: no such file or directory, lstat '/Users/zhangchuzhao/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:314:24)
    at toRealPath (module.js:113:13)
    at tryFile (module.js:109:22)
    at tryExtensions (module.js:119:20)
    at Function.Module._findPath (module.js:160:20)
    at Function.Module._resolveFilename (module.js:336:25)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at EventEmitter.<anonymous> (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:216:77)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:133:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:113:13)
    at Object.exports.require (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:270:32)
    at AtomIoClient.module.exports.AtomIoClient.getCachePath (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/atom-io-client.js:271:90)
    at AtomIoClient.module.exports.AtomIoClient.createAvatarCache (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/atom-io-client.js:162:31)
    at new AtomIoClient (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/atom-io-client.js:24:12)
    at PackageManager.module.exports.PackageManager.getClient (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:28:64)
    at InstallPanel.module.exports.InstallPanel.initialize (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:135:41)
    at InstallPanel.View [as constructor] (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at InstallPanel.ScrollView [as constructor] (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new InstallPanel (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:32:49)
    at /Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:159:18
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:320:24)
    at HTMLAnchorElement.<anonymous> (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:123:24)
    at space-pen-div.jQuery.event.dispatch (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Users/zhangchuzhao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-05-15 15:29
This is a duplicate of atom/atom#10774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-15 15:29 UTC
