### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory 'C:\Users\Iegor\.atom\packages\autocomplete-plus\lib\provider.coffee'

### ISSUE THREAD

**Issue by underc0de** [atom/settings-view#391] opened 2015-02-24 14:09 UTC
[Enter steps to reproduce below:]

1. File > Settings > Updates and **Update All**

**Atom Version**: 0.182.0
**System**: Windows 7
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.183.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory 'C:\Users\Iegor\.atom\packages\autocomplete-plus\lib\provider.coffee'

```
At C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\src\package.js:241

Error: ENOENT, no such file or directory 'C:\Users\Iegor\.atom\packages\autocomplete-plus\lib\provider.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\atom\common\lib\asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\atom\common\lib\asar.js:329:27)
  at Object.exports._compileFile (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\node_modules\coffee-script\lib\coffee-script\coffee-script.js:206:14)
  at getSourceMap (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\node_modules\coffee-script\lib\coffee-script\coffee-script.js:314:22)
  at getSourceMapping (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\node_modules\coffee-script\lib\coffee-script\coffee-script.js:322:19)
  at formatSourcePosition (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\node_modules\coffee-script\lib\coffee-script\coffee-script.js:274:16)
  at C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\node_modules\coffee-script\lib\coffee-script\coffee-script.js:340:34
  at Function.Error.prepareStackTrace (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\node_modules\coffee-script\lib\coffee-script\coffee-script.js:343:7)
  at Package.module.exports.Package.activateNow (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\src\package.js:241:79)
  at C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\src\package.js:221:28
  at Package.module.exports.Package.measure (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\src\package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\src\package-manager.js:464:21)
  at C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\node_modules\settings-view\lib\package-manager.js:226:29
  at exit (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\Iegor\AppData\Local\atom\app-0.182.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
  4x -2:29.7 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-seti-monokai.theme-seti-ui)
     -2:12.3 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-seti-monokai.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-scala, v1.1.0
seti-monokai, v0.3.1
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-02-25 01:27
Duplicate of #388, please subscribe there for updates.

**Closed by 50Wliu** 2015-02-25 01:27 UTC
