### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by jorcons** [atom/settings-view#820] opened 2016-07-28 10:56 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709

TypeError: Cannot read property 'substr' of null
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709:80
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:51
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:403:20
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -1:05.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.panel-shadows.panel-contrast.use-animations.theme-atom-material-syntax.theme-atom-material-ui.has-custom-icons)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ],
    "excludeVcsIgnoredPaths": false,
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/Jordi/vagrant/VVV-master/www",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.8.3
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.13
autoclose-html, v0.23.0
color-picker, v2.2.2
emmet, v2.4.3
file-icons, v1.7.16
foundation5-snippets, v0.2.2
linter, v1.11.14
linter-htmlhint, v1.2.1
linter-jshint, v2.1.0
merge-conflicts, v1.4.4
minimap, v4.24.7
php-cs-fixer, v2.5.6
pigments, v0.31.1
project-manager, v2.9.7
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by oztalha** [comment] 2016-07-29 20:47
1. Update Hydrogen to version 0.11.0

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1


### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709

TypeError: Cannot read property 'substr' of null
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709:80
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:51
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:403:20
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -0:17.2.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview",
      "autocomplete-python"
    ],
    "packagesWithKeymapsDisabled": []
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.22
jupyter-notebook, v0.0.9
markdown-preview-plus, v2.4.0
pdf-view, v0.50.0
tablr, v1.3.2
terminal-plus, v0.14.5
tool-bar, v1.0.0
tool-bar-markdown-writer, v0.2.0
wordcount, v2.6.2

# Dev
No dev packages
```

**Comment by jorcons** [comment] 2016-07-29 20:47
Esta dirección en breve dejará de funcionar.
Rogamos tome nota del nuevo email: jconstanti@visibletic.com

Visible IT Comunicación
visibletic.com

**Comment by 50Wliu** [comment] 2016-07-30 15:57
This is a duplicate of #766 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-30 15:57 UTC
