### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by keitaj** [atom/settings-view#833] opened 2016-08-23 03:45 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709

TypeError: Cannot read property 'substr' of null
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709:80
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:51
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:403:20
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -4:34.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:12.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:10.1.0 find-and-replace:show (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:44 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -3:32.9.0 editor:toggle-line-comments (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:28.2.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  8x -3:23.5.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
 88x -3:19.7.0 core:undo (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -3:02.7.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 89x -1:42.5.0 core:redo (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:30.8.0 core:move-left (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  6x -1:30.4.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:27.5.0 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -1:27.2.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -1:26.5.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:25.5.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
api-blueprint-preview, v0.7.0
compare-files, v0.6.2
file-icons, v1.7.18
go-plus, v4.2.0
godoc, v0.3.1
gofmt, v1.1.8
language-haskell, v1.7.17
language-jade, v0.7.1
linter, v1.11.16
linter-ruby, v1.2.2
markdown-preview-plus, v2.4.0
tester-go, v1.0.6
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment] 2016-08-23 06:04
Looks like a duplicate of https://github.com/atom/settings-view/issues/766 which was fixed in Atom 1.9.8.

**Closed** 2016-08-25 17:46 UTC
