### ISSUE TITLE
Some enabled packages don't show a settings button while some disabled packages do

### ISSUE THREAD

**Issue by olmokramer** [atom/settings-view#471] opened 2015-04-21 07:21 UTC
See this image:
![settings weird](https://cloud.githubusercontent.com/assets/3612514/7247196/0f3738e2-e807-11e4-955e-f8b28dca9646.png)
As you can see, it seems kind of random which packages get a settings button and which do not. The majority of the packages don't have the settings button, and now I can't go to their details page anymore.

**Comment by olmokramer** [comment] 2015-04-21 07:42
Ah, it seems packages that don't have settings don't have a settings button. Kindof makes sense I guess :p Anyway, the details page has more features than just settings (readme, links to atom.io, github.io, open in atom etc.) that I like to use, so it would be nice to be able to get to their details page as well :)

**Comment by izuzak** [comment] 2015-04-21 07:44
For packages which don't have a Settings button, you can just click on the package card and it will take you to the details view.

**Comment by olmokramer** [comment] 2015-04-21 07:53
D'oh! Can't believe I didn't try that :p Thanks!

It's nice (really super nice) that I can see now which packages have settings, so I don't have to go through each package anymore, but I think the settings button is a little confusing. When there's a button it makes me think it's the only way (at least in the button's context) to accomplish it's action. The card could just as well show a little icon indicating that the package has settings to configure.

**Comment by izuzak** [comment] 2015-04-21 08:01
Did you see https://github.com/atom/settings-view/issues/355 where this change was discussed (and https://github.com/atom/settings-view/pull/443 which implemented this)? /cc @mnquintana 

> The card could just as well show a little icon indicating that the package has settings to configure.

Not sure I understand what you mean -- can you clarify, or even better provide a screenshot of a mock up?

**Comment by izuzak** [comment] 2015-04-21 08:03
Also, I've added an enhancement label to this issue since this is working as intended, but it would be great if you could clarify what exactly you'd like to see improved and how. Changing the title would help as well. :mag:

**Comment by olmokramer** [comment] 2015-04-21 08:13
I'm sorry, I searched the open issues, but not the closed ones :flushed:

I meant that when the  button as well as the entire card for the package do the same thing, the button is kind of pointless, and it could just as well be an icon (just like the download and version numbers have) that indicates the package has settings.

[This](https://github.com/atom/settings-view/issues/355#issuecomment-85704026) is what I had in mind. I see I could have been clearer about this :).

I think I can close this issue, as #443 is basically the same discussion.

**Comment by izuzak** [comment] 2015-04-21 10:39
Thanks for clarifying. Yeah, I think we can close this and please feel free to add your comments/feedback to that existing issue. I think it's good to know that this is causing confusion (and keep everything in one place). 

:cocktail:

**Closed by izuzak** 2015-04-21 10:39 UTC
Labels: enhancement
