### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory 'C:\Users\admin\.atom\packages\autocomplete-plus\lib\provider.coffee'

### ISSUE THREAD

**Issue by oliveiraeduardo** [atom/settings-view#413] opened 2015-03-09 12:45 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: Unknown Windows Version
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.183.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory 'C:\Users\admin\.atom\packages\autocomplete-plus\lib\provider.coffee'

```
At C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\src\package.js:243

Error: ENOENT, no such file or directory 'C:\Users\admin\.atom\packages\autocomplete-plus\lib\provider.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\atom\common\lib\asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\atom\common\lib\asar.js:329:27)
  at Object.exports._compileFile (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\node_modules\coffee-script\lib\coffee-script\coffee-script.js:206:14)
  at getSourceMap (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\node_modules\coffee-script\lib\coffee-script\coffee-script.js:314:22)
  at getSourceMapping (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\node_modules\coffee-script\lib\coffee-script\coffee-script.js:322:19)
  at formatSourcePosition (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\node_modules\coffee-script\lib\coffee-script\coffee-script.js:274:16)
  at C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\node_modules\coffee-script\lib\coffee-script\coffee-script.js:340:34
  at Function.Error.prepareStackTrace (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\node_modules\coffee-script\lib\coffee-script\coffee-script.js:343:7)
  at Package.module.exports.Package.activateNow (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\src\package.js:243:79)
  at C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\src\package.js:221:28
  at Package.module.exports.Package.measure (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\src\package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\src\package-manager.js:464:21)
  at C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\node_modules\settings-view\lib\package-manager.js:226:29
  at exit (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\admin\AppData\Local\atom\app-0.186.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
     -2:41.2 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -2:23.9 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
coffee-lint, v0.7.3
color-picker, v1.4.4
editor-stats, v0.17.0
file-icons, v1.5.1
jshint, v1.3.0
linter, v0.12.0
linter-jshint, v0.1.0
linter-jsl, v0.0.1
linter-php, v0.0.11
linter-phpcs, v0.0.12
linter-phplint, v0.0.7
monokai, v0.12.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-09 12:52
Duplicate of #388.  This will be fixed in the next Atom version.

**Closed by 50Wliu** 2015-03-09 12:52 UTC
