### ISSUE TITLE
Uncaught Error: ENOENT

### ISSUE THREAD

**Issue by BlueAccords** [atom/settings-view#722] opened 2016-01-14 19:47 UTC
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/BlueAccords/Documents/Atom.app'

error occurred after a fresh download(potentially corrupted? didn't check checksums/hashes. The internet connection i'm using has trouble loading pages constantly). And trying to open the theme picker. Quitting and restarting atom and going back to the welcome page and trying to open the theme picker afterwards solved it.

``` 
Error: ENOENT: no such file or directory, lstat '/Users/BlueAccords/Documents/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/lib/parse.js:4:18)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/lib/cheerio.js:6:13)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/index.js:5:28)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/roaster/node_modules/task-lists/lib/index.js:4:11)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/roaster/lib/roaster.js:14:15)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/roaster/lib/roaster.js:73:4)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-readme-view.js:8:13)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-readme-view.js:72:4)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:26:23)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:441:4)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:24:23)
    at Object.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:369:4)
    at Module._compile (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at createSettingsView (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:20:22)
    at /Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:71:28
    at Workspace.module.exports.Workspace.openURIInPane (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/workspace.js:460:22)
    at Workspace.module.exports.Workspace.open (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/src/workspace.js:399:19)
    at HTMLButtonElement.<anonymous> (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/welcome/lib/guide-view.js:302:31)
    at HTMLButtonElement.jQuery.event.dispatch (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Users/BlueAccords/Documents/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)

```

**Comment by 50Wliu** [comment] 2016-01-14 20:20
Hi @BlueAccords, thanks for reporting!  This looks like a duplicate of #7399 though, so if you could add your comments to that issue, that would be great :smile:.

**Closed by 50Wliu** 2016-01-14 20:20 UTC
