### ISSUE TITLE
Packages installed via apm are listed under Installed Packages but show "Install" buttons

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#336] opened 2015-01-12 17:28 UTC
**Expected:** After installing any number of packages via `apm install`, the Installed Packages pane should show cards for each of these packages, and these cards should show the standard buttons (ie. Settings, Disable, etc)

**Actual:** After installing any number of packages via `apm install`, the Installed Packages pane shows cards for each package installed, but they still show an "Install" button. Restarting Atom will result in the correct buttons being shown.

**NOTE:** This applies to Themes too.

![screenshot from 2015-01-12 12 21 49](https://cloud.githubusercontent.com/assets/823545/5707331/04c4b53c-9a56-11e4-9b57-5323755ad5b1.png)

**Steps to reproduce:**
1. Open Atom
2. Run `apm install toggle-quotes` (for example, as long as you don't already have it installed)
3. Open Settings
4. Click Packages
5. Scroll to or filter for `toggle-quotes`
6. The `toggle-quotes` package card should be there, but with an "Install" button

**OS:** Ubuntu 14.04 LTS
**Atom:** 0.169.0

**Comment by thedaniel** [comment] 2015-01-12 23:16
Those button states change after events fired by the package manager in the editor (i.e. not apm run outside of atom), but should also check install state when the card is first rendered. It looks like they might not. Thanks for the bug report, we'll hopefully clean it up soon!

**Comment by mnquintana** [comment] 2015-01-12 23:39
@thedaniel Would you be open to any PRs for some of these open issues (specifically for settings-view)? I've been diving into Atom's codebase a little lately and I'd love to help out. :smiley:

**Comment by thedaniel** [comment] 2015-01-12 23:41
Yes, absolutely. We would love PRs.

**Comment by kevinsawicki** [comment] 2015-01-13 19:26
I think this is a duplicate of https://github.com/atom/settings-view/issues/157 which talks about the settings views being out of sync with packages installed from the CLI.

**Closed by kevinsawicki** 2015-01-13 19:26 UTC
