### ISSUE TITLE
Installed packages don't get refreshed after apm install

### ISSUE THREAD

**Issue by mgarciaisaia** [atom/settings-view#542] opened 2015-06-12 03:32 UTC
1 - Open Atom
2 - Open Settings
3 - Go to Packages
4 - Wait for the list to be shown
5 - Run `apm install some-new-package` from the CLI
6 - Atom doesn't show the new package in the Installed Packages list - and you can't refresh that list

We should add a `Refresh installed packages list` command, a `Refresh list` button in the Installed Packages pane and bind `CMD/Ctrl + R` in that pane to the command.

**Comment by mnquintana** [comment] 2015-06-12 03:44
Thanks for the suggestion! This is a duplicate of https://github.com/atom/settings-view/issues/157 - let's move the discussion there.

**Closed by mnquintana** 2015-06-12 03:44 UTC

**Comment by mgarciaisaia** [comment] 2015-06-12 03:45
Ouch - sorry about that!
